### ISSUE TITLE
[EN][NPC][RAID] Beth'Tilac [Firelands] high priority

### ISSUE THREAD

**Issue by sunshitwowsucks** [Atlantiss/BugTracker#7892] opened 2016-07-23 06:57 UTC
Beth "Cinderweb Drone" is using Burning Acid on everyone. - It should choose a random person and only 1

^ is really hard to heal that

at 5% after phase 2, beth goes back up and comes back down?

**Comment by Aldergar** [comment] 2016-07-23 11:24
#6031 Going to update the post

**Comment by Aival94** [comment] 2016-07-23 14:00
The reason it go up and down is because of a glitch because of the last fix "when boss will hit 5% hp while still on the web, she will go down and trigger phase 2". There is no other condition to check if is first phase or second phase so she always do it.

About the burning acid i can confirm.

**Comment by Sayris9876** [comment] 2016-07-23 14:44
Also the drone "Consumes" the small spiders (getting dmg increase) without the small spiderlings even hit the drone on top of everyone getting hit by Burning Acid makes the fight really hard to be done right now

**Comment by Aival94** [comment] 2016-07-23 15:10
@Sayris9876 when this happened.After last update for us the drone did not eat the spiderlings before it reach it. Are you sure you have done it after last update(yesterday around 10:00 server time i believe).

**Comment by Kaldros** [comment] 2016-07-23 19:58
On top of the overwhelming damage from Burning Acid, she also bugs on pull.
Sometimes when you pull her and tank goes up, she ignores him and continues spraying Venom Rain. Sometimes she just wipes the raid that way, sometimes she unbugs and starts targeting after a while. Other times she acts normally. I don't know what the exact cause is, but it should be looked into.

Also, Quban, could you actually test bosses before the updates go live? Or you know, check your code and fix mistakes before all hell breaks loose?
The same thing happened when Rhyolith's script was rewritten and it lasted until Wolffenstein fixed it after 2-3 weeks.

**Comment by Quban** [comment] 2016-07-23 21:10
im testing it, try to test bosses alone

**Comment by sunshitwowsucks** [comment] 2016-07-23 21:35
testers on ptr can work

**Comment by Quban** [comment] 2016-07-25 14:54
fixed in http://atlantiss.eu/changelog#rev5114

**Closed by Quban** 2016-07-25 14:54 UTC
Labels: Raid - Cata
