### ISSUE TITLE
[EN][Spell][Class][Item] Frost mage + Teracgosa behaviour.

### ISSUE THREAD

**Issue by ExoDuSSS123** [Atlantiss/BugTracker#9650] opened 2017-11-02 09:15 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Frost mage's main dmg source is talent  **Fingers of Frost**. After I got legendary I discovered annoying bug, There are 3 spells using  **Fingers of Frost**: Ice Lance / Deep Freeze / Frostfire Bolt. 

**Current behaviour**: Each time u use | Ice Lance / Deep Freeze / Frostfire Bolt | with **Fingers of Frost**(2 stacks on you) , and legendary clones them. Your 2nd proc will be eaten aswell.

**Expected behaviour**: Cloned spells of **Fingers of Frost** shouldn't eat another stack.

**Steps to reproduce the problem**:

1. Hit 2 stack's of **Fingers of Frost**
2. Use  Ice Lance / Deep Freeze / Frostfire Bolt 
3. Wait for one of those spells to clone with 2 stack's of **Fingers of Frost** on you.
4. Watch how it eats your extra dmg.

**Revision**: ACore rev. 5535

**Comment by ExoDuSSS123** [comment] 2017-11-02 09:24
I posted similar issue of Elemental Shaman+ Teracgosa over 1month ago but it was ignored ( mby bcs I wrote it in polish) https://github.com/Atlantiss/BugTracker/issues/9542

**Comment by fluessig** [comment] 2017-11-02 11:16
A frost mage's [Ice Lance] will consume a second stack of [Fingers of Frost], if one is present, upon duplication.

https://wow.gamepedia.com/Dragonwrath,_Tarecgosa%27s_Rest

**Comment by Psychobird7** [comment] 2017-11-02 12:56
Can we get credible sources on the matter?

**Comment by kadi2** [comment] 2017-11-03 02:02
Working as intended.

**Comment by Psychobird7** [comment] 2017-11-03 11:38
http://www.mmo-champion.com/threads/1027271-DTR-eats-Hot-Streaks 

#3: "DTR eats any caster's proc of this kind. For example, it also eats Nightfall, Glyph of Corruption and Molten Core procs for warlocks." 

#5: "I'm guessing you noticed this when you went to throw a pyro and hard cast it instead? This is how I noticed it. Yes it adds stacks, to Arcane Blast, it will also Eat FoF procs if you proc a 2nd Ice Lance. IMO this should be fixed." 

Let's close this report please.

**Closed** 2017-11-03 15:42 UTC
