### ISSUE TITLE
[en][Mage][general bug possibly] petattack vs. combat

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4920] opened 2015-11-13 20:51 UTC
## What's wrong:

If you /petattack an enemy player, it puts you in combat.
## How it should be:

If you /petattack an enemy player, you should enter in combat after your pet reaches and succesfully attacks that target.

Currently this is bugged for Mages, I don't know for other classes,but more than sure is same for Udks,Hunters,Enha Shamans,Locks,Boomkins with trents probably,etc

**Comment by razgal** [comment] 2015-11-13 20:52
this is can be very gamebreaking in pvp, because mages can't get sapped against rogues in bgs/arena  if they know to abuse this.

**Comment by Kejmil** [comment] 2015-11-13 22:10
hunters confirmed, was killed by game when i was logging out because of this :D

**Comment by lamaATS** [comment] 2017-10-10 13:18
Fixed in rev. 5533

**Closed** 2017-10-10 13:34 UTC
Labels: Pets
