### ISSUE TITLE
[EN][Talent][Warrior][Toughness]

### ISSUE THREAD

**Issue by sigmundfreud2016** [Atlantiss/BugTracker#5105] opened 2015-12-02 19:50 UTC
Gives much less than 10% armor bonus.
With 3/3 Toughness:
![wowscrnshot_120215_204510](https://cloud.githubusercontent.com/assets/12395407/11542093/06f34cc6-9936-11e5-873b-fef0d520303e.jpg)
With 0/3 Toughness:
![wowscrnshot_120215_204519](https://cloud.githubusercontent.com/assets/12395407/11542103/125e81c0-9936-11e5-8f42-54512953fe88.jpg)
Without any armor-giving items (so you can't tell me that most of my armor doesn't come from items and is therefore not affected by the talent):
![wowscrnshot_120215_204931](https://cloud.githubusercontent.com/assets/12395407/11542158/3e17f67a-9936-11e5-9c04-37e9c87d188f.jpg)

**Comment by Thefakemccoy** [comment] 2015-12-02 19:53
Try it with out heirlooms on druids had the same issue wearing heirlooms.

**Comment by sigmundfreud2016** [comment] 2015-12-02 20:00
Ok, on 79 I will check it with cata gear only. Don't want to waste more money on resetting. Anyway it is not normal. I thought "ok, I rarely use Heroic Strike, so I ll better get 2.5% passive dmg reduction". But instead I got absolutely nothing.

**Comment by Thefakemccoy** [comment] 2015-12-02 20:26
You dont have to wait or respec. Take all your heirlooms off and any gear with armor. Then put the sheild on see what the armor is on it add 10% see if you get that in the char screen.

**Comment by sigmundfreud2016** [comment] 2015-12-02 20:53
I ve already respecced back in Incite, so I have to respec at least once in Toughness and probably again if it still doesn't work.

**Comment by Quban** [comment] 2015-12-03 02:07
anyway link to toughness would be nice ;D

**Comment by Thefakemccoy** [comment] 2015-12-03 02:16
Rank ! http://cata.openwow.com/spell=12299
Rank 2 http://cata.openwow.com/spell=12761
Rank 3 http://cata.openwow.com/spell=12762

Hope that helps Quban

**Comment by Jenovas** [comment] 2016-01-09 15:15
The bug with Toughness is that it doesnt work with the Warriors Shield. It properly increases armor of gear but it doesnt increase the armor of a Shield.

**Comment by Kejmil** [comment] 2016-01-09 16:24
then paladin's equivalent of this talent can be affected in same way
http://cata.openwow.com/spell=20143 r1
http://cata.openwow.com/spell=20144 r2
http://cata.openwow.com/spell=20145 r3

**Comment by gumby123** [comment] 2016-05-20 10:32
6 months and Atlantiss still cannot compute 1.1x of total armor value
AMAZING

**Comment by Jenovas** [comment] 2016-05-20 18:34
gumby123 - post deleted. I really dont care what you think + I'll fix it when I feel like it / have time to fix something so minor. Cheers

**Comment by stanq87** [comment] 2016-05-21 11:53
is there a chance that [Austere Shadowspirit Diamond](http://wow.gamepedia.com/Austere_Shadowspirit_Diamond) also ignores shiled ?

also shiled give about 1/4 of total armor for warriors so it would be nice to have this talent work as intended

**Comment by gumby123** [comment] 2016-05-21 12:47
@Jenovas Warrior tanks are severely inferior to other tanks on this server, and nothing is being done to fix it.

1. Thunder Clap doesn't work on ~50% of the bosses. So if you have a warrior tank in your raid, the boss will hit **20% more often** than with any other tank. **That's 20% more damage**!

It's either caused by fucked-up boss hit box, that is outside of range of 6-yard Thunderclap, or fucked-up boss spell immunity (thunderclap gives slow -> bosses are immune to slow -> bosses ignore Thunderclap)

2. Warrior's armor calculation is wrong. As said before, shield is the item that gives a SIGNIFICANT amount of total armor to any shield-wearing tank.

3. **Block, dodge, parry calculation are taken from the moon**. It doesn't check with any tank addon, doesn't check with Rawr program. My warrior tank has ~4% less chance to block, ~1% less chance to parry and ~1% less chance to dodge on Atlantiss versus Rawr. Same buffs, same gear, same setup. That's 6% of avoidance missing completely.

4. I won't even go into critical block and talents affecting mastery and critical block. With the blizzard's default character panel it's impossible to check these stats reliably, but it's very likely that warrior's mastery and any talents affecting mastery are also fucked up on Atlantiss.

5. Bottom line is this - if you want to raid on Atlantiss, you don't want to have a warrior tank in your raid.

**Comment by Jenovas** [comment] 2016-05-22 15:09
> Thunder Clap doesn't work on ~50% of the bosses. So if you have a warrior tank in your raid, the boss will hit 20% more often than with any other tank. That's 20% more damage!
> It's either caused by fucked-up boss hit box, boss being "physically" outside of 6-yard range of Thunderclap, or a fucked-up boss spell immunity (thunderclap gives slow -> bosses are immune to slow -> bosses ignore Thunderclap)

Tell me which boss

> I won't even go into critical block and talents affecting mastery and critical block. With the blizzard's default character panel it's impossible to check these stats reliably, but it's very likely that warrior's mastery and any talents affecting mastery/critical block are also fucked-up on Atlantiss.

Proof or didnt happen.

> Block, dodge, parry calculation are taken from the moon. It doesn't check with any tank addon, doesn't check with Rawr program. My warrior tank has ~4% less chance to block, ~1% less chance to parry and ~1% less chance to dodge on Atlantiss versus Rawr. Same buffs, same gear, same setup. That's 6% of avoidance missing completely.

Rawr was never accurate, I also used it and it didn't work properly for half of the classes / specs / stats. Show me the numbers.

**Comment by Jenovas** [comment] 2017-01-02 17:05
Fixed in rev 5277

**Closed by Jenovas** 2017-01-02 17:05 UTC
Labels: Class - Warrior
