### ISSUE TITLE
[EN][Quest][Badlands] Olaf, the Big Fella'

### ISSUE THREAD

**Issue by martinelrey1979** [Atlantiss/BugTracker#4283] opened 2015-08-18 01:11 UTC
It fulfills the mission is not whatever you do please verify
http://www.wowhead.com/quest=27835/olaf-the-big-fella

**Comment by Pallitax** [comment] 2015-08-18 06:42
Duplicate of #3304

**Closed** 2015-08-18 11:21 UTC
