### ISSUE TITLE
[EN][Mage] Ignite (not the double dipping issue)

### ISSUE THREAD

**Issue by aneq** [Atlantiss/BugTracker#4452] opened 2015-09-09 15:09 UTC
There is a bug with ignite that will hurt fire mages a lot once firelands are released.
If another crit is added to the ignite "bank" ignite shouldn't tick, thus increasing the bank. 
Right now Ignite just keeps ticking even if its refreshed so it's impossible to build a large ignite bank that can then be used on combustion.
How it should work : if a mage crits on a target that already has his ignite, the remaining ignite should be rolled into the new ignite and should not tick. In theory, if you can consistently land a crit with every ~1.5 sec, before ignite ticks for the first time, ignite will never tick but keep building up more and more.
How to reproduce : it's bit impossible for a regular player but a dev with gm commands should be able to easily reproduce it. 
1) Get enough haste so fireball or pyroblast has ~1 sec cast time.
2) Get 100% crit through an aura or something.
3) Get near a target dummy and start casting.
4) ONCE YOU STARTED CASTING DON'T MOVE SO THE INTERVAL BETWEEN HITS IS EXACTLY THE SAME (althouth this doesn't matter because the ignite isnt working properly ;D)
You will see, that even though you keep critting every 1 second the ignite is still ticking, making it impossible to bank a huge ignite for a huge combustion

proof : http://us.battle.net/wow/en/forum/topic/3195920164 - alysrazor fire mage guide

**Comment by ezzira** [comment] 2015-09-11 03:14
you described this a bit confusing, because like you said:"Right now Ignite just keeps ticking even if its refreshed.." it is working correct. 
Ignite works like this: "Ignite stacks when a target is crit twice (or more via Dragonwrath) before ignite ticks (2 seconds) the ignite's strenth will stack and be nearly twice as strong. Two hits at the same time do not cause ignite to stack. One of the values will be munched."

so ignite only stacks if you crit 2+ times within 2 seconds, but it does not stack when you crit twice at the same time or if you crit after the 1st tick (2 seconds).

**Comment by aneq** [comment] 2015-09-11 09:42
"so ignite only stacks if you crit 2+ times within 2 seconds, but it does not stack when you crit twice at the same time or if you crit after the 1st tick (2 seconds)."

Did you ever play a mage? Because it's not how it works. Not only what you wrote here is wrong (ignite will stack if you crit after the first tick, just it will be less than optimal because one tick will expend half of the ignite bank already), but you seem to have trouble reading, because what I posted here clearly mentions consistently critting BEFORE the 1st ignite tick.
You don't seem to know how ignite works so I'll explain it to you properly.

 When you crit, 40% of the damage dealt is left on the target as a DoT effect for 4 seconds ticking 2 times, once every 2 seconds. However, if you crit while ignite is already on a target, the new ignite value is added to the old ignite and the damage is recalculated.
example : 

00:00 You crit with fireball for 25k damage, 10k ignite is created
00:02 Ignite ticks once for 5k damage, 5k remaining in the ignite "bank"
00:03 You crit with fireball for 25k damage, 10k ignite is added to the remaining 5k, resulting in 15k ignite
00:05 Ignite ticks once for 7,5k damage, 7,5k ignite remaining

Now let's see what happens if you can consistently land crits every ~1.5 seconds

00:000 You crit with fireball for 25k damage, 10k ignite is created
00:015 You crit with fireball for 25k damage, 10k is added to the remaining ignite, resulting in 20k ignite bank
00:030 You crit with fireball for 25k damage, 10k is added to the remaining ignite, resulting in 30k ignite bank
00:045 You crit with fireball for 25k damage, 10k is added to the remaining ignite, resulting in 40k ignite bank
00:060 You crit with fireball for 25k damage, 10k is added to the remaining ignite, resulting in 50k ignite bank
00:075 You crit with fireball for 25k damage, 10k is added to the remaining ignite, resulting in 60k ignite bank

As you can see, ignite never ticks and so the ignite bank keeps growing. It might seem that there is no difference because ignite damage stays the same. The difference is in the combustion. Combustion is based on all your active dot effects on the target. Having 300k ignite banked is having combustion ticking for at least 300k per second for 10 seconds.

Here is what currently happens on Atlantiss™

00:000 You crit with fireball for 25k damage, 10k ignite is created
00:015 You crit with fireball for 25k damage, 10k is added to the remaining ignite, resulting in 20k ignite bank
00:020 Ignite ticks for 10k, 10k ignite remaining in the bank
00:030 You crit with fireball for 25k damage, 10k is added to the remaining ignite, resulting in 20k ignite bank
00:040 Ignite ticks for 10k, 10k ignite remaining in the bank
00:045 You crit with fireball for 25k damage, 10k is added to the remaining ignite, resulting in 20k ignite bank
00:060 Ignite ticks for 5k damage, 5k ignite remaining in the bank
00:060 You crit with fireball for 25k damage, 10k is added to the remaining ignite, resulting in 15k ignite bank
00:075 You crit with fireball for 25k damage, 10k is added to the remaining ignite, resulting in 25k ignite bank
00:080 Ignite ticks for 12,5k, 12,5k remaining in the bank

As you can see, because the ignite keeps ticking despite being refreshed constantly, its impossible to build a big ignite bank, resulting in lackluster combustions.

**Comment by ezzira** [comment] 2015-09-11 14:34
Thanks for that wall of text :) but i played a mage, and i understand how ignite works, it just seems you are missing some information, thats why you're thinking it's bugged.
Ignite does not work like a regular DoT, thats the key part. When you refresh a normal DoT(Living Bomb for example) it refreshes the duration of the DoT and adds the last tick to the refreshed DoT.

Living Bomb ticks for 12 seconds (1 tick every 3 seconds)-> You refresh Living Bomb for at 1 seconds remaining so the time gets refreshed to 0 and the last tick is added to the new Living Bomb DoT.

But Ignite doesn't work like that. The Ignite DoT doesn't get refreshed if you reapply it, its more like the ticking DoT get expanded by the new Ignite ticks. What this means is that if you reapply Ignite before it runs out, the new ticks will be added to the old Ignite and the damage gets recalculated, but its still the old Ignite tick (it's not a new DoT, just a expanded time and recalculated damage). "As you can see, because the ignite keeps ticking despite being refreshed constantly.." thats the point. Ignite doesn't get refreshed.

**Comment by aneq** [comment] 2015-09-11 17:09
This might've been poor choice of words on my part (refreshing). Currently on Atlantiss, refreshing a DoT doesn't reset the tick timer (and that is correct)
You know what I thought you might be right and I rewatched the vid the guide creator provided (https://www.youtube.com/watch?v=OOo-9p_-AXc) at 0.25 speed and took a really close look at damage values from floating combat text. (0:20-0:40) 
The only damage is pyroblast damage, pyroblast dot damage, and living bomb damage (there is a lot of living bomb ticks because of him having shitload of haste due to the buff from alysrazor encounter). Look at his ignite counter in the upper right corner, near his minimap. It's steadily growing like I explained in the first post.
The problem on Atlantiss still remains, because the ignite keeps spending its damage so you cant bank a huge ignite.

**Comment by ezzira** [comment] 2015-09-12 02:52
When you watch the video you can see his ignite ticks, just watch closely before his combustion his ignite ticks for about 80k (240k ignite banked). Okay after re-reading your other posts i think i got the problem now, you misunderstood how ignite stacking works, which is not a big deal, because ignite is actually a pretty complicate spell, so i'll try to explain it, but that shit is some serious math ;)

Ignite's initial application will be 4 seconds in duration: 2 ticks, one at 2 seconds, one at 0 seconds. Ignite's total damage pool is divided between these two ticks. Any reapplies (new crit) at any time will extend ignite to 6 seconds in (max) duration (current duration is ignite's current duration mod 2 plus 4 seconds): 3 ticks, one at 4 seconds, one at 2 seconds, one at 0 seconds. Ignite's damage pool is divided evenly between these three ticks (Ignite must be below 4 seconds in current duration to accept any new reapplies). You can stack ignite up by landing critical hits when your old ignite is still ticking on the mob. When this happens, the damage left from your old ignite (if it ticked 2 times already, it will have 1/3 of the total damage left. If it ticked 1 time, 2/3 of the total damage left) will be added to the ignite damage from your freshly landed crit.
So for a really big ignite you want to crit (and stack) it between the 4 seconds and the 2 seconds tick, that 2/3 of your remaining ignite damage will be added to the new ignite damage from your latest crit.

But Ignite has been always bugged due to limitations in the game engine. These bugs are refered to as "Ignite Munching". Basically when your ignite gets munched, you loose all the remaining damage it still hadn't dealt and just get the damage from your freshly landed crit. There are 3 different situations when this can happen:
Crits that land at the same time (or at least nearly), for example if you cast a HS Pyro right after a Fireball and they both crit at the same time (than the 1st crit will be "munched" and you only get ignite from the 2nd crit).
Crits that land when Ignites timer is above 4 seconds. Because of the scripting of how ignite works it will only accept crits that are under the 4 seconds tick.
Crits that land just before the Ignite is about to tick. This is caused by the small delay in between the crit hitting the mob & ignite being applied.

**Comment by aneq** [comment] 2015-09-12 08:23
You're probably right, sorry about the agressive language I did use before, but usually on this bugtracker most people don't know what they're talking about (this time it turned out to be me)
I'm gonna close this, cheers.

**Closed** 2015-09-12 08:23 UTC
Labels: Class - Mage

**Comment by ezzira** [comment] 2015-09-12 11:51
No problem dude, im glad i could help and keep on burning :)
