### ISSUE TITLE
[EN][Quest][The Cape of Stranglethorn] Drive-By Piracy

### ISSUE THREAD

**Issue by Champions2012** [Atlantiss/BugTracker#3973] opened 2015-07-27 14:52 UTC
This quest cannot be completed because u get under water instead on the boat and u can't shoot on the goblins:
http://www.wowhead.com/quest=26649/drive-by-piracy
![wowscrnshot_072715_061136](https://cloud.githubusercontent.com/assets/13512234/8909060/c4b4fdd4-347f-11e5-9ad3-ad182a194801.jpg)
![wowscrnshot_072715_061304](https://cloud.githubusercontent.com/assets/13512234/8909061/c4b91fcc-347f-11e5-8fc9-d63df02638bc.jpg)

**Comment by Pallitax** [comment] 2015-07-27 20:24
Duplicate of #360.

**Closed** 2015-07-27 20:27 UTC
