### ISSUE TITLE
[EN][Dragon Soul][Ultraxion][Warlock][Pet][Felhunter]

### ISSUE THREAD

**Issue by Pocketerino** [Atlantiss/BugTracker#9906] opened 2018-03-10 14:08 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Pet twisting is a core part of the Warlock class, currently it's impossible to it do on Ultraxion. The issue only happens if you summon exclusively the Felhunter after the pull, if you go from for instance Felguard to Felhunter then the Felhunter won't spawn, and it bugs other pets out so they can't be summoned either. If you pull with the Felhunter out it works correctly, however if you try to resummon after the pull then it won't spawn again. You have to go through the whole fight with the same pet, if it's the Felguard you lose out on your pet dps, cuzz the Felhunter is the superior option for single target, and if you start with Felhunter you'll lose out on your major dps cooldown, Demon Soul, as you're using the weaker version of it. Felhunters also don't work in Sethria's Roost in Mount Hyjal, interestingly it only happens to this perticular pet.

**Current behaviour**: If you try to pet twist/change pet after the pull to Felhunter it won't spawn and your other pets will bug out and won't be able to spawn either.

**Expected behaviour**: Felhunter should correctly spawn and attack the boss and let you switch pets after that.

**Steps to reproduce the problem**:

1. Have a Felguard or any other pet except the Felhunter summoned.
2. Start Ultraxion 10/25 man.
3. Try to summon a Felhunter.
4. Cry.

**Revision**: 5683.

**Comment by lostmyusername** [comment] 2018-03-12 12:13
experienced a related issue yesterday. my pet died during trash and i didnt resummon it. we got soaked into twilight (before the fight started) and i couldnt summon ANY other pet (tried felguard, felhunter, imp and voidwalker), had to go through the whole fight without a pet at all.

**Comment by stanq87** [comment] 2018-03-12 17:44
seen this happen to a hunter :P

**Comment by xmesaj2** [comment] 2018-03-15 23:33
Since I cannot reproduce it the way described, any more information could be helpful, preferably video of the fight when this happens, details on which spells did you use, which part of boss encounter it happens exactly etc

**Comment by stanq87** [comment] 2018-03-16 10:22
so the issue hapens when a pet is dead or not summoned/revived/called when by the time the player is "pulled"/given the buff that placees him/her in the shadow realm,  so like the pet are in a difrent phase which is bloking the player from affecting them

**Comment by pelekon** [comment] 2018-04-14 00:24
fixed in  5732

**Closed by pelekon** 2018-04-14 00:24 UTC
Labels: Content: Cata, Raid
