### ISSUE TITLE
[Eng][Druid][Talent] Master Shapeshifter

### ISSUE THREAD

**Issue by Andarien** [Atlantiss/BugTracker#2091] opened 2015-02-07 13:45 UTC
Talent does not increase healing in caster form. Damage for bear and critical for cat work well, but healing stays the same no matter the form. It was not increased at all after I used the point in that talent.

http://www.wowwiki.com/Master_Shapeshifter

**Comment by Jenovas** [comment] 2015-02-09 15:48
How did you check this?

**Comment by Andarien** [comment] 2015-02-09 16:41
What do you mean by "how"? 
When I place my cursor over any healing skill, I can see how much it heals. And the numbers didn't change after I placed my talent point on this talent. Also, I tested it on practice, not only by looking at skill description.
Even much weaker talent "Blessing of the grove" increased rejuvenation healing. "Improved rejuvenation" gave even more bonus. Master shapeshifter gave nothing. I reseted my talents three times (wasted a lot of gold) and tested all my healing skills both BEFORE and AFTER taking the talents. Other talents have effect, this one - not.

**Comment by Varchord** [comment] 2015-02-10 06:21
Master shapeshifter does not Chang your spell power. It modifies you healing spells making them 4% stronger
But since you've checked that too I'm assuming wollf must've broken something else when he fixed infinite stacking of this aura

**Comment by Andarien** [comment] 2015-02-10 06:33
I know that it does not increase spell power. I was not checking character stats, but the number that is written on the spells. For example, Rejuvenation, "Heals the target for 114 every 3 sec for 12 sec". 
This number changes when you take other talents, like "Blessing of the grove", which increased to 116 (it gives +2% to rejuvenation). Master shapeshifter should give two times more, 4%, but the spell description remains the same.

And I checked the actual healing too, not only the description. Used all the spell few times before taking the talent, and AFTER that too - no effect at all.

**Comment by GtGraphics6** [comment] 2015-03-12 20:45
I can confirm this, actually the master shapeshifter isnt working in any of the 4 forms, and sometimes i dont even have it as a buff, same happens to my friend

**Comment by Isuel** [comment] 2015-03-21 18:12
it's like this:
switching out of travel or flight form (aquatic probably, too) into cat -> no cat master shapeshifter.
switching out of travel or flight (or aquaqtic, prolly) into bear -> no bear master shapeshifter.
shifting out of any form into caster form -> no healing shapeshifter.
shifting out of travel or flight form (prolly aquatic) into cat or bear, then changing from cat to bear and vice versa or powershifting into those same forms -> no master shapeshifter.

**Comment by Liebeqt** [comment] 2015-03-21 18:18
Also doesn't work for Moonkin Form.

Upon shifting into Moonkin Form there's no Master Shapeshifter Bug that would grant 4% increased damage.

**Comment by Wolffenstein** [comment] 2015-03-22 14:23
Fixed in rev 4365.

**Closed by Wolffenstein** 2015-03-22 14:23 UTC
Labels: Class - Druid
