### ISSUE TITLE
[EN][Quest]Grandma's Cat wargen starting quest

### ISSUE THREAD

**Issue by matbra30** [Atlantiss/BugTracker#3329] opened 2015-05-22 20:05 UTC
Tried to get near cat and game crashed now character is stuck crashing upon loading.  Tried to do fixes from http://atlantiss.eu/community/viewtopic.php?f=10&t=1117 and now my game can't start up.  It says Cannot stream required archived data.  Please check network connection. I tried to set everything back to normal, but that still doesn't work. Only thing left is to redownload game :\

**Comment by Thefakemccoy** [comment] 2015-05-22 23:36
Heard of this issue but i never had any issue when i started my worgen. Which client are you using. Mini, Torrent.

If the mini has it finished downloading?

**Comment by Aival94** [comment] 2015-05-23 22:32
i do not thinks this caused to one of the cliens only as i have this issue with either the mini and the torrent one.

**Comment by Tj20** [comment] 2015-05-30 00:53
I can confirm this bug. I did the quest once and it worked fine, so it does not seem to be a problem of my Atlantiss mini client.

I deleted my cache folder before starting a new worgen on a different account, so I think me having done this quest previously shouldn't be a problem.

Here is what happened:

1. I came from [Grandma Wahl](http://www.wowhead.com/npc=36458) with the Quest [Grandma's Cat](http://www.wowhead.com/quest=14401/grandmas-cat). Zone: "Wahl Cottage". I had my mouse cursor over the cat, [pic](http://i.imgur.com/NjWEDyw.jpg)

2. I ran towards the cat. When the zone changed to "Gilneas" and I was right in front of the cat, the game crashed at location (34,74). I had my mouse cursor on the cat the whole time.

![pic](http://i.imgur.com/QGbq2vn.jpg)

I repeated my test after having used the unstuck option. Again I kept my mouse cursor on the cat while walking towards it, and again the game crashed at the same location. This time I had abandoned the quest, I was walking towards the cat without the quest.

![pic](http://i.imgur.com/rMElO1Q.jpg)

Other people were not nearby. I had completed the quest successfully before on another account so I know it works (deleted cache afterwards), but this time it did not, I suspect it happened because I had him under my mouse cursor during my zone change, but I'm not sure.

Can't really test this well because after every crash you would have to buy an unstuck thingy and have the hearthstone CD ready.

**Comment by Tj20** [comment] 2015-06-14 20:44
I believe this issue was closely related to Lorna Crowley (#2493) and that it has been fixed in [rev. 4458](http://atlantiss.eu/changelog#rev4458) by Wolffenstein. I couldn't reproduce the client crash around Grandma's cat any more.

**Closed** 2015-06-15 08:32 UTC
Labels: WoW Error
