### ISSUE TITLE
[EN][Spell][Hunter] Burning Adrenaline can be consumed by Lock n' Load procs

### ISSUE THREAD

**Issue by MellenIO** [Atlantiss/BugTracker#9130] opened 2017-05-02 12:48 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: The 4-piece T12 bonus given by Flamewalker's Battlegear allows a chance to proc [Burning Adrenaline](http://www.wowhead.com/spell=99060/burning-adrenaline), a spell that has no ICD and sets the cost to your next shot/KC as 0. What I have noticed is that, sometimes, if Lock n' Load (the talent that, on chance from explosive trap/black arrow periodic hits, will give you 2x  free explosive shots) and Burning Adrenaline overlap each other (ie both are active at the same time), there is a chance (not all the time!) that Burning Adrenaline will be consumed with the free explosive shot given by Lock n' Load (this should not be the case - [read here](http://www.wowhead.com/spell=99060/burning-adrenaline#comments:id=1492567))

**Current behaviour**: There is a chance that Burning Adrenaline will be consumed by the free Explosive Shot given by Lock n' Load

**Expected behaviour**: The Lock n' Load procs should **not** consume Burning Adrenaline.

**Steps to reproduce the problem**:

1. Get 4 piece t12 set bonus
2. Be survival
3. Engage a mob
4. Apply black arrow/explosive shot
5. Pray both Lock n' Load and Burning Adrenaline proc at the same time
6. Use your free Lock n' Load shots

**Revision**: ACore rev 5377, hash 82ed4a08bc04

**Comment by szapol** [comment] 2017-05-02 13:35
#6119
#8974 
good luck xd

**Comment by MellenIO** [comment] 2017-05-02 14:20
I searched in the bug tracker to see if this was already reported and nothing turned up so I wrote this up since it's a really annoying bug in PVE.

A sidenote, here, does the same happen to the free aimed shot proc in MM?

**Comment by xolon** [comment] 2017-05-02 19:05
@MellenIO I believe it was fixed long time ago, hence i closed it #6341

**Comment by MellenIO** [comment] 2017-05-02 19:43
@xolon Nope, still there. It's a lot easier to see if you have something such as Simple Power Auras to show you when the buff is active.

**Comment by xShojirox** [comment] 2017-05-05 05:11
@MellenIO @xolon [https://github.com/Atlantiss/BugTracker/issues/6341](#6341) is a slightly different issue than this. This is about burning adrenaline being used by abilities that cost 0 focus (because of a talent proc) where [https://github.com/Atlantiss/BugTracker/issues/6341](#6341) is about burning adrenaline not being used by aimed shot at the finish of an aimed shot cast when burning adrenaline procs in the middle of the cast (this is not an issue for Lock and Load as there is no cast time on Explosive Shot).

What @MellenIO was talking about was when you have the stacked buff to give you a free aimed shot, is burning adrenaline used by that free aimed shot?

Now I have not tested if [https://github.com/Atlantiss/BugTracker/issues/6341](#6341) is actually fixed or not, but regardless this issue should actually be closed as this is just a duplicate of [https://github.com/Atlantiss/BugTracker/issues/6119](#6119).

**Comment by xShojirox** [comment] 2017-09-14 23:16
Aside from this being a duplicate of [#6119](https://github.com/Atlantiss/BugTracker/issues/6119) as I stated in my previous message, this issue should also be closed because it has been fixed. This was fixed by lama in revision 5498.

**Closed** 2017-09-15 10:56 UTC
Labels: Hunter, Spell
