### ISSUE TITLE
[EN][BG] Attack own team

### ISSUE THREAD

**Issue by druque** [Atlantiss/BugTracker#7555] opened 2016-06-02 21:48 UTC
Very occasionally, 3 times in at least 50 battlegrounds, I get the message 'Your raid group has been disbanded' and from then on, I can attack my own teammates. They can't attack me back, but their pets will attack if I attack first. This causes many problems since I can accidentally (or deliberately) sabotage my own team.

Me: Horde, goblin, frost mage
First happened: Since rated BG system (maybe coincidence), but I did at least 100 bgs before that and it never happened, but 3 times since then

It has happened two times in Arathi Basin and one time in Alterac Valley. When it happens, I can't use /bg chat anymore or see the scoreboard, but I can stay in bg and get honor and conquest points as normal.

The bg starts fine, but somewhere like 5 minutes it I get the message and bg becomes a lot harder to know who the enemies are.

**Comment by Jenovas** [comment] 2016-06-03 13:16
Yes this may be caused by RatedBG, thank you for your report, I will have a look at this.

**Comment by Jenovas** [comment] 2016-06-06 11:30
Should be fixed in rev 5041

**Closed by Jenovas** 2016-06-06 11:30 UTC
