### ISSUE TITLE
[EN][Quest][Badlands] The Day that Deathwing Came: The Real Story

### ISSUE THREAD

**Issue by martinelrey1979** [Atlantiss/BugTracker#4285] opened 2015-08-18 01:12 UTC
It fulfills the mission is not whatever you do please verify

http://www.wowhead.com/quest=27714/the-day-that-deathwing-came-the-real-story

**Comment by Pallitax** [comment] 2015-08-18 06:41
Duplicate of #1358

**Closed** 2015-08-18 11:21 UTC
