### ISSUE TITLE
[EN][SPELL][MAGE][Ignite] ignite stacking only 300k cap

### ISSUE THREAD

**Issue by demaciaprotector37** [Atlantiss/BugTracker#8567] opened 2016-11-16 23:41 UTC
**Description**: Ignite has a 300k cap on the server.

**Current behaviour**: Ignite stacking caps at 300k

**Expected behaviour**: The cap should be more than 300k.

Here is a video showing retail of 4.3.4 with the Combustion Helper Addon:

https://www.youtube.com/watch?v=1kkYzbWhSvU
After 3:20 you can ignite going over 300k. and you even see some ticks on it, 

Image showing over 300k: (this is from video)
![7cd6ec5a4e4318fd4a7eec3abe716fb1](https://cloud.githubusercontent.com/assets/22946546/20370205/7ac2bcc8-ac2b-11e6-9bb7-4c33e201d92a.jpg)

**Steps to reproduce the problem**:

1. Go into combat with Alysrazor Normal or HC, as fire mage.
2. Get Alysra's razor and 25 haste stacks.
3.  Spam pyroblast until Combustion helper shows a red 300k or recount data shows ignite tick max 300k
4. see as ignite ticks  never goes above 300k.

**Revision**: 5252

**Comment by kadi2** [comment] 2016-11-16 23:52
Aye, it could be something like the cap was let's say 200k and then it was modified by buffs like mastery. I don't see other explanation to this.

**Comment by Illusie** [comment] 2016-11-17 08:21
I have 450k on my Mage on Alys hc.

**Comment by sunshitwowsucks** [comment] 2016-11-17 11:10
It was 450k for a few days, but they changed it back to 300k. recently

**Comment by kadi2** [comment] 2016-11-17 11:32
Aye the cap is 900k indeed, it's just divided by ammount of ticks.

**Comment by lamaATS** [comment] 2016-11-17 13:33
As You said in issue `Go into combat with Alysrazor Normal or HC, as fire mage.` it's only possible on Alysrazor and 300k damage per tick makes this boss easy and that's why for my Very Log Priority.

**Comment by sunshitwowsucks** [comment] 2016-11-17 13:39
I think it was fine before that dot fix, at least for ignite.

**Comment by lamaATS** [comment] 2016-11-17 13:56
Ignite was not changed in last days. (If you are talking that cap was 450k it was only for one day because of bug with duration.)

**Comment by Illusie** [comment] 2016-11-17 14:24
Is it still possible to one shot Alys hc as Mage with 300k? with 450k I could ;/

**Comment by sunshitwowsucks** [comment] 2016-11-17 14:29
Probably with 1 mage it's not.

**Comment by Aldergar** [comment] 2016-11-17 14:30
We did Alysrazor HC yesterday,and our mage could 1 shot the boss just fine.

**Comment by LaveniaGithub** [comment] 2016-11-17 14:30
It is, unless other people's dps is very low :)

**Comment by Illusie** [comment] 2016-11-17 14:50
Anyway interesting issue right here.
I thought because I stacked Mastery for Alys my ignite went to 450k ^^
I will try to kill alysrazor hc this saturday with my Mage,
but previous tries when I killed it. I had 450k ignite. 300k is alot less (150k less / 50% less)
Hope it still possible.

Let you know soon ^^..

**Comment by Mordorianin** [comment] 2016-11-22 07:44
U cant solo Alys HC Illusie. U need the other person flying to do at least 60k+ to do that.

**Comment by Illusie** [comment] 2016-11-22 11:58
Yeah can comfirmed.
Mage cannot solo Alys heroic with Ignite capped to 300k.
Unless someone has a trick and want to teach us :D

According to demaciaprotector37 (the Issue opener) it also not-blizzlike that the ignite is capped to 300k.
This limitation ruin the Alys fight in four aspects.

The first aspect is that FL hc bosses in Atlantiss are buffed. Bosses (in this case Alysrazor) has more Health or Armor or both.

The second aspect is the Ignite cap to 300k so your combustion do less damage potential than it suppost to be /Retail. CAUSE: damage-loss.

Conclusions: (Theory numbers)
If your Combustion suppost to hit 40-50mil (with Bigger number Ignite lets say 450k-500k) but it does 25m cause of Limitation of 300k ignite.
there is 15mil "gap" that someone need to close it. in this case 2nd flyer as Mordorianin mentioned.
But because the boss itself has more health/armory the gap is not 15mil is even greater.

The three aspect the boss fight should not last more than 5-6min or as someone whispered me yesterday. "More than one vortex"
Unable to kill it on first attempt is failure of your group, and failure of your Mage. when the things are suppost to work as Retail.

The fourth aspect is the Ground-team.
Because it mandatory to get 2nd flyer you lose a DPSer on talons, meteors, hatchlings
And that without mentioning that boss still shooting Brushfire and Fieroblast when people are in LoS.

Make the all fight "Almost" Impossible & RNG.
(yes with "" in purpose because there still groups who can kill Alysrazor even with all those problems.) 

disclaimer: everyone who gonna say: "kill it next circle or get 2nd fly player". It's totaly wrong behavior Alysrazor fight.

@Alysrazor totaly not-blizzlike #confirmed.
Sorry for my bad english & grammer.

**Comment by kadi2** [comment] 2016-11-22 15:57
In bug reports you have to provide the info how it should work, not how it shouldn't work. So start make your researches on your own.
http://www.worldoflogs.com/ranking/eu-us/firelands/alysrazor/heroic-10/dps/ // Might be helpful for you guys at the beggining.

**Comment by lamaATS** [comment] 2016-11-22 16:49
```
Yeah can comfirmed.
Mage cannot solo Alys heroic with Ignite capped to 300k.
Unless someone has a trick and want to teach us :D
```
And that's the point only one Mage shouldn't be able to kill BOSS on HEROIC sorry.
Ignite is the biggest bug in this game on Cata that's why it has been completely reworked in MoP because they didn't had control how it's working and like you saw stacking to infinity is very stupid and it's not mechanic like someone will say IT'S A BUG.

```
disclaimer: everyone who gonna say: "kill it next circle or get 2nd fly player". It's totaly wrong behavior Alysrazor fight.
```
Take 2 or 3 Mages raid is not made to be done solo.

I can make Ignite to work like it should on retail (no stacking to infinity and dealing damage) but when I do this mage will be completely useless class.

So what is better Cap which can be reached only on ONE boss or properly stacking ignite.

**Comment by Psychobird7** [comment] 2016-11-22 16:51
A mage can solokill Alysrazor, unless you suck.    
Our mage can solokill Alys on his ilvl 346 alt so git gud :D

**Comment by Illusie** [comment] 2016-11-22 17:26
@lamaATS I'm not arguing.
Just ook at the WorldofLogs link, all the mages doing 66m-68m damage which is 100% of Alysrazor HC health on RETAIL.

According to this information the boss can be solo'ed by 1 flyer (Mage)

here on Atlantiss there 2 things that make it impossible to 1 shot it by mage.
the first one is the FL hc buffs you did for all the bosses in Heroic mod.
the second one is the ignite limitation.

both things are not blizzlike and leave a "gap" that need to be filled with 2nd flyer.

@Psychobird7 
I am standing on 235k dps with my Mage which is higher than on those Logs.
70m damage total and boss still alive because he have additonal 15% health/armor

Maybe I'm wrong but 2 things are against blizzlike and Alysrazor heroic encounter look like a big joke.

But let's say you are not suppost to do it with 1 flyer.
atleast fix other issues on "ground group" to make it possible to do it with lack of 1 dpser because he has to fly.

Thank you.

**Comment by kadi2** [comment] 2016-11-22 18:07
But the logs are from t13 patch, not 4.2, the gear they have makes diffrence aswell.

**Comment by lamaATS** [comment] 2016-11-23 00:56
```
on same analogy - You should nerf BDK vs Baleroc because he heal too much.
or Beacon of Light heal 150k+ beacuse Vital Flame.
```
You probably don't understand what I mean. Problem is not with the boss but with Ignite BUT only this boss can be one shot because of this bug.

```
here on Atlantiss there 2 things that make it impossible to 1 shot it by mage.
the first one is the FL hc buffs that been given to all the bosses in Heroic mod.
the second one is the ignite limitation.
```
1. is custom because it's patch 4.3.4 and here FL has been nerfed so this shouldn't be used as argument because this change more sense on progressing FL
2. that's the point of this limit which affect ONLY this boss

```
but atleast fix other issues on "ground group" to make it possible to do it with lack of 1 dpser because he has to fly.
```
When I was reading this it was like `this boss can't be done without mage`.

The problem is:
1. I want make mage on this fight less dps to disallow him to one shot boss.
2. You want solo kill this boss even in a group because maybe other dpsers are too low.

Conclusion by me:
I'm not going to change this because someone wants to one shot boss and the limit for me it's still too high because can be reached only on this fight because of crit & ignite bug so I'm not going to change anything in Ignite (no increase nor reduce limit) because only argument to do this is that You want to kill boss in one group phase if You really want to do this take 2-3 mages.

**Comment by Illusie** [comment] 2016-11-23 11:07
You take it too personal, It's not about me want to 1 shot it, its about the currect behaviour of the Mage vs Alysrazor in this expansion. I said it many times I never played wow in retail at Cataclysm.
I hope maybe someone  who played at 4.2 will tell us how it was.

And I told you. I don't really have a problem with the boss. (except 55 wipes on it) we (my group) can send 2nd flyer but the 'ground scene' in this boss is f----d up so sending 2nd flyer cause a DPS loss.
Beside, I know there still groups who make it the way it is now.

Now lets back to the topic. (full disclosure my last post too cause it's bigger then me xD)

As you said the Ignite been fixed at MoP when people had 600k health by default and could solo entire FL.
but with correct gear item level no one can solo FL.

From what I understand the limitation of Ignite also limit of how strong your Combustion will be.
From my evaluations the Combustion here with 80 ticks will be maximum 25mil. When in Retail (even on 4.2) I believe you could produce higher Combustion.

Here is the Graph I made to explain the "gaps" between ATS to Retail.
http://imgur.com/a/NETUg

The first gap - 70m health vs 84m health - 14m health gap. (caused by atlantiss costume buff)
The second gap - 25m combustion vs 30-40m or greater combustion -12m gap (caused by atlantiss combustion limitation)

the third gap (not in the graph) is lets say "IF" the ignite was capped to 450k, it means 150k+ damage per tick (450-300=150), now lets say your 450k ignite tick 30 times. you earn another 4.5m damage from Ignite.

Thank you for your time LamaATS & everyone else.

**Comment by sunshitwowsucks** [comment] 2016-11-23 11:28
Actually the health is the correct values from 4.2, after firelands nerfs in 4.3 the hp from bosses became lower. (we are on 4.2 content?)

**Comment by LaveniaGithub** [comment] 2016-11-23 12:14
Yea, but we have damage reduction auras applied. Health of the boss is the same, the damage you do is the same, but if you check total damage on recoint afterwards, you will see that you did a lot more damage to the boss than its total health.

**Comment by Fabiana-B** [comment] 2016-12-06 19:44
> @lamaATS: When I was reading this it was like this boss can't be done without mage.

There's a Heroic FL group who done Alysrazor without a mage? :3

**Comment by LaveniaGithub** [comment] 2016-12-06 19:47
There is no problem doing it without mage at all.

**Comment by stanq87** [comment] 2018-02-27 01:07
so look at parry and dodge of Decimating Strike and Inferno strike on retail
![bez tytulu2](https://user-images.githubusercontent.com/16665131/36704861-96c88590-1b62-11e8-8595-3fa9d9920f03.jpg)
now on atlantiss
![bez tytulu](https://user-images.githubusercontent.com/16665131/36704865-98ead328-1b62-11e8-8e66-856fe25d2699.jpg)
and: no, the tank was not crappy

**Comment by Jenovas** [comment] 2018-06-26 18:06
Not a bug, it's a custom fix to not allow soloing T12 bosses by mages.

**Closed by Jenovas** 2018-06-26 18:06 UTC
Labels: Class: Mage, Low Priority, Spell - Generic, Status: Confirmed
