### ISSUE TITLE
[EN][Quest][Silverpine Forest] It's Only Poisonous if You Ingest It

### ISSUE THREAD

**Issue by Lanrutcon** [Atlantiss/BugTracker#366] opened 2014-11-22 04:21 UTC
# What is not working:

If you use the item, you won't get credit after dealing the rest of the dmg to kill the mob.
Tried in the opposite way, by dealing dmg first and then drop the chicken, but after you aggro it, he won't eat it.
In order to complete this quest, I had to "solo" it, no quest-item used.

Another issue: there are around 4 mobs in the same area (instead of one), all of them are not moving as they should.

---
# How should work:

First, this mob should patrol path instead of 4 mobs in "guard-mode".
The mob should always eat the chicken if there is one nearby, even if you have the aggro.
You should get credit of the kill even if you use the item (which is how suppose to be).

---
# More info:

[Video#1](http://youtu.be/OJ_r15P8RDQ?t=3m20s)
[Video#2](http://youtu.be/PrUe4hy07sw?t=14s)
[Video#3](http://www.youtube.com/watch?v=0Shvl1Y-eA4)
[It's Only Poisonous if You Ingest It - WoWHead](http://www.wowhead.com/quest=27088)
[Forest Ettin - WoWHead](http://www.wowhead.com/npc=44367)
[Mutant Bush Chicken Cage - WoWHead](http://www.wowhead.com/item=60808)

**This was tested on 4.0.6a realm**

**Comment by Angelo-DM-** [comment] 2015-01-18 16:27
When you use the [Mutant Bush Chicken Cage (ID: 60808)](http://www.wowhead.com/item=60808), near one [Forest Ettin (ID: 44367)](http://www.wowhead.com/npc=44367) correctly a chicken is pawned, properly it goes towards the [Forest Ettin (ID: 44367)](http://www.wowhead.com/npc=44367), it is eaten by him and correctly the [Forest Ettin (ID: 44367)](http://www.wowhead.com/npc=44367) get poisoned and he start to attack you!
The problem is that the [Forest Ettin (ID: 44367)](http://www.wowhead.com/npc=44367) with the [Bush Chicken Explosion (ID: 83903)](http://www.wowhead.com/spell=83903) debuff does not give credit for the quest if you kill it. Only the NOT poisoned [Forest Ettin (ID: 44367)](http://www.wowhead.com/npc=44367) give you the credit!

**Comment by Enay** [comment] 2015-08-12 06:04
Confirming, still bugged.

**Comment by tondiaq44** [comment] 2015-10-12 15:33
i managed to complete the quest by simply not using the chicken and bursted down the Etin and i received the kill credit.

**Comment by Angelo-DM-** [comment] 2015-11-11 14:12
Still "bugged"...

You can complete this quest only if you kill the mob without using the quest item.

The problem is that the [Forest Ettin (ID: 44367)](http://www.wowhead.com/npc=44367) with the [Bush Chicken Explosion (ID: 83903)](http://www.wowhead.com/spell=83903) debuff does not give credit for the quest if you kill it. Only the NOT poisoned [Forest Ettin (ID: 44367)](http://www.wowhead.com/npc=44367) give you the credit!

**Comment by eryczek1615** [comment] 2015-12-11 16:13
bump

**Comment by dmucya** [comment] 2016-04-21 08:02
bump

**Comment by JohannDoe** [comment] 2016-07-15 12:25
confirmed

**Comment by ylluminarious** [comment] 2016-12-04 22:37
+1

**Comment by krecik88** [comment] 2017-01-14 22:33
fixed in 5287

**Closed by krecik88** 2017-01-14 22:33 UTC
Labels: Quest - Classic
