### ISSUE TITLE
[PL][ITEM] Firelands Trinkets

### ISSUE THREAD

**Issue by Nc94** [Atlantiss/BugTracker#5493] opened 2015-12-28 21:47 UTC
http://www.wowhead.com/item=68995/vessel-of-acceleration
http://www.wowhead.com/item=68972/apparatus-of-khazgoroth
http://us.battle.net/wow/en/forum/topic/3050125027

Oba te trinkety powinny mieć 100% szansy na proc 1 stack buffka przy melee critical hit, przy czym powinno naliczać crity ze zwykłych melee ataków jak i zdolności melee np. Crusader Strike, Templar's Verdict oraz Judgement i Hammer of Wrath (które jako tako nie są melee atakami lecz powinny procować buffki - "Judgement procs apparatus, as does hammer of wrath. At 3 stacks you can wings and get 2 stacks in to basically overlap the trinket with wings for full duration (you end up missing a second total but thats nitpicking).").

Niestety u nas oba trinkety procują tylko od critów zwykłych melee ataków przez co są useless gdyż nie ma możliwośći wbicia i utrzymania 5 stacków buffa, prawdopodobnie sytuacja ma miejsce z innymi tego typu trinketami lecz trzeba to sprawdzić.

**Comment by Iskra12** [comment] 2015-12-29 06:57
To ja dorzucę od siebie jeszcze Eye of Blazing Power. 
http://www.wowhead.com/item=68983/eye-of-blazing-power
Trinket odpala się co 45s ale zamiast jednego targetu leczy cały raid za ~14k. Jeden cast Prayer of Healing pozwolił mi na wygenerowanie około 250k healingu. Jak wrócę z pracy wrzucę screena.

**Comment by Jenovas** [comment] 2015-12-29 12:54
Eye of Blazing Power fixed in rev 4755

**Comment by freddie12** [comment] 2015-12-29 15:08
Can someone translate it to English because i think apparatus has some problems with death knight's attack as well.

**Comment by Nc94** [comment] 2015-12-29 15:58
@freddie12 
In short Apparatus and Vessel stacks are procing only form melee atacks but not from "melee abilities" = GL with stacking it to 5.

**Comment by freddie12** [comment] 2015-12-29 16:28
yea that's what i'm saying too. it doesnt proc from Killing Machine proc attacks of death knights as well. so it makes the trinket just a crap.

**Comment by Kejmil** [comment] 2015-12-29 18:14
procFlags trzeba ustawic na 0x14 w 96981, 97143 i 96924 w spellproevent skoro pobranie danych z dbc sobie nie poradzilo

**Comment by freddie12** [comment] 2015-12-30 21:14
bump

**Comment by Beatit** [comment] 2016-01-01 14:45
Eye of Blazing Power nie crtituję a powinno (200% heala)

**Comment by freddie12** [comment] 2016-01-01 19:34
i'm leaving this link as a proof. 
link: https://www.youtube.com/watch?v=G_YOYhnnHZY

**Comment by freddie12** [comment] 2016-01-04 12:52
bump.

**Comment by ponpontos** [comment] 2016-01-05 15:55
Kind of annoying that you close English tickets just because there are PL tickets open. As a non-Polish speaker I have no idea of what's going on this thread. 

But I'd like to confirm that Apparatus (http://www.wowhead.com/item=68972/apparatus-of-khazgoroth) is not working as intended; supposed to be bis as of 4.2 on frost DK, currently almost impossible to stack it.

**Comment by Kejmil** [comment] 2016-01-05 18:58
INSERT INTO spell_proc_event (`entry`, `procEx`, `procFlags`, `Cooldown`) VALUES
(96981, 0x2, 0x14, 0) ON DUPLICATE KEY UPDATE  Cooldown = 0, procEx = 0x2, procFlags=0x14;

INSERT INTO spell_proc_event (`entry`, `procEx`, `procFlags`, `Cooldown`) VALUES
(97143, 0x2, 0x14, 0) ON DUPLICATE KEY UPDATE  Cooldown = 0, procEx = 0x2, procFlags=0x14;

INSERT INTO spell_proc_event (`entry`, `procEx`, `procFlags`, `Cooldown`) VALUES
(96924, 0x2, 0x14, 0) ON DUPLICATE KEY UPDATE  Cooldown = 0, procEx = 0x2, procFlags=0x14;

**Comment by freddie12** [comment] 2016-01-05 19:02
Nice. This prolly means that we will get a fix soon.

**Comment by arranmc** [comment] 2016-01-05 20:40
I hope the trinket will be fixed really soon I farmed and spent allot of gold on it :(

**Comment by freddie12** [comment] 2016-01-08 20:40
bump

**Comment by Kejmil** [comment] 2016-01-08 21:57
#fixforagitrinketinonedayafterreportbutnoonecaresenoughaboutstrtrinkets

**Comment by Bastion** [comment] 2016-01-08 23:20
fix achievement!

**Comment by Jenovas** [comment] 2016-01-08 23:40
Fixed in rev 4791. And Kejmil stop QQ.

**Closed by Jenovas** 2016-01-08 23:40 UTC
Labels: Item, New Content

**Comment by Bastion** [comment] 2016-01-08 23:53
naprawi jeszcze acziw, ładnie proszę :D
