### ISSUE TITLE
[Spell][Druid] Lifebloom (instant heal while getting disspelled)

### ISSUE THREAD

**Issue by phifedawg** [Atlantiss/BugTracker#5266] opened 2015-12-14 09:16 UTC
http://cata.openwow.com/?spell=33763

The Lifebloom's instant heal after getting disspelled doesn't work. I only tested it with a mage spellstealing it, so i'm not sure about priest's and shaman's dispell/purge. It might be a core issue, but i couldn't tell.

**Comment by gurin** [comment] 2015-12-14 10:27
A spell stolen lifebloom does not bloom. And should not.

**Comment by phifedawg** [comment] 2015-12-14 10:32
Well, apparently based on the info I got from a 1v1 guide from retail forums it should.
http://us.battle.net/wow/en/forum/topic/2089111000

"-Keep Lifeblooms on yourself while rooted. The Mage will either Spellsteal and waste tons of mana healing you, or they'll try to power through your LBs. The first reaction is the best, but the second also works"

This quote can be found in the first few lines of the tips against mages.

 It is possible that the info is outdated since that guide was for 4.0.6. and i don't know if it's any different for 4.3.4 .
In any case, do you have any proof of spellstolen lifeblooms not proccing the instant heal? Maybe a patch note or something? IIRC it used to work that way, at least on my old server, which also used 4.3.4 mechanics.

**Comment by phifedawg** [comment] 2015-12-14 10:35
Also I just found some info on wowwiki. Dunno if it's that reliable though.

http://wowwiki.wikia.com/wiki/Spellsteal

"Spellsteal uses the dispel mechanic and is affected by dispel resistance. There is no known pattern to which buff Spellsteal will target. It attempts to steal a random buff every time. If a buff can be stolen, it will have a yellow border. Otherwise, you will get an error message after attempting to steal it."

**Comment by gurin** [comment] 2015-12-14 10:38
http://us.battle.net/wow/en/forum/topic/4138438238 for example

**Comment by Jenovas** [comment] 2015-12-14 10:53
https://www.youtube.com/watch?v=UnGImLYzujY
Here we have a video from retail showing that spellstealing a lifebloom heals the feral Druid.
So spellsteal should bloom lifebloom on the Druid.

**Comment by gurin** [comment] 2015-12-14 11:06
So, Maybe this 4xGlad from AJ has no idea what he's talking about.

**Comment by phifedawg** [comment] 2015-12-14 12:10
Can you tell at which minute that happens for the sake of everyone following this discussion?

**Comment by blinkmaster** [comment] 2015-12-14 14:18
http://www.mmo-champion.com/threads/633912-Spellsteal
"Spellsteal on Lifebloom will not cause it to bloom and heal the druid. And Sacrifice for warlocks, PW:S, Hand of Freedom, Blessing of Protection, Innervate and Earth Shield are all worth stealing."

this is not a bug. spellsteal is labeled as dispel due to fact its mechanic resemble dispel ( when they are not ). 
cartoonz played on retail. he wouldnt hit more than 1,6k on at anyway with such gameplay

**Comment by phifedawg** [comment] 2015-12-14 14:54
It sounds reasonable, still i don't understand why a retail forum guide would point out using lifebloom as a strategy against mages if it wasn't true (again it is also possible, that that information is outdated for 4.3 and true for 4.0.6). Also that's the way i know it from my old server, but then again they might have done it wrong. [In case you need a reference the server i'm talking about is Frostmourne, which pretty much had fixes on a regular basis after it joined with Wowreach, Paramourne and AT] Can anyone give a definite answer?

**Comment by blinkmaster** [comment] 2015-12-14 15:26
well my guess is simple - mage cant kill resto druid with full cd and constant 3 lifebloom on himself by tunnel visioning him :)

**Comment by Jenovas** [comment] 2015-12-14 18:07
https://www.youtube.com/watch?v=UnGImLYzujY&feature=youtu.be&t=216
Here we see the druid with 66k HP after the Spell Stealing he has 76k so life blooms gave him around 10k HP. After the bloom on the mage we see that it healed him for 7k so the number would match.

**Comment by Jenovas** [comment] 2015-12-14 18:26
Also if you write mage vs feral 4.3.4. or mage vs balance 4.3.4 you can find some other videos where spellsteal does proc lifebloom heal.

**Comment by blinkmaster** [comment] 2015-12-14 18:40
i might be wrong but i think this comes from heal from leader of the pack :) 
anyway - i am perfectly fine if you fix it this way but as provided in statements above - i think this is not bugged.

**Comment by phifedawg** [comment] 2015-12-14 18:51
Now that you mention it, he does get a heal from 66k to 76 k.
For leader of the pack to heal him, he has to do melee dmg, in that example he was rooted so there was no way for the feral to do melee dmg. Still a definite answer would be great.

**Comment by blinkmaster** [comment] 2015-12-14 18:53
well melee range is about 5 yds so its possible in my opinion. also on combat text you can see FUNKY numbers probably meaning he critted which proves my point

**Comment by Jenovas** [comment] 2015-12-14 19:09
leader of the pack heals only if the druid crits, the druid wasnt in melee range + leader of the pack doesnt heal for 10k+ and it has a cooldown, and we see his HP jump up 2 times, so it wasnt LotP.

**Comment by Jenovas** [comment] 2015-12-14 21:58
Fixed in rev 4714

**Closed by Jenovas** 2015-12-14 21:58 UTC
Labels: Class - Druid
