### ISSUE TITLE
[en][spell queue] 

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#6716] opened 2016-03-05 20:47 UTC
spell queue not working at all correctly.

the problem at druid is when you get a proc of predatory swiftness and then immediately trying to clone someone, or try to switch forms from cat to bear and reversed /  other form, you'll feel that roughly 1 additional second.

happens when you spam immediately the buttons

**Comment by meowmewo** [comment] 2016-03-06 12:24
Confirmed. Something is amazingly wrong now, as a warlock after 6-7 casts i start to delay extremely on my casts.

**Comment by arranmc** [comment] 2016-03-06 13:53
Another confirmation, when casting spells after the 2nd cast, on the third there is huge latency which makes spell queuing REALLY hard

**Comment by Kaldros** [comment] 2016-03-06 14:02
After 1-3 casts I get a gigantic delay on the next one. I'm using Quartz as a cast bar and it shows that the delay is 800-1000ms which is huge. Sometimes it can happen on a few casts in a row. So I get something like:
1. Cast spell with no latency
2. Cast spell with no latency
3. Cast spell with 800ms latency
4. Cast spell with 1000ms latency
5. Cast spell with no latency
6. Cast instant spell with huge latency

And so on. It is a huge problem. This should definitely get marked as high priority.

**Comment by Bjarzyna** [comment] 2016-03-06 15:46
When i cast projectile spell (Haunt / shadowbolt / soul fire) followed by some instant spell (corruption / curse of agony) my character will not cast the second spell before projectile spell reaches it's target. If I cast another spell during the time projectile spell is flying it will be cast instantly but after global cooldown the second cast spell is cast (so if you cast haunt -> curse of agony -> corruption it will actually cast haunt -> corruption -> curse of agony).
It's very hard to cast properly right now. Yesterday I did not notice any issue like this.

**Comment by Kozakko** [comment] 2016-03-07 10:39
The same goes when it comes to Mage (fire). When we gain Hot Streak we can cast instant pyro with huge delay after previous spell. More over i have the same problem like Kaldros. It's started to happening after applying fixes 4918,4919,4920.

**Comment by Respect69** [comment] 2016-03-08 14:12
Same problem with warrior, it's impossible to keep my rotation, because of this delay. Maybe you should get rid of this spellqueue, fix it and then try again.

**Closed** 2016-05-19 12:06 UTC
Labels: Core Mechanic
