### ISSUE TITLE
[EN][Hunter] Focus regen with haste debuffs

### ISSUE THREAD

**Issue by serianx** [Atlantiss/BugTracker#2039] opened 2015-02-04 18:47 UTC
Focus regen in the prescence of haste debuffs is negative, for example 
http://www.wowhead.com/npc=43873/altairus  this boss gives you a debuff that decreases attack and casting speeds by 100%,  that makes you lose focus even if you are not doing anything. 
As far as i remember from retail, there is a base focus regeneration plus a positive scaling with haste
This also happens with other types of debuffs like the tornadoes from 
http://www.wowhead.com/npc=43878/grand-vizier-ertan#encounter

**Comment by Jenovas** [comment] 2015-02-04 18:56
Please show us some proof that negative haste doesnt reduce focus regen for hunters.

**Comment by Tj20** [comment] 2015-02-04 21:59
[Hunter focus regen in Cataclysm:](http://forums.elitistjerks.com/topic/109357-hunter-faq-cataclysm-edition-read-this-before-asking-questions/)

> Base hunter focus regen is 4 fps (focus per second). 1% haste increases your focus regeneration by 1%, so 10% haste for instance would increase your base regen to 4.4 fps. It looks like all attack speed buffs will also affect your focus regen in addition to your attack speed. The exception to this is improved steady shot as well as hunting party and equivalent buffs, which is currently bugged and will actually reduce your regen by 10% instead of increasing it.

[Downwind of Altairus](http://www.wowhead.com/spell=88286): *If the prevailing wind blows over Altairus before reaching the player, then the player has their attack and casting speeds decreased by 100% and movement speed decreased by 30%.*

I'm not sure how that is calculated. Does "AS / casting speed decreased by 100%" not mean that the player is unable to attack at all?

Be that is it may, [here](http://youtu.be/5nq0byheDnw?t=5m3s) is a video of a Cata hunter soloing Altairus. If you look at his focus regen when he has the debuff, it's something like this:

![pic](http://i.imgur.com/Q7QxdLg.jpg)
![pic](http://i.imgur.com/WGgizjv.jpg)

So with the debuff he regens 8 focus in 4 sec, if I'm not mistaken, or 2 focus per second. That is about half of what he would reg unter normal circumstances.

>  that makes you lose focus even if you are not doing anything

In the video, the debuff makes you regen slower, but you still regen focus. Losing focus should not be possible under any circumstances.

**Comment by kadi2** [comment] 2015-02-05 00:03
In this specific moment hunter doesn't have exactly -100% haste that would theoretically make him regain no focus, since he has additional haste from gear and Improved Steady Shot buff.

**Comment by Jenovas** [comment] 2015-02-05 09:58
From what I know you do not lose focus on the server there is a visual bug I think for every class that uses energy/focus that even with negative haste you still regen 10 energy per second but every second or two your energy/focus updates to the state it should be (making you think you just lost some focus/energy). I saw the same thing for energy with big amounts of haste, you can see your energy bar jumping up cause on the client side you still regen 10 energy per second and later it updates with the server and you get the energy that you should get from haste (and it looks like your getting free energy).

**Comment by serianx** [comment] 2015-02-06 00:03
tj20 thanks for the complete information i was lacking. 
Jenovas , that is not the case here, you actually lose focus each second.
You can try this in this Altairus fight and you will end up with 0 focus until the debuff wears off.
Seems that the formula calculating focus regen from haste does not take into account the minimal focus regen per second

**Comment by MikeViper** [comment] 2015-02-07 03:01
I can confirm this, at least energy sided. Energy regeneration should not be affected by attack speed modifiers (read plain attack speed modifiers like thunder clap, icy fever or frost armor, NOT haste). Otherwise slice and dice and lightning reflexes 9% melee speed talent would provide 40% and 9% respectively energy regeneration while active which is not the case. 
Attack speed debuffs affect DK runes and Hunter's focus regen, but energy it is not affected by it. Yes, it is stupid the way it is, I can't tell though if attack speed buffs affect their resource positively, like Hunting Party or Icy talons 10% increase attack speed.
Check google on battle net of 2011-2012 complains of DKs and Hunters complaining their resource is slowed down during certain boss encounters with such debuffs or in PvP.
Here some links to such complains: https://www.google.com/search?q=wow+attack+speed+debuff+resource+site:us.battle.net&biw=1429&bih=987&sa=X&ei=H37VVMG7BMf3avbVgtgI&ved=0CCgQrQIoBDAA&dpr=0.9

There are some mobs for easy GM testing (scarlet archmage http://www.wowhead.com/npc=9451/scarlet-archmage) in eastern plaguelands that have ice armor which reduces attack speed by 100% when hit, effectively making me on my rogue losing ~1 energy per sec as the regen formula goes negative. This is not visual bug, abilities are locked and cannot be used. 

As a conclusion; regeneration rate of runes and focus should be affected by attack slowing debuffs negatively (but not losing focus instead of gaining, it should be capped at 100%, meaning no resource generating until debuff wears off), but not energy. It is dumb yes, but it's how blizzard made it. :/

**Comment by MikeViper** [comment] 2015-02-07 04:30
I can confirm this and can also provide more info;

First, attack speed debuffs or buffs should NOT affect Rune, Focus and Energy regeneration in either way. In a patch around 4.0.6 there was a bug on retail where those attack speed modifiers were affecting Runes and Focus positive or negative, Blizzard eventually fixed it from the mass of bug reports.

Attack speed =/= haste. Buffs like slice and dice do not provide haste, otherwise it would provide 40% energy regeneration while active. Any attack speed modifying debuff like Frost Armor, Earth shock, Infected wounds, Thunder Clap, Frost Fever and all other similars from PVE should NOT affect a resource regeneration time, as they do not reduce your haste, they only reduce attack speed that has no relevance to resource regeneration.

Bloodlust like buffs or debuff affect resource gained formula, since it's a haste haste related mechanism. Some debuffs like Downwind of Altairus are made to affect haste despite saying attack speed, as it seen in the video reducing focus gain. Those kind of buffs and debuff should affect Focus, Rune or Energy regeneration, the modifiers that affect HASTE not attack speed.

To make a conclusion of the current bug report here:
- Focus, Energy and Rune regeneration should not be affected by attack speed slowing debuffs from the game's attack speed debuffs. (Frost armor, Frost Fever, Thunder Clap, Infected Wounds, Earth Shock, Judgement of the Wise and the like). The same way goes for the buffs. (slice and dice or icy talons etc.) Which the buffs work correctly on Atlantis, they do not provide resource regeneration increase, however debuffs do provide slower regeneration.

- Focus and Energy should not in any circumstances be able to go negative in amount, as in losing instead of gaining them as it can happen here on Atlantis.

**Comment by Andelen** [comment] 2015-11-03 00:24
I know this is off label, but energy regen bugs the same way on that boss. My rogue won't lose energy though, but his energy regen goes to 0, so he can't use any skill. Basic energy regen is 10 per second, losing 100% haste should never lower energy regen to 0. 

It also happens with other attack speed debuff.

**Comment by Shirofune** [comment] 2015-11-16 16:29
Confirmed. This is still bugged and a mayor annoyance for any energy/focus class.

**Comment by Wolffenstein** [comment] 2015-12-11 02:06
Fixed in rev 4701.

**Closed by Wolffenstein** 2015-12-11 02:06 UTC
Labels: Class - Hunter
