### ISSUE TITLE
Worgen Quest Exodus 

### ISSUE THREAD

**Issue by Chariska** [Atlantiss/BugTracker#4062] opened 2015-08-03 19:16 UTC
Its not possible to end this Quest as a Worgen cause the NSC is not there.

**Comment by Pallitax** [comment] 2015-08-03 19:46
Duplicate of #2501 and

• Title doesn't follow the guidelines
• No wowhead link for the quest or the NPC provided

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Closed** 2015-08-04 13:10 UTC
