### ISSUE TITLE
[EN][Spell][Warrior]Blood Frenzy   id 30070 - very annoying

### ISSUE THREAD

**Issue by kohahahu** [Atlantiss/BugTracker#9324] opened 2017-07-07 08:21 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Increase physical damage taken by 4%

**Current behaviour**: debuff stay after bg, debuff stay after relog

**Expected behaviour**: Blood Frenzy debuff (http://cata.openwow.com/spell=29859) should be present on the target whenever there's either Rend (http://cata.openwow.com/spell=772) or Deep Wounds (http://cata.openwow.com/spell=12867) debuff present on the target, or both at the same time.
Blood Frenzy should not have a duration.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: 5451

**Comment by Celiez** [comment] 2017-08-04 19:13
in b4 they delete this after 1 year of no fix again

**Comment by lamaATS** [comment] 2017-09-06 01:46
Anyone can give proper `Steps to reproduce the problem` because I'm unable to reproduce.
I was trying with relog.

**Comment by lamaATS** [comment] 2017-09-07 15:24
Fixed in rev. 5491

**Closed** 2017-09-07 15:29 UTC
Labels: Spell, Warrior
