### ISSUE TITLE
[en][item][spell][priest] Dragonwrath legendary staff and  [Atonement]

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#8980] opened 2017-03-03 19:12 UTC
**Description**: the copied smite and holyfire  should work as if the priest casted them, so priests talents should work on  it, soooo it should also heal 

http://wow.gamepedia.com/Dragonwrath,_Tarecgosa%27s_Rest
"Duplicated spells behave as if you did cast them. They are subject to the same talents, buffs, debuffs and other conditions."

smite http://cata.openwow.com/spell=585
holy fire http://cata.openwow.com/spell=14914
Atonement spell http://cata.openwow.com/spell=94472
Atonement talent http://cata.openwow.com/spell=81751

**Current behaviour**: the copied smite and holyfire does not  heal

**Expected behaviour**: copied spel shoudld also heal

**Steps to reproduce the problem**:

1.  go spam smite or holyfire with a warlock  ( tell him to lifetap so he has bellow 50%hp)
2. count the smites or holyfires, compare to the amount of attounments

**Revision**: rev. 5319

**Comment by Spust** [comment] 2017-03-04 08:44
No, it should not proc heal.

**Comment by Batranelu** [comment] 2017-03-04 12:35
Yes it should cause staff spell benefit from talents too.

**Comment by Spust** [comment] 2017-03-04 12:50
"I have Dragonwrath and an AA/A offspec and it does proc another smite but does not duplicate the heal as the above poster has also said."

**Comment by Illusie** [comment] 2017-03-04 18:45
If It should benefit from talents, It should work with Telluric Currents aswell.
Some shaman can check out?

**Comment by Trollpowah** [comment] 2017-03-04 20:13
According to Wowhead: http://www.wowhead.com/item=71086/dragonwrath-tarecgosas-rest#comments and MMO-Champion forums: http://www.mmo-champion.com/threads/922716-Dragonwrath-Tarecgosa-s-Rest-*Possibly-Useful-For-Disc-Priests*/page2 spells copied from DTR neither heal for priests, and don't regen additional mana for Shamans (confirmed by our Shaman with staff, copied bolts didn't regen MP).

**Comment by Aival94** [comment] 2017-03-05 00:05
Yeah. I can confirm as well. Tarecgosa staff does not benefit from Talents and it should not. And like they said only Damaging spells should be copied and not healing spells or effects.

**Comment by Illusie** [comment] 2017-03-05 00:55
@Aival94 we know Staff duplicating the harmful spell, Smite & Lightbolt are harmful spells.
the question was if the duplicated Smite & Lightbolt are also benefit from Talents,

Because Pyroblast proc from staff benefit from Ignite.
And Wrath / Starfire benefit Eclipse system.

Just saying.

**Comment by Suricat-chicken** [comment] 2017-03-13 10:24
Yeah, Smite / Holy Fire are harmful spells and as above Illusie stated >> The staff benefit from talents for mages and druids so why it shall not proc for priests? Curious.

**Comment by Spust** [comment] 2017-03-13 11:01
Because this staff is for damage class, not healers.

**Comment by Suricat-chicken** [comment] 2017-03-13 11:04
Okkay guys sorry for bothering you.... Just found out that the staff will not proc double heals, cause the staff procs as duplicate of your damage dealin arcane dmg from the copy of the spell. 

Still we have Devouring Plague which can give us small heals, and doesn't matter it is BiS even for healers. Compare it to hc Kogun stats.

**Comment by stanq87** [comment] 2017-03-13 14:06
thats wrong,  because the part thats dealt as arcane damage are dot tics that are copied not direct dmg spells
"If the staff duplicates a DoT-tick, the exact amount of damage is dealt by the spell 'Wrath of Tarecgosa' as arcane damage. This spell will not hit critically.", so the coppied harmfull holy spel is still a holy spell,

**Comment by Aival94** [comment] 2017-03-13 15:08
I think that the staff is only duplicating Harful spells and their effects. It should not duplicate any kind of healing effect. The legendary staff was mentioned even by blizzard that is not for any Healing spec and only DPS-casters benefit from it. About talents should benefit from them as far as they do not have a healing effect. This is in the description of the item and this is what most say. 
If anyone really want to check it even more only way is to go to retail and test it.

**Comment by Illusie** [comment] 2017-03-13 16:28
@Spust 
You right if he was casting Heal, Flash heal, Greater heal and rest of the heals.
The staff does not duplicate heals, HoTs etc.

But I spoke about difference things, Let me just shapern my opinion.

We need to ask three questions:

1. what Tarecgosa staff duplicate. Spell/Ability or only the damage?
2. Smite and Lightbolt are HARMFUL spells or not?
3. Tarecgosa work with Talents and Mechanics (like Ignite)(like Eclipse)?

According to my knowledge and only to my knowledge till someone will disprove me.

1. The staff duplicate the SPELL/Ability not the damage.
2. Smite and Lightbolt are harmful spells.
3. Tarecgosa work with Talents and Mechanics.

Atomenent/Lightbolt answer on all those questions conclusively.

-Atomenent/Lightbolt are Harmful spells.
-Tarecgosa duplicate the spells not the damage
-Tarecgosa work with Talents and Mechanics


Now:
when ever Disc Priest Smite and get another Smite from staff its counted like he Smite TWICE.

So BOTH (one he casted and one he recieved from staff) should benefit from the Atomenent talent like Ignite and Eclipse system benefit from the Tarecgosa duplicated spells.

[Atonement](http://cata-shoot.tauri.hu/?spell=81749):"(Do) equal to 100% of the damage **dealt**".

Now same about Lightbolt and Telluric Currents with Resto shaman
"Restore mana equal to 40% of damage **dealt**"

And same with Elemental Shaman and Rolling Thunder:"When you **deal** damage with Lightning Bolt or Chain Lightning while your Lightning Shield ability is active, you have a 60% chance to recover 2% of your mana

P.S
I'm really sorry I could not find a proper reliable source.
It's just me and my "thoughts", "Logic" call it how you want.

**Comment by Illusie** [comment] 2017-03-15 17:41
Ok, I made a experiments because my researchs for Tarecgosa staff work Resto/Disc priests was unsuccessful to shed light. Every topic I read gave really shitty unreliable source & Information.

But I want to clarify more things about Staff.
to strengthen my claim about: "If staff should work for Disc Priest and Resto Shamans talents".

1. I knew Tarecgosa staff duplicate SPELLS like Fireball, Pyroblast.
2. I also knew the duplicated spells helping my Ignite(talent) go bigger.
3. I knew the duplicated proc from staff also work with Mechanics like Eclipse for Balance druid.
so the duplicated proc from staff counts/considered as you casted it and **inherit** with EVERYTHING.

My conclusion
Talents: Ignite, Atomenent, Telluric Currents = Should work ALL the same with staff.

Indirectly proportional the staff does heals and help Resto shaman gather more mana.

I'll explain:
Smite duplicated proc should work with Atomenent because it considered as YOU casted it.
And If it considered as you casted it and it DEALS damage it should also heal.
Because that how Atomenent work, damage=heal.

So I read things about "Arcane damage" that Trollapowah mentioned above.
But Stanq87 corrected him that the Arcane damage appear only from DoTs.
And duplicating the damage of DoT itself only (ex: Combustion 51k -> WoT 51k)

DoTs like Devouring Plague & Pain should apply WoT.

Lightbolt proc out of staff should work with Rolling Thunder (Ele spec) and Telluric Current (Resto spec)
Tarecgosa should proc out of proc (like pyroblast procced out of my Hot Steak) and should proc out of Overload. (Didn't tested if it work as It intend in Atlantiss)

Casted 50 Ice lances (Direct ability) had 3 procs from staff.
btw The Ice lance proc from staff also benefits from Shatter for Frost spec
Another good example that the Proc from staff work with Talents, Abilities and Mechanics.
http://i.imgur.com/H191HaC.png

WoT appeared only from DoTs.
http://i.imgur.com/Rweplqi.png

Proc out of Proc proof:
http://www.dailymotion.com/video/x5ewaxt

I now many will say it will make those healers OP'er than other Heal classes.
I want to clear more something.. Because the low proc chance (13.6% for Priest & 17% for Shaman) I am surely can say that Tarecgosa staff won't really make Disc Priest & Shaman OP'er because its too RNG to relay yourself on it. besides, Disc are already OP :D 

You welcome disclaim me if you have good proof, not those shitty gaven by mmo-champion.
Till than I really hope ATS will make the Tarecs proc aka duplicated spell to work with Talents mentioned above.

HF Day.

**Comment by Spust** [comment] 2017-03-15 18:08
It's logical, but you can find the information that the staff did not work with the atonement on the Blizzard servers, so I see no reason to "fixing" this on Atlantiss.

https://us.battle.net/forums/en/wow/topic/3967596897

**Comment by Illusie** [comment] 2017-03-15 19:54
Ofc it should.
If it proc another clone Smite it should inherit everything include Talents.

Like Fireball & Pyroblast with Ignite
Like Wrath/Starfire cloned give points to Eclipse system for Balance Druid.

The duplicated spell considered like If you casted it yourself.
and according to ""Duplicated spells behave as if you did cast them. They are subject to the same **talents**, buffs, debuffs and other conditions."

Here is proof from myself casting Ice lances (direct spell) I casted 50 times and got 3 from staff.
The ice lances also work with Shatter (Talent Frost spec)
http://i.imgur.com/H191HaC.png

It should work with Atomenent because its TALENT.
not direct-heal Its not like Flash heal.

We know Staff does not duplicate heals. but obviously work with Talents.

I really don't want to copy-paste everything I wrote earlier and had to remove.
Because its not worthy when the Opener explained it pretty well.


- Tested with Shaman Restoration with Telluric Currents Talents and Lightbolt.
Tarecgosta lightbolt proc does not giving mana. It should give.


About Telluric Currents - I tested it on Atlantiss with my Shaman

**Comment by Spust** [comment] 2017-03-15 20:06
> Ofc it should.
No, it should not.

**Comment by Illusie** [comment] 2017-03-15 20:19
It should because its TALENT.
the staff does not work with DIRECT-HEALS like Greather Heal, Flash Heal, Heal

Atomenent is **talent** that HEALS equal to the DAMAGE of Smite.
its very simple

selfcast Smite>Xdamage=Xheal
procced Smite>Xdamage=Xheal

I did experiments of my own because you confused us with what you said on your previous messages.
And I really wanted to prevent myself to write 50000 letters here. But you give me no choice.
I read alot of Topics from EJ to mmo-champion and Blizzard none gives a reliable source if the staff should work with Atomenent and Telluric Currents even the Link you and Trollpowah gave are unliable and disproved by OT.

Now lets talk more about staff mechanic.
the staff work with Eclipse - Confrimed.
the staff work with Talents - Confirmed.
the staff even Proc out of Proc - [Confirmed](http://www.dailymotion.com/video/x5ewaxt)

So staff not working with Atomenent & Telluric Currents are just BUGs.
proof - http://i.imgur.com/I1smH3Q.png
proof - http://i.imgur.com/mLlrZ8E.png

**Comment by Aival94** [comment] 2017-03-15 21:15
Unfortunatelly the Logs he linked here: http://www.mmo-champion.com/threads/1041653-attonement-and-the-legendary-staff someone are not longer but rest clearly state(even the one who thought he got 2 heals instead of one) that it does not proc any heals even from Talents.

**Comment by Illusie** [comment] 2017-03-15 21:24
And one dude before thought the Smite should proc Arcane damage when we know the Arcane damage is not come from direct-spell but DoTs. he also got corrected by "Shedi".

Other dude named "Ravyna" said: "copied smite does heal as smite specced Disc."
than "Vorend" said: "in my logs i see double smites but no double atonements"

What the point linking mmo-champion link(s) when the everyone say different opinions.
we can't understand anything from it and and ye the Logs link is broken. sadly still no confirmation it shouldn't.

**Comment by Aival94** [comment] 2017-03-15 21:27
check again as same guy named "Ravyna" said 
"dont have logs but i sometimes smiteheal 5 manns and i got the legendary and parrot(scrolling combat text addon) always shows a double heal when i get a smite procc (and the tank actually gets more life than he would from a single smite)

---------- Post added 2011-12-12 at 10:24 PM ----------

hm just tested it on a dummy it seem to not work there but im quite sure i got that double heal in the 5 mann ->confused

---------- Post added 2011-12-12 at 10:27 PM ----------

two options it´s bugged in 5 manns or more likely i just messed up and wanted to believe it double heals
have to test in a 5 mann sometime"

So please at least check the hall post..

**Comment by Illusie** [comment] 2017-03-15 21:28
Avial94
I read what everyone said in the link you shared with us.
It's still not a clear-cut proof.

According to the FACT the staff proc work with Talent I still stick to my argument that It should work for Atonement and Telluric Currents.

If the Logs link was not broken we probably could find it out :/ sad.

**Comment by Aival94** [comment] 2017-03-15 21:32
No. According to the facts should never heal anyway. The staff as even stated by blizzard is only dps-spec gear and only harful effects are cloned. If you still really want to have a disc priest with double heals then go on blizzard and test it and as far as we see such proofs i am totally with you to see that in atlantiss as well. But for now it should not.

**Comment by Illusie** [comment] 2017-03-15 21:34
Atonement is not a direct-heal its Talent.
why people cannot read?

its not only "dps-spec" because the staff already proc Smite and Lightbolt even in Heal-spec.
the question is simple if it should work with Talent such Atonement and Telluric Currents like it work with Ignite or not.

**Comment by Spust** [comment] 2017-03-15 21:40
It's like talking to a wall.

**Comment by Illusie** [comment] 2017-03-15 21:43
Better talk to wall than talk to stone.
I told you here facts talk and you don't give facts but I do.

If you want I don't mind to repeat myself over again.

Atonement = Talent
Staff work with Talents
Smite is Harmful spell
Smite is already duplicated by staff.
the Duplicated should inherit with Everything include talent.

It mean the duplicated smite should heal

have fun.

**Comment by Aival94** [comment] 2017-03-15 21:50
Then you should show PROOFS and not just your own Logical thinking(i could understand that but yeah we give you links and in-direct proofs but it seems you ignore them by reading half of them and telling are not good enough for you). As far as no real proof are here the states go mostly to no direct or in-direct heal from legendary staff.

**Comment by Illusie** [comment] 2017-03-15 21:52
@Aival94 the proof is already been given in OT wowpedia link.
I just strengthen his claim with facts that already happen in ATS.

I read alot things on mmo-champion most of them are bullshit and not official sources.
we cannot take them serious ofcourse.

**Comment by Aival94** [comment] 2017-03-15 21:55
the comments they gave are from 4.1. I gave at least one from wowhead that was from 4.3 which means the 4.1(the staff was still on PTR) are less trustfull from the 4.3(where the staff was out for some months already).

**Comment by Illusie** [comment] 2017-03-15 22:13
Well I'm trying to be positive...
I still think they should put it work with Atonement and Telluric Currencts talents.

In the best case scenario we helped Disc and Resto to be a little bit more useful and stronger.
The game is anyway imbalanced and some specs are just better than other.

At worst scenario we did mistake and it shouldn't work with those Talents.
Not too hard to fix.. It's better to put it on, than not. we are doing injustice.

Yet I must repeat myself, All this discussion went theoritical, if someone will give decent evidence to how it should work I'll just remove my messages and will accept it.

**Comment by Spust** [comment] 2017-03-15 22:24
> It procs another Smite but not another Atonement heal.

> I have Dragonwrath and an AA/A offspec and it does proc another smite but does not duplicate the heal as the above poster has also said.

> Doubles damage, but not Atonement healing.

> It actually clones the spell and should proc Atonement, but I'm pretty sure they prevented it to make sure it went to DPS.

> This was tested WAY back with 1 of the early ones made - it does duplicate the Smite and Holy Fire, but does not proc the Atonement effects. 

> In my logs I see double-smites but not the associated double atonements from them.

> I'm 100% sure that the staff copies the damage but does not trigger atonement. 

eot

**Comment by Illusie** [comment] 2017-03-15 22:28
Well I'm trying to be positive...
I still think they should put it work with Atonement and Telluric Currencts talents.
The OT gave pretty decent proofs and I admit, I convinced it should work with those Talents.
Like the staff does with any other Talent or Mechanic (ex: Eclipse)

In the best case scenario we helped Disc and Resto to be a little bit more useful and stronger.
The game is anyway imbalanced and some specs are just better than other. if we talk DPS or if we talk HPS. 
I'm not willing to do those specs stronger for god knows what reason. You can't blame me for unkown cause why I'm defending it.

At worst scenario we did mistake and it shouldn't work with those Talents.
Not too hard to fix.. It's better to put it on, than not. we are doing injustice.

Yet I must repeat myself, All this discussion went theoritical, if someone will give decent evidence to how it should work I'll just remove my messages and will accept it.


Anyway I'll put my messages up till tomorrow than I'll delete them.
TBH I don't really care :)

**Comment by Jenovas** [comment] 2017-03-16 01:12
No proof, no fix.

**Closed by Jenovas** 2017-03-16 01:12 UTC

**Comment by Illusie** [comment] 2017-03-16 11:22
Well I deleted all my messages because there no point to keep them up, BugTracker is not Forum we don't discuss here. I'll just leave this message and that all.

I read every single link I could find in the internet that giving information about Smite.
I did not found clear-cut proof that Smite proc from staff will work with Talent (Atonement).
Most of the topics says the Smite-proc doesn't do extra heal from Talent. but in same breath they say the damage is Arcane which just untrue and easily disproved.

I found mmo-champion is not reliable source to lay on to as proofs.
[Here ](http://www.mmo-champion.com/threads/938495-Disc-priest-Legendary-staff) is exampe why wowpedia is more decent source than mmo-champion.

ZyloCG: "As for giving the staff to a disc priest. My understanding, is that the smites damage would be duplicated, but the heal which is procced through atonement would not be. The damage replicated by the staff will be equal damage to that of the smite which it is procced from, however the proc comes in **the form of another spell which deals arcane damage**, and thus, no atonement."

According to him, the duplicated Smite will deal damage as Arcane.
which we already know its impossible because the Arcane damage (WoT) applying only from DoTs.
Also according to [this ](http://i.imgur.com/mLlrZ8E.png) screenshot I took from ATS the damage duplicated is not Arcane but exactly a clone of the Smite.
This is one proof from many that mmo-champion is damn unreliable official source to lay on.

Another example why you can't lay on Blizzard forums is [this](https://us.battle.net/forums/en/wow/topic/3278899057) another dude say the damage duplicated is Arcane, which is untrue.

I also tried and looked for if Staff work with Telluric Currents (Talent)
according to [this ](https://eu.battle.net/forums/en/wow/topic/2123513091) link from Blizzard forums.

Lezrokk: "Like all the other legendaries, aye? I really, really doubt it will be a fast process in any way. I can't see this going to a resto very fast, **since the proc is just not worth the extra 3-4 k mana on a resto shaman** when it could be a 120k (pulling that number out of my hat) .."

He saying that the proc (from Staff) not worth the 3-4k mana back from Lightbolt(Telluric Currents, talent)
According to this quote I assume that the staff DOES work with Telluric Currents but in his opinion not worthy.
in ATS the lightbolt from staff proc but you don't get extra mana > [proof](http://i.imgur.com/I1smH3Q.png)

Still I can't take those people seriously because I doubt their knowledge.

Since It's really hard to find a clearcut proof to any side working or not working.
I stick with with what OT & wowpedia and my experiments I did in ATS and the Logic.

The staff work with Talents(e.g Ignite) and the duplicated inherit and work with everything include Mechanics (e.g Eclipse).

-Atonement is talent not heal. Smite is already proc out of staff with Priest specced Disc (proved)
-Atonement and Telluric Currents are Talents.
-Atonement is mechanic that heal equal to the damage (not direct heal but indirect).

This is my last message. I truely don't care so much, its not a gamebreaker.
The proc is anyway 13% and if Priest will lay his playstyle on RNG proc he is stupid.

Have nice day or night.

**Comment by Illusie** [comment] 2017-03-19 16:02
https://images.weserv.nl/?url=www.interload.co.il%2Fupload%2F8277083.jpg
https://images.weserv.nl/?url=www.interload.co.il%2Fupload%2F394610.jpg

I hope its enough evidence.

**Comment by stanq87** [comment] 2017-03-21 17:20
that chat dosent tell us anything, wee need a disco smiter on retail with the staf  to test it and gives us some real proof

**Comment by Illusie** [comment] 2017-03-22 22:51
@stanq87 its impossible.
because the Retail is now on Legion and talents, things has changed.

Even if you'll find a Priest with Tarecgosa staff.
I don't think they have Atonement talent or Smite anymore.

I asked few people that play or played Retail at cataclysm, and they said it worked back then.
People from decent guilds that doing Mythic raids.

So or you lay on that people to say the truth (I dont see reason why they wont) or you lay on forums like mmo-champions.

I don't mind to do re-checks again with friends playing Retail.

Maybe you suspect that if 1 person say it is not enough.
Ill try to bring more 2-3 people to strengthen it.

**Comment by stanq87** [comment] 2017-03-22 23:00
u dont have to convince me, however we need  hard evidance of it working  the way we think it should on retail,  so the gm would cave in and enable it on atlantis soo, bring a shit load  of testimonies but still some screen or a movie from  a smiter would be better

**Comment by stanq87** [comment] 2017-03-23 15:35
OK guys, so IF smite does not heal because the staff wassent intented to duplicate healing efects from damage spels why do why a copied holy nova heals ? [Holy Nova](http://wow.gamepedia.com/Holy_Nova)
