### ISSUE TITLE
[EN][Item] Variable Pulse Lightning Capacitor HC

### ISSUE THREAD

**Issue by Aldergar** [Atlantiss/BugTracker#8623] opened 2016-11-28 22:48 UTC
**Description**: Trinket does the same damage as the normal trinket http://www.wowhead.com/item=69110/variable-pulse-lightning-capacitor

**Current behaviour**: It doesn't matter if you use Normal or HC trinket,output damage is the same

**Expected behaviour**: Trinket should deal WAY more damage 

**Steps to reproduce the problem**:

1. Kill Ragnaros HC
2. Take the Trinket HC
3. Equip it and cry

**Revision**: 5263

**Comment by kadi2** [comment] 2016-11-29 08:53
Can you check if it doesn't proc from non-crit spell hits aswell?

**Comment by Aldergar** [comment] 2016-11-29 10:55
My friend tried with full crit gear and without crit,the result is the same,the trinket does the same damage,I will get a screenshot from him when I can.

**Comment by therealpadthai** [comment] 2016-11-29 14:47
There's more to it than this. Do more testing. There's a few interesting things happening to both normal and hc versions of the trinket and I'll update accordingly with my findings once I have a couple days off work to run sims and compare logs.

**Comment by PolpoVolante** [comment] 2016-11-29 15:29
Hi so far i've tested with same gear both normal and hc trinkets,
Normal:
1 stack 6.7k
2 stack 10k
3 stack 13500
When crit it does 2x the damage
The hc version is the same so I think the scaling is ok but the base damage per stack isnt it should do +-2k more per stack.

Also to add more bugs on this trinket:
If you have dots on a target or multiple targets and you change target if the dots crit the lightning bolt targets your actual target even if it has no debuffs and so the crit cannot occur.   It works properly if you have no one in target and have dots on multiple targets.

Also i think it doesnt proc even if you crit if the target is too far away (need testing tho not too sure)

ALSO with the legendary staff if i get a proc on the trinket with for example 3 stacks and it gets duplicated it does WAY LESS DAMAGE, as with above numbers 3 stacks do 13.5k it should proc another 13.5k since it has fixed damage but it does like 1.5k, since this number is so little i think it only does the damage of 1 stack without any intellect/sp buff from the caster.

**Comment by Jamishman** [comment] 2016-11-29 20:17
Heroic procs off non-crits, nice report, nerf inc XD

**Comment by blinkmaster** [comment] 2016-11-29 20:27
XD

**Comment by Fearyourself** [comment] 2016-11-29 20:29
Lmao :P

**Comment by therealpadthai** [comment] 2016-11-30 01:00
So I've done a little digging and found a few interesting things.

In this issue (https://github.com/Atlantiss/BugTracker/issues/5552), we see that the trinket was not buffed with the damage portion of the stealth patch Blizz introduced (Hotfix (2011-09-08): "The Variable Pulse Lightning Capacitor now does an average of 2.6x more damage than before, but is less likely to reach a large stack of charges.") (source: http://wow.gamepedia.com/Variable_Pulse_Lightning_Capacitor)

And in this revision, we see how the normal version was indeed buffed with the damage buff blizz introduced, among other things. (source: http://atlantiss.eu/changelog/25#rev4764)

Now, through my tests, I have confirmed that the heroic trinket does pretty much the same damage to the normal trinket. I tested my character naked, with just the trinket equipped, with no buffs or talents.

A) non-eclipse: 1 stack at approximately 3366 w/ normal version. Again, naked, nothing else equipped, with just the trinket, and unspecced in any tree. Keep in mind that in revision 4764, the tooltip damage was buffed by 300%. Not sure why it was 300%, as in the Wowpedia article (direct source: https://worldofwarcraft.com/en-us/news/3019413) it stated Blizz only buffed it by an average of 260%. Not that I'll be complaining, though ;P
B) non-eclipse: 1 stack at approximately 3374 w/ heroic version. Again, naked, nothing else equipped, with just the trinket, and unspecced in any tree. Keep in mind that the tooltip of this trinket states 3301 as the damage the trinket should be inflicting. If we increase that by approximately 300%, as in revision 4764, 1 stack should be dealing roughly 10,122 damage. Not sure why it was 300%, as in the Wowpedia article it stated Blizz (direct source: https://worldofwarcraft.com/en-us/news/3019413) only buffed it by an average of 260%. Not that I'll be complaining, though ;P
C) in solar eclipse, no form, naked: 1 stack at pproximately 4.95k w/ heroic version, confirming that it still is increased by nature damage effects, or at least the intended effect from being in a solar eclipse. 56% of 3374 (current eclipse bonus naked) roughly equals out to 5.2k-5.3k. Keep in mind in order to reach my eclipse I need to be in balance spec, giving me an automatic increase to nature damage through talents, making the 5.2k-5.3k roughly 57-58% instead (balance of power gives 2% increased nature dmg). Pretty much spot on here.
D) It seems as though the heroic version of the trinket is indeed gaining charges from non-crits. I was naked while testing and had literally no issues whatsoever getting procs on the heroic version, given my 7% crit chance and the fact it never crit :p However, the normal version did not proc as fast at all and only seemed to proc off crits.

Given this info and the info from previous posts in this tracker link as well as the previous tracker links already solved on Atlantiss about VPLC, I have two conclusions.
1) I have a hunch that perhaps the heroic version of the trinket has not been buffed with the correct damage increase as seen in the Blizz silent patch. I mean, we've already seen how Apparatus HC was bugged as well during the release of FL HC. It's normal for trinkets compared to their heroic counterparts to go through bugs like this on a private server.
2) The trinket should indeed NOT be gaining charges on non-critical strikes.

That being said, I could be completely wrong here, this is just something I can only assume, given the history of the fix to the trinket, rudimentary math checking out (haven't sim'd anything yet, have just tested on dummies), and the fact that other HC trinkets, such as Apparatus also required fixes to the HC version. 

I hope I can point the devs in the proper direction into looking why it's doing less damage as intended.

**Comment by PolpoVolante** [comment] 2016-11-30 07:52
@therealpadthai 
Thank you for testing I should have tested like you without gear I didnt notice that it proc off non crit as fire mage.

I hope it gets fixed as soon as possible, I'm getting sick of all fire mage bugs and now this after using 70% of my dkp for it.

**Comment by therealpadthai** [comment] 2016-11-30 15:45
@PolpoVolante 
No problem, as I said if we need further testing I'm willing to sim and then compare using worldoflogs of others with the trinket and such, but I really think it's just a matter of the trinket not having the 2.6x base dmg increase. Found some further curious things as well.

To recap, in revision #4764 (http://atlantiss.eu/changelog/25#rev4764), A) the base dmg was increased as per Blizz's patch (although it should have been x2.6, **not** x3.0 :p), B) the max charge was set to 5, and C) the ICD of the trinket was set to the proper ICD of 2.5sec.

A) As per my wall of text in my post above, we can clearly see that something wonky is happening with the heroic trinket and some conclusions have drawn me to the belief that the base dmg multiplier has not been added to the heroic version of the trinket.
B) I haven't been able to see any charges go longer than 5, but then again, the heroic trinket is procing from NON-CRITS, meaning I am legit machine gunning these lightning bolts because I'm procing the charges and the bolts so fast and I can only imagine how fast fire mages are throwing them out. I am still unsure if this change has not been applied to the heroic trinket as well. It's almost as if the crit bug would have to be fixed before testing this aspect can happen. That being said, I haven't seen any charges go past 5.
C) After some testing, I found the ICD of the trinket _suspiciously_ close to the 2.5sec ICD. Often times, it would seem as though the 2nd charge would be gathered at around 2 seconds of the 1st charge accumulating. Again, I am still unsure if this change has been applied to the heroic trinket as well. I am still looking for a proper timer addon to test this aspect, maybe someone else can do the due diligence and test this as well?

Anyways, if some other people would like to test the three aspects of this change that would be great, especially the ICD. Multiple perspectives are always much better than one.

**Comment by kadi2** [comment] 2016-11-30 21:15
Related to Normal version of the trinket report. https://github.com/Atlantiss/BugTracker/issues/6974

**Comment by PolpoVolante** [comment] 2016-12-01 14:12
So I did a bit of testing with simcraft. The results are strange.

http://imgur.com/a/mdwJ0
all tests are with 0 gear 0 buff and 0 debuffs on 10000 iteractions on a level 85 dummy patchwerk style.

SO according to my tests on Atlantiss this trinket does 3x times the base damage but has no scaling, also looking ad these tests damn that trinket does heavy damage.
If you are nude with no gear on Atlantiss 1 stack does 6.7k while with my 388 gear it remains the same.

What do you guys think?

**Comment by therealpadthai** [comment] 2016-12-01 14:24
One stack does 6.7k? lol what? You mean 3.35k, right?

I think the SP scaling is a bit off, I noticed some weird results when I had my full gear on as well.

**Comment by PolpoVolante** [comment] 2016-12-01 14:28
http://imgur.com/a/i5zhD 

Try it yourself this is my base damage and its wayy too strange.

**Comment by therealpadthai** [comment] 2016-12-01 14:45
I never proc a capacitor at 1 charge, it's always at 2 or more. I check my rolling combat log and it shows me how many procs I have and when I lose them, then the bolt hits. So, I've just been deducing that if 2 charges = 7k, then one single charge must be 3.5k. P.S. this is in my balance spec so I have the nature+dmg talent.

Padthai gains Padthai's Electrical Charge.
Raider's Training Dummy suffers 393 Arcane damage from Padthai's Moonfire.
Padthai's Shooting Stars fades from Padthai.
Raider's Training Dummy suffers 402 Nature damage from Padthai's Insect Swarm.
Padthai gains Padthai's Electrical Charge (2).
Padthai's Electrical Charge fades from Padthai.
Padthai's Lightning Bolt hits Raider's Training Dummy for 7021 Nature.

**Comment by PolpoVolante** [comment] 2016-12-01 14:56
Yes my bad now that i checked it same here.

http://imgur.com/a/kEHRD

this is my test no buff and no self buff with gear with 9400 spell power with the hc and 9340 with the normal.

**Comment by therealpadthai** [comment] 2016-12-01 18:27
Okay, after more testing, simming with some inconclusive data, some digging for more information, I am not too sure that the heroic version is supposed to be buffed with the x2.6 increase.

If we check wowhead changelog files for both normal and heroic trinket uses, we see that:
A) non-heroic version was buffed with the x2.6 increase (http://www.wowhead.com/spell=96887/variable-pulse-lightning-capacitor#changelog).
_It's at 2926 damage value_
B) heroic version was not buffed with the x2.6 increase (http://www.wowhead.com/spell=97119/variable-pulse-lightning-capacitor#changelog)
_It's at 3301 damage value_

In Simcraft I have noticed these two lines in the RAWR imported code that point to this very fact as well:
A) non-heroic: trinket1=variable_pulse_lightning_capacitor,ilevel=384,quality=epic,stats=406int,equip=onspellcrit_2926.3nature_15%_10stack_2.5cd_chance
B) heroic: trinket1=variable_pulse_lightning_capacitor,heroic=1,ilevel=397,quality=epic,stats=458int,equip=onspellcrit_3300.7nature_15%_10stack_2.5cd_chance

Again, this shows how the normal trinket is indeed given the x2.6 increase, however, as per Simcraft, which uses Blizzard scripts, the heroic version is not given an increase.

Now, I imagine it makes sense, this value. Blizzard probably realized the normal version was under-performing greatly, whereas if they buffed 3301 value by x2.6, it would skyrocket DPS. A small increase of approximately 400 damage, plus the extra intellect is probably what they were looking for on an item that is only an extra 13ilvl. This is still an upgrade.

Why are we seeing such similar results on Atlantiss? Well, **the normal version is buffed incorrectly with a 300% value**, but it should in fact by a 260% value, as per the OFFICIAL blizzard patch notes (https://worldofwarcraft.com/en-us/news/3019413). You can find the line in September 9th under the subheading items: "The Variable Pulse Lightning Capacitor now does an average of **2.6x** more damage than before, but is less likely to reach a large stack of charges."

**Comment by PolpoVolante** [comment] 2016-12-01 19:11
i suppose its possible. 
Now the only thing to check is why the damage on simcraft is so diverse? Regarding the min max values. I'm pretty sure my simcraft is 4.3.4 as it has t13 presets so both trinkets are in their final forms.

**Comment by therealpadthai** [comment] 2016-12-01 20:18
Yeah... no idea.. I'll have to do some more digging on that aspect as well

**Comment by Jenovas** [comment] 2016-12-18 13:20
Should be fixed in rev 5270

**Closed by Jenovas** 2016-12-18 13:20 UTC
