### ISSUE TITLE
[EN] Game Breaking Arena Re-spawn Bug

### ISSUE THREAD

**Issue by PvPbugreporter** [Atlantiss/BugTracker#9216] opened 2017-05-31 20:57 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The problem is that upon dieing in arena, instead of the person who died being put as a spectator, instead they respawn into the arena with nearly full health.
**Current behaviour**: What happens
I have experienced this happening to me and my opponents rather consistently. While I am not sure what causes it, it makes it so that they have a second life in the arena. Some people have abused this and came back to win and it really triggers me. If this bug is not fixed I will never play a private server again.
**Expected behaviour**: What should happen instead
What should happen instead is the person being killed should die and have the option to release spirit to specate. 
**Steps to reproduce the problem**:

1.  Enter a war game in arena 2v2
2. Cause someone to die from damage over time and bleed effects. Also try causing someone to die normally, basically just kill them.
3.  Repeat these steps until the bug occurs, it should not take long as it happens quite frequently. So far this has happened on the map Ring of Valor and Blades Edge Arena the most. This is a new problem that did not start occurring until the recent developer update. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) ACore rev. 5418 hash, bf0dc1c7e36a 2016-05-25

**Comment by xmesaj2** [comment] 2017-06-01 22:11
> Enter a war game in arena 2v2

Does it only happen in wargame arenas or also in normal rated arenas?

**Comment by PvPbugreporter** [comment] 2017-06-01 22:22
It does happen in rated arena, this is actually where I have been seeing it.

**Comment by Jenovas** [comment] 2017-06-02 10:11
I killed myself and ressurected over 50 times in both Ruins and Blade Edge.
I tried normal attacks, DoTs, DoTs + attacks, DoTs while being healed be a healer.

I could not reproduce this bug.
Please make a video with your friends if you may and show us what happens.
Thx.

**Comment by Jenovas** [comment] 2017-06-02 10:15
Also can you give me the nick of the players that revived?

**Comment by xmesaj2** [comment] 2017-06-02 10:23
Any additional information will help, for example which comp you played against when it happened etc

**Comment by PvPbugreporter** [comment] 2017-06-02 16:43
Sure, I will stream or record every time I play 2v2 until I can get it to happen several times. I get the feeling it has something to do with damage over time but cannot confirm this. The first time I saw this happen it happened to me when I was playing as Hadralt (sub rogue) with my friend miakhalifax (marksmen hunter) on the map ring of valor against unholy death knight with a holy paladin.(I cannot remember the names of these players alts that they were on but they are watchmewog and dkgodx on their mains. As soon as I died I was relocated to where you first spawn into the arena and I was alive. I then saw this happen on blades edge arena a little later when I was playing with the same partner. This time we were against unholy dk with a ret paladin (the unholy dk was valrath, I don't remember the ret). This time it happened to Valrath when we killed him.The last time I remember this happenening I was on my rogue learntorogue playing with a random fire mage (I can't remember his name) Our opponent was a horde feral and discipline priest. We played this team two times and the first time the glitch happened when we killed the priest, and in another game it happened to me when I died from the feral bleeds.

**Comment by PvPbugreporter** [comment] 2017-06-02 16:45
I forgot to mention, this only happened on the maps blades edge and ring of valor. It is worth noting we did not play many other maps though as these were the ones coming up.

**Comment by Heroclassx** [comment] 2017-06-02 18:05
can also confirm this and have some recordings of it, i will look @ my recordings and post it then.

+ can only confirm it happening in ring of valor

**Comment by Jenovas** [comment] 2017-06-02 18:08
Did you click release right away? Or did you wait some time?

**Comment by PvPbugreporter** [comment] 2017-06-02 18:37
I don't recall the release button appearing at all, and I had around 40-60% HP.

**Comment by PvPbugreporter** [comment] 2017-06-02 18:40
I played about 10 games today while recording and it didn't occur. On the day it did I played around 8 hours and about 60 matches.

**Comment by Jenovas** [comment] 2017-06-02 20:16
If you ever catch the bug on video or see anything that could help us solve this let us know.
We'll be testing this also and trying to find the cause.

**Comment by xmesaj2** [comment] 2018-02-12 23:07
was fixed with 5470

**Closed by xmesaj2** 2018-02-12 23:07 UTC
Labels: Battleground&Arenas, Core Mechanic
