### ISSUE TITLE
[EN] Problem with Vial of shadows for hunters.

### ISSUE THREAD

**Issue by cearal10** [Atlantiss/BugTracker#9881] opened 2018-02-28 23:26 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com) http://www.wowhead.com/item=77207/vial-of-shadows#comments
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past) N/A
[//]: # ([EN][NPC] Thoralius the Wise)  Morchok, Warlord Zon'ozz, Yor'sahj the Unsleeping, Hagara the Stormbinder, Ultraxion, Warmaster Blackhorn.
[//]: # ([EN][Spell][Class] Frostfire Bolt) Lightning strike
[//]: # ([PL][Talent][Class] Brain Freeze) N/A
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt) N/A
[//]: # ([EN][Npc][Drop] Thoralius the Wise) Morchok, Warlord Zon'ozz, Yor'sahj the Unsleeping, Hagara the Stormbinder, Ultraxion, Warmaster Blackhorn. 
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
Vial of shadows' doesn't proc for how much it should on hunters
**Current behaviour**: What happens
for hunters, it only procs for the set amount plus a little extra so far my highest proc is 6.3k
**Expected behaviour**: What should happen instead
it should proc for the basic 5035 damage Plus 0.9% of the attack power, or ranged attack power for the normal version. my hunter has 17753 RAP so that would proc for 15977.7+5035=21012.7
**Steps to reproduce the problem**:

1. get vial on any melee/ranged class that uses attack power/ranged attack power
2. target anything and damage it enough to proc the trinket's "lightning strike" effect
3. look at the damage its doing in recount

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat) 4.3.4

**Comment by cearal10** [comment] 2018-02-28 23:31
if it works for any of the melee classes such as rogue, feral druid and enhancement shaman, that 20k bonus damage is a huge advantage towards a hunter where it doesn't work correctly, all i ask is for an equal playing field in pvp and pve.

**Comment by Psychobird7** [comment] 2018-03-01 00:13
It seems to work fine on rogues etc, so it's probably just an issue with *ranged* AP not being used when applicable.       

The AP ratio you cited is incorrect however. 

Here are the correct values. 
- LFR: 3568 to 5353 (confirmed) (AP mod: 0.266)
- Normal: 4028 to 6042 (confirmed) (AP mod: 0.3)
- Heroic: 4546 to 6819 (confirmed) (AP mod: 0.339)

I think @pelekon scripted Vial, shouldn't be too hard to fix?

**Comment by cearal10** [comment] 2018-03-01 06:23
wowhead says different values, and i even datamines the values myself to double check, the correct values and percentages are the ones i listed.

**Comment by Psychobird7** [comment] 2018-03-01 08:43
Those numbers you listed would mean Vial had a 2.7 AP ratio before its initial nerf which would have been beyond asinine, even for Blizzard standards. 

http://www.wowhead.com/item=77207/vial-of-shadows#comments:id=1574792:reply=283301
This seems to be the comment you pulled those numbers from. 
The header clearly shows "patch 4.2.2", which means Vial was still on PTR when it was posted. Not exactly reliable. 

http://www.wowhead.com/item=77207/vial-of-shadows#comments:id=1592179 
Another example. "Patch 4.3.0", which was also *before* the hotfix. 

If you had looked at any sources citing post-hotfix numbers, you would have seen my numbers are correct. 
Please verify your sources in the future. 

The damages and AP coeffs I listed are from after the initial nerf in 4.3.2, and are backed by numerous logs. 
Take your pick from any of the following, and compare them to my initial research. You'll see my math is correct. 
http://www.worldoflogs.com/ranking/eu-us/firelands/dps/ 
http://www.worldoflogs.com/ranking/eu-us/dragon-soul/dps/ 

https://github.com/Atlantiss/BugTracker/issues/9493

**Comment by cearal10** [comment] 2018-03-01 13:36
the numbers i pulled come straight from the game files, i was just showing that i wasn't the only one that data-mined the files and what pulled up for me were also what other people have gotten, i clicked the links in the wolrdoflogs but as i try to pull up anyone of the "vial using classes" such as rogue's and feral druids for both DS and Firelands, all of them came up as "Page not found". but as a player of cataclysm on retail, i can confirm my numbers and ap ratios are what you were given, and yes even after the nerfs. im not the only one that confirms this and you can even see retail videos from cataclysm, showing the exact damage of Vial, how it was used in pvp and pve, and several recounts graphing the crits and normal hits of the item. the normal version always hit for  around 20k and crit for around 30k while the heroic verson did 5-7k more for both normal and crits. its pretty common to see a rogue and hunter hit these numbers in retail specially if they had some pve and the legendary daggers. your numbers are also from the stat nerf at the end of Mop, which was implemented for the opening of Wod.

**Comment by Psychobird7** [comment] 2018-03-02 00:08
FYI, game files are what generates tooltips, and tooltips have been known to be consistently wrong about the information they're presenting, especially following hotfixes. 
Said Vial nerf being a hotfix, you can probably see where this is going.  

And no, the AP ratios I listed are *not* from early Warlords. 

I'm not sure what you're on about WoL, the site works.   

Now how about you bring actual numbers, or some of those videos you keep talking about.

**Comment by cearal10** [comment] 2018-03-02 02:46
yes they can be wrong, but when i myself, and other people have gotten the same information, plus some comments saying the same thing in wowhead, i think its safe to say these are the true ratios. but like i said, i don't know how you can argue with the game files, these are the files from 4.3.4, the end patch of cataclysm, when everything that is there isn't going to change due to the next expansion on approach. you list numbers you've gotten from a site.

I list numbers iv'e gotten from the game files, a comment from wowhead saying the same, and again just go to youtube, 4.3.4 vial of shadows pvp/pve, you'll see the numbers from both burst and normal. all the sources you list are just numbers, you can't even click on a player to see what procced for him, how many times it procced and what it procced for. i think you need to do some more digging and send some more links that aren't just for display and you can actually get information from them.

you understand where i'm getting at? i'm not the only source that confirms this, what you linked generally is useless, and the ap ratios are yes, from the pre wod stat nerf. aslo notice how on the pre wad stat nerfed vial of shadows http://www.wowhead.com/item=77207/vial-of-shadows#comments it even shows the information you keep saying, except instead of doing  4028 to 6042 its just a flat 305 + # 0.3% attack power. seem any similarities yet? you've gotten your information wrong

**Comment by cearal10** [comment] 2018-03-02 03:06
https://wow.gamepedia.com/Vial_of_Shadows hmm the tooltip for this say 4028 + 0.3% so my bad you even go the base value wrong, for this is a pre wod nerfed vial aswell!

**Comment by RangerTalion** [comment] 2018-03-02 05:03
After tests conducted with a rogue guildie he was getting average hits of 11k and average crits of 17k from the Vial procs, while my average hits with it as Hunter are no more than 5,6k and my average crits no more than ~10k. (so basically just the tooltip damage) Even with the Rogue's multipliers and armor reduction on the target the difference in damage seems absurd. I have 19,2k Attack Power unbuffed at 394 ilvl as Survival Hunter and yet the Vial proc feels weaker than an autoshot. Thus I came to the conclusion that the bug regarding Ranged Attack Power isn't fixed in Atlantiss's current version of the item, which limits the ability of Hunters to keep up in DPS with other classes that truly shine.

**Comment by Arakis14** [comment] 2018-03-03 19:25
So does this trinket work correctly? I use this trinket on a enh shaman with unbuffed AP 16558 (have in mind enh shaman has unleashed rage up at all times - 20% melee AP). I tested the ligtning strike (Vial of Shadow proc) dmg by attacking a dummy until I have a good sample (100). The lowest possible dmg was 6167 . Does it mean its ok? From what you guys said and another post on the bugtracker regarding the dmg and AP scaling it shoud deal slightly more. The lowest possible for me would be: 4028 +0.3*16558=9004
I'll attach pics for you'all. (Sorry for bad paint skills :D)
![3](https://user-images.githubusercontent.com/36998871/36938375-e66d78a0-1f20-11e8-8130-83e418d9384e.png)
![2](https://user-images.githubusercontent.com/36998871/36938376-e68b0a82-1f20-11e8-85af-f0b681d342d7.png)

**Comment by Piklo** [comment] 2018-03-03 19:52
there is a difference between attack power and ranged attack power, that's why they are talking only about hunters

**Comment by Psychobird7** [comment] 2018-03-04 02:53
^ it works perfectly fine for everyone except hunters, because the trinket only scales with AP and not ranged AP.

**Comment by RangerTalion** [comment] 2018-03-04 09:18
Is this a complicated thing to fix - script? Can we expect it to be fixed anytime soon?

**Comment by Arakis14** [comment] 2018-03-04 09:43
Yeah I get it guys but number still don't feel right. May I ask: what are the average procs for other non-hunter classes?

**Comment by ZappBrannigan93** [comment] 2018-03-04 11:15
Arakis: probably the reason why the numbers are not what you expect is that the procs of vial deal physical damage, which is mitigated by armor, even on dummies. I've tested it with a feral with 21k ap and armor reduction with faerie fire on dummies and the average proc was around 8.4k. The formula seems correct, except for hunters, as has already been said.

**Comment by Arakis14** [comment] 2018-03-04 11:42
Ok, thank you @ZappBrannigan93 .

**Comment by RangerTalion** [comment] 2018-03-06 06:17
Also on the matter of Ranged Attack Power can anybody confirm if Hunter's Mark correctly applies the 1.772 bonus Ranged Attack Power because I see no actual difference in my DPS nor does my Serpent Sting deal more damage with Hunter's Mark applied on the target as I believe it should which makes me think it is also not working properly

**Comment by firemagegodx** [comment] 2018-03-06 09:42
Damage is probably set to melee attack power even for hunters, since the proc seems to do more than the base damage. Nonetheless, not like this is any good for anything that isn't a Subtlety Rogue anyways.

**Comment by RangerTalion** [comment] 2018-03-07 15:18
Feels bad then!
![Uploading WoWScrnShot_030718_171720.jpg…]()

![wowscrnshot_030718_171716](https://user-images.githubusercontent.com/26337767/37100408-88764912-222b-11e8-847c-2fb4e5c46c22.jpg)

**Comment by RangerTalion** [comment] 2018-03-07 15:21
Feels bad then 
![wowscrnshot_030718_171716](https://user-images.githubusercontent.com/26337767/37100478-be410b5e-222b-11e8-8719-58f27bfb8e17.jpg)
![wowscrnshot_030718_171720](https://user-images.githubusercontent.com/26337767/37100479-be7ae202-222b-11e8-804a-19b9ba827537.jpg)

**Comment by RangerTalion** [comment] 2018-03-14 02:01
I love how this issue has been one of the most commented lately, also quite a significant bug for Hunters especially for guilds raiding 25M and doing Council Loot on trinkets, so some poor bastards will probably end up chasing it for months...but it seems like devs are ignoring this!

**Comment by Piklo** [comment] 2018-03-14 07:28
We are not ignoring it, we are just kinda busy with other stuff

**Comment by pelekon** [comment] 2018-03-14 11:48
Should be fixed in rev 5690

**Closed by pelekon** 2018-03-14 11:48 UTC

**Comment by RangerTalion** [comment] 2018-03-14 11:51
Well my sincere apologies and my biggest thank you Devs!
