### ISSUE TITLE
[EN][Item][Spell] Gladiator's Wyrmhide 4 piece bonus

### ISSUE THREAD

**Issue by Nappelinc** [Atlantiss/BugTracker#4034] opened 2015-07-31 21:14 UTC
The "While not in an Eclipse state, critical attacks done to you restore 20 Solar or 13 Lunar energy, whichever is more beneficial to you. This effect can only occur once every 6 sec." -part of the item http://cata.openwow.com/item=65552 does not work. I tested it, but it seems to do nothing.

**Comment by kadi2** [comment] 2015-08-01 00:16
"whichever is more beneficial to you" This part is about that it shouldn't actually proc if you are in eclipse state

**Comment by Nappelinc** [comment] 2015-08-01 14:12
That's correct, but it does nothing in every case.

**Comment by Astrobazooka** [comment] 2015-12-16 18:07
Great report of very important bug. This set bonus due to its synergy with Euphoria talent helps in mana regeneration. Would be amazing if you could finally fix it ! All Moonkins that play any kind of pvp are in need of this set ! BUMP !

**Comment by Astrobazooka** [comment] 2015-12-17 14:40
#4034
Warto dodać, że bonus z tego setu również powinien pierw dać energię w stronę Lunar Eclipse.
https://youtu.be/EOQz1PS0jlo?t=1m30s 1m30s

**Comment by Fearyourself** [comment] 2016-01-30 18:41
Confirmed. Fought rsham/boomking today and they wanted to quit once the owl's blue bar was at zero.

**Comment by Jenovas** [comment] 2016-02-02 13:38
Fixed in rev 4861

**Closed by Jenovas** 2016-02-02 13:38 UTC
Labels: Item, Spell - Generic
