### ISSUE TITLE
[EN][Mage][Spell] Ignite

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#3130] opened 2015-04-30 05:31 UTC
Combustion and Ignite should be calculated differently in 4.3.4 with some damage modifiers and probably scale dynamically with them. 

WHAT'S WORKING INCORRECT: IT'S SNAPSHOTING MODIFIERS ON THE SERVER.

What this change really brings?
You shouldn't be able to deal full damage to Shadow Priests through Dispersion, Rogues through Cheat Death, Ferals through Survival Instincts etc. if you casted combustion or scored critical strike that proc ignite before they get their dmg mod buffs on.

http://eu.battle.net/wow/en/forum/topic/2504843963 // about combustion and ignite after SECOND hotfix
"-It doesn't say anything about damage modifiers after combustion is applied, as much as I absolutely love seeing a rogue burning for full damage during cheat death I don't think that change is reverted, will need further testing."
"They used to be ignored, but Combustion properly adheres to all modifiers now."

http://www.wowhead.com/spell=11129 // combustion
http://www.wowhead.com/spell=12654 // ignite
https://github.com/Atlantiss/BugTracker/issues/2020 // Latest bug report

**Comment by Jenovas** [comment] 2015-04-30 07:58
So you mean that if you hit a druid with survival instinct on (-50% DMG) even after survival ends the DMG of combustion will be 50% lower?

**Comment by kadi2** [comment] 2015-04-30 19:21
It was months ago when i was testing it. Testing it again and i can say combustion is probably working correctly with damage modifiers on the target. The only issue is the ignite is snapshotting  damage modifiers on the target. On the server Shadow Priest is getting full damage from ignite during Dispersion if ignite was applied before.

I couldn't find nicer proof ignite shouldn't be snapshotted by damage modifiers on the target, but i hope this should be enough.
https://youtu.be/p667ZATEkPY?t=7m16s Watch it at 0.25 speed to see ignite, cheat death buffs/debuffs and numbers clearly
Rogue is taking 2680 damage from ignite before the cheat death proc
After Cheat death proc he takes 2680 * .2 = 536 damage from ignite reduced by 80%

I am so sorry for confusions with combustion.

**Comment by Jenovas** [comment] 2015-05-01 09:58
So the problem is ignite. Ok I'll take a look at that

**Comment by blinkmaster** [comment] 2015-11-23 14:45
bump big buff bug vs cerain classes / encounters with reduced damage

**Comment by Jenovas** [comment] 2015-12-07 20:58
Fixed in rev 4694

**Closed by Jenovas** 2015-12-07 20:58 UTC
Labels: Class - Mage, Spell - Generic
