### ISSUE TITLE
[EN][Spell][Mage][Living Bomb]

### ISSUE THREAD

**Issue by Fearyourself** [Atlantiss/BugTracker#6156] opened 2016-01-30 12:11 UTC
Link to living bomb: http://www.wowhead.com/spell=44457/living-bomb#modified-by

This spell is NOT supposed to bring the target of LB in combat once it explodes.

I don't know if this is proof enough, but if it's not please let me know.
Living bomb isn't supposed to bring the target (nor the casting mage) in combat once it explodes.

http://eu.battle.net/wow/en/forum/topic/2868759154

**Comment by blinkmaster** [comment] 2016-01-30 12:22
http://eu.battle.net/wow/en/forum/topic/2723296789

period before the patch saying it worked like that on normal server , not ptr. give proof it shouldnt be like this ( you wont ).

**Comment by kadi2** [comment] 2016-01-30 12:25
As far as I know, Atlantiss is trying to bring as close blizzlike  experience as possible. So it's not going to be looked into

**Comment by BialyADI** [comment] 2016-01-30 14:05
It work as it should.

**Comment by blinkmaster** [comment] 2016-02-20 12:48
can be closed this is not a bug
@Aviannaqt

**Closed** 2016-02-20 13:27 UTC
Labels: Class - Mage
