### ISSUE TITLE
[EN][Spell][Mage] Frostfire Orb

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#1543] opened 2015-01-13 13:14 UTC
1.Flame Orb didn't actually hit targets in most Crowd Control effects that would normally break from it's damage, i found a proof for few spells:
http://youtu.be/jLnR0Whlw_s?t=9m55s // Flame Orb and Blind
http://youtu.be/cXE0nTMQn2M?t=18m32s // Frostfire Orb and Fear

2.Frostfire Orbs switches targets to whoever is closer to it's center, making the Orb more powerful versus stealthed classes in PvP scenarios. I guess it should switch targets only when it can't attack it's previous target.
http://youtu.be/cXE0nTMQn2M?t=24m47s
http://youtu.be/fL6pzResomQ?t=12m4s
http://youtu.be/fL6pzResomQ?t=14m22s // The worst Orb targeting AI i have ever seen

3.Flame Orb should not attack targets in the Smoke Bomb (even if the Flame Orb is inside the Smoke Bomb), just tested it with Flame Orb on main, it may be similar mechanic to this one i posted in Spirit Link Totem issue.
http://youtu.be/fL6pzResomQ?t=12m4s

http://cata.openwow.com/spell=82731 // Flame Orb Spell

**Comment by Wolffenstein** [comment] 2015-01-13 15:56
2. Applies only to Frostfire Orb or Flame Orb as well?

**Comment by kadi2** [comment] 2015-01-13 16:35
I am just pretty sure both effects had the same mechanic, 

Updated the link Frostfire Orb and Fear (forgot to add the timer)

I also noticed it's breaking Vanish effect, While doing some researches to prove otherwise, i found out it existed on retail. Just curious if they really didn't fix that in late patches, all the posts about this were made before 4.0.6 patch.
http://www.skill-capped.com/forums/showthread.php?9551-Fire-orb-breaking-vanish

**Comment by Wolffenstein** [comment] 2015-02-13 20:40
https://www.youtube.com/watch?v=gAQ3NrULDQA 0:16 
+ your movies - orbs always switch targets to those closest to them, so it's not a bug.

**Comment by Wolffenstein** [comment] 2015-02-13 21:10
Fixed in rev 4320.

**Closed by Wolffenstein** 2015-02-13 21:10 UTC
Labels: Class - Mage
