### ISSUE TITLE
[EN][Vanish][Rogue] Vanish Breaks Stealth

### ISSUE THREAD

**Issue by PvPbugreporter** [Atlantiss/BugTracker#9522] opened 2017-09-12 14:16 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
http://www.wowhead.com/spell=1856/vanish

**Description**: Describe the problem
  The problem occurs when a rogue is in stealth and uses the spell vanish. The rogue is then taken out of stealth and vanish does not take affect, similar to if the rogue removed stealth himself.
**Current behaviour**: What happens
Stealth is removed and vanish cool down is spent but did not take effect.
**Expected behaviour**: What should happen instead
When vanish is used in stealth the buff "Improved Stealth" should be applied.
**Steps to reproduce the problem**:

1. Take a subtlety rogue (Not tested on other specs).
2. Have them enter stealth.
3. Have them use vanish from stealth.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
ACore rev. 5495 hash. 4f7281da05c9 2017-09-12 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by bijtankga** [comment] 2017-09-12 18:54
rev: 5498 (after some vanish bugfix)
In assa and combat it looks good but problem is in sub.

**Comment by PvPbugreporter** [comment] 2017-09-12 18:57
amaybe tbe problem is witb master of subtetly

**Comment by lamaATS** [comment] 2017-09-12 20:17
@PvPbugreporter You are right, I was working on it today this bug was caused by some kind of typo in code when casting `Master of Subtlety`. I have it already fixed on my local server. Same problem when when you cast Vanish in Vanish (Prep for remove cd) both cases are fixed.

**Comment by PvPbugreporter** [comment] 2017-09-12 20:19
@lamaats Thanks so much :)

**Comment by lamaATS** [comment] 2017-09-12 20:47
Fixed in rev. 5501

**Closed** 2017-09-12 20:49 UTC
