### ISSUE TITLE
[ENG][Quest][Terokkar Forest] The Final Code

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2387] opened 2015-02-25 00:23 UTC
http://www.wowhead.com/quest=10447/the-final-code

Upon usage of the code a message appears that the quest is completed, but neither does the quest log show the quest as completed nor does a question mark show up on the map marking the quest giver.

**Comment by lourrific** [comment] 2015-05-29 22:53
This quest is still broken as of May 29, 2015. It is part 4 of a 5 part quest chain. 

As a result of this quest being bugged the following quest is also broken. 
Letting Earthbinder Tavgren Know http://www.wowhead.com/quest=10006/letting-earthbinder-tavgren-know

**Comment by Technowizard15** [comment] 2015-05-30 01:36
If I do remember correctly, the quest quest is doable. The only thing is that the quest isn't marked as completed in the quest log nor are the quest markers changed, marking Tooki (http://www.wowhead.com/npc=18447/tooki) as the person to submit the quest to.

**Comment by otto943** [comment] 2015-06-07 20:43
BUGGED.. activated mana bomb and nothing happened...fix it!

**Comment by Tarvo27** [comment] 2015-07-17 20:19
It is doable, you just need to take the quest in to Jenai Starwhisper, even if the log doesn't say it's completed. If you get the message of completeing it, then it's done.

**Comment by TheCopacabanaMan** [comment] 2016-07-15 09:11
Confirmed. Quest doable.

**Comment by xolon** [comment] 2016-11-06 17:31
Closing because the issue is better explained in the newest report with the new template. #8481

**Closed by xolon** 2016-11-06 17:31 UTC
Labels: Quest - TBC
