### ISSUE TITLE
[EN][Talent] Lunar Shower

### ISSUE THREAD

**Issue by Milton3450** [Atlantiss/BugTracker#2933] opened 2015-04-04 17:45 UTC
Lunar shower does not generate 8 solar/lunar energy. The damage increase seems ok tho.

http://www.wowwiki.com/Lunar_Shower

**Comment by kao194** [comment] 2015-04-04 18:42
Works as intended, checked both in moonkin/caster form. Managed to enter both eclipses with only moonfire spam

**Comment by Milton3450** [comment] 2015-04-04 18:48
I have 1/3. Maybe that is why it doesn't work. It should still generate 8 points no matter how many points you have spent.

**Comment by Varchord** [comment] 2015-04-05 10:13
Lunar shower eclipse energy generation is working as intended. There is problem with eclipse entering but it wont be fixed anytime soon.

Also issue for lunar shower spread exist so this one should be closed

**Comment by Milton3450** [comment] 2015-04-05 16:23
How can you say that it's working as intended when it's clearly not working for me? Is the problem something on my side? Have u tested with 1/3 in the talent?

**Comment by Varchord** [comment] 2015-04-05 16:36
I will when i come home. If it's not working i will add this to my issue. That doesn't hange the fact that this issue shoud be closed

**Comment by Milton3450** [comment] 2015-04-05 16:55
You can close it then, just remember to test/add it yourself in your own issue.

**Closed** 2015-04-05 17:38 UTC
