### ISSUE TITLE
[EN[Spell][Warrior][NPC] Charge on Restless Infantry/Solider

### ISSUE THREAD

**Issue by Zabiasty** [Atlantiss/BugTracker#736] opened 2014-12-18 21:33 UTC
Charge on Restless Solider/Infantry in Tol Barad causes wow crash. Please fix it as soon as posibble.

www.wowhead.com/class=100

http://www.wowhead.com/npc=46825/restless-soldier
http://www.wowhead.com/npc=46823/restless-infantry

![wowscrnshot_121814_223251](https://cloud.githubusercontent.com/assets/5214950/5496270/d508314c-8705-11e4-9d55-837986f40252.jpg)

**Comment by fifi147** [comment] 2015-01-14 20:06
I can also confirm this in the same place, the whole situation ended up like this:
![635af5a0d10349b11f076b55f9c8cf9e](https://cloud.githubusercontent.com/assets/6854838/5746375/756b5054-9c2f-11e4-8cbd-2141d1423fb2.png)

And it's NOT the charge's fault. I just walked up to these NPC in Tol Barad as a warlock and got crashed.

The same thing happens in the Shattered Halls in the tunnel with these NPCs:
http://www.wowhead.com/npc=16593/shattered-hand-brawler
http://www.wowhead.com/npc=17462/shattered-hand-zealot

No idea which type of NPC does it (Zealot or Brawler) because there ale a lot of them in one place.

And here is my friend's screenshot of this place:
![a852b3e76f3aa051d39650ad861b8369](https://cloud.githubusercontent.com/assets/6854838/5746584/decb6678-9c30-11e4-9c7f-f70447aaa9d8.png)
NPCs are in front of the character.

Similiar WoW Error after eating a bunch of my RAM:
![635af5a0d10349b11f076b55f9c8cf9e 1](https://cloud.githubusercontent.com/assets/6854838/5746606/03f8646e-9c31-11e4-995b-60378e7ac77f.png)

**Comment by bgb** [comment] 2015-04-10 09:39
I dont think its fixed. When I charge those npcs my wow hangs permanently and I have close it with ctrl+alt+delete...

**Comment by Tj20** [comment] 2015-05-06 17:36
I had a look at the Infantry/Soldiers and the yellow mobs standing around because I thought this might be related to the mobs from Shattered Halls (#870) or Kaskala (#1791), but I was not able to reproduce this issue.

I tried pulling ony one mob at a time of the groups of 3, tried pulling 3 groups (= 9 mobs), tried Feign Death, but had not a single WoW crash in that area.

**Comment by bgb** [comment] 2015-05-06 18:05
Because it seems to cause wow error only when warrior use charge on those mobs. They dont cause erorrs if i hit them without chargin either:P

**Comment by Tj20** [comment] 2015-05-06 21:38
Since you get instant level 85s right now on the PTR I've made a warrior over there to test this issue.

I tried multiple things: charging the Infantrys, charging the soldier, intervene, fighting 2 groups at the same time... no problem, I had not a single WoW crash. after maybe 10-15 tries.

Maybe it happens with another spec (I was prot), maybe it has something to do with glyphs (I had none), but so far I could not reproduce this issure.

![pic](http://i.imgur.com/UFxNOj7.jpg)

**Comment by bgb** [comment] 2015-05-06 22:48
Try going arms and take Blitz talent (I have it on 1/2). Maybe thats the cause?

**Comment by Nukeey** [comment] 2015-05-07 06:09
Had 2/2 Blitz, no charge related glyphs.

**Comment by Tj20** [comment] 2015-05-07 10:06
I tried again as Arms. Charge the Soldier, charge the Infantry, 0/2, 1/2, 2/2 Blitz, pull one group and then charge into another... no luck, I couldn't reproduce this bug, my client didn't crash at all.

Step 1
![pic](http://i.imgur.com/WwRunaE.jpg)

After charge: all three stunned with 2/2 Blitz
![pic](http://i.imgur.com/E6eDbUF.jpg)

Now maybe it is fxed on the PTR already, but I don't think so because I've tested the bugged mobs in the Shattered Halls and in Kaskala on the PTR and they still do crash my client.

**Closed** 2015-08-21 10:44 UTC
Labels: Class - Warrior, NPC, WoW Error
