### ISSUE TITLE
[En][Warlock][Felhunter][Spell lock]

### ISSUE THREAD

**Issue by texa69** [Atlantiss/BugTracker#6435] opened 2016-02-16 17:43 UTC
Fel hunter's pell lock sometime miss and does nothing at all ! 
It's always 30% miss 70% success. That's a big problem for warlocks in arenas !

**Comment by texa69** [comment] 2016-02-16 17:44
Don't tell me that I'm not hit capped cuz I'm not that noob !

**Comment by blinkmaster** [comment] 2016-02-19 07:28
I cant reproduce that.

**Comment by kadi2** [comment] 2016-02-19 09:29
Its due to the serwer diff. But It always hits with interrupt instantly and then silences with delay.

**Comment by texa69** [comment] 2016-02-19 11:15
Sometimes it doesn't interrupt at all !

**Comment by Jenovas** [comment] 2016-02-19 15:48
Cant reproduce.
Please test it more and tell us next time how to reproduce this bug or even try creating a video if you have time.
Closing.

**Closed by Jenovas** 2016-02-19 15:48 UTC
Labels: Class - Warlock
