### ISSUE TITLE
[EN][Npc][Drop] Mal'ganis

### ISSUE THREAD

**Issue by dovahkonjz** [Atlantiss/BugTracker#9247] opened 2017-06-09 18:14 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Mal'ganis's cache isn't interactable with.

**Current behaviour**: It cannot be clicked.

**Expected behaviour**: It should be able to be opened and items inside it taken.

**Steps to reproduce the problem**:

1. Go into Culling of Stratholme
2. Expect phat lewt
3. Andas expresses his displeasure with the chest in question

**Revision**: ACore rev. 5434 2017-06-04 4:16:27 +0200

**Proof**: 
![wowscrnshot_060917_200317](https://user-images.githubusercontent.com/29311996/26988472-d9c74408-4d4f-11e7-8dd5-064d92a3434a.jpg)

**Comment by 1Andas** [comment] 2017-06-09 23:35
LOL. Confirmed that it's bugged still. (I also confirm that I hate that chest)

**Comment by Piklo** [comment] 2017-06-09 23:46
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14445-9247-malganis-loot-tables/
maybe now will work lul

**Comment by mdX7** [comment] 2017-06-16 16:53
@Piklo problem should be in core @ instance_culling_of_stratholme.cpp
Flag that should be removed is GO_FLAG_NOT_SELECTABLE. In core the Flag GO_FLAG_INTERACT_COND will be removed, but GO_FLAG_NOT_SELECTABLE still persists, that was a problem few years ago in TrinityCore.

**Comment by 1Andas** [comment] 2017-07-04 21:35
Bump.

**Comment by Piklo** [comment] 2017-07-04 22:18
last fix still not accepted, we have to wait

**Comment by 1Andas** [comment] 2017-07-20 21:43
@Myivo Why did you close the issue? It's not fixed nor working.

**Comment by dovahkonjz** [comment] 2017-07-20 21:46
Yeah. This is a constant occurrence here.

**Comment by Piklo** [comment] 2017-07-20 21:59
fix still not accepted, just wait :P

**Comment by dovahkonjz** [comment] 2017-07-20 22:01
Exactly, fix still not accepted, why is it closed? lul

**Comment by Piklo** [comment] 2017-07-20 22:04
aww, It doesn't matter since there is a fix but just not accepted yet

**Comment by 1Andas** [comment] 2017-07-21 14:13
@Piklo Thank you for reopening. Very much appreciated.

**Comment by Buggingtrack** [comment] 2017-09-25 16:14
Can still confirm as of today the problem still persist.

**Comment by Jenovas** [comment] 2017-11-22 23:46
Fix in rev 5541

**Closed by Jenovas** 2017-11-22 23:46 UTC
Labels: CF, Loot
