### ISSUE TITLE
[EN] [Core][Dungeon finder] Dungeon cooldown

### ISSUE THREAD

**Issue by masscin** [Atlantiss/BugTracker#2717] opened 2015-03-21 11:05 UTC
Dungeon cooldown does not allow to queue again when someone leave shortly after finding a party (or after DC) for df. I mean that if other player leaves dungeon, people left in dungeon cannot queue to find missing party member. When tank or healer leaves df that means end of dungeon because we have a cooldown.

**Comment by Tj20** [comment] 2015-03-21 13:57
might be related to #696 (although I'm not completely sure if it's a new issue or if it was described over there before)

**Comment by Aival94** [comment] 2015-03-21 14:05
This feature([Dungeon Cooldown](http://www.wowhead.com/spell=71328/dungeon-cooldown) ) is working just fine and is totally blizzlike i think. You cannot queue in dungeon finder for 15 minutes when you start one but you can ask a friend of yours to join and invite him/her(can use dungeon teleport most of the times to come to dungeon).

**Comment by Tj20** [comment] 2015-03-21 14:42
But if you enter a random dungeon and somebody leaves after 1 minute, the dungeon finder should be able to find other people so you can complete the dungeon*. That's not working, according to masscin.

*(unless you were in a group with the guy who left. Then everybody of the group who queued with him should get kicked out of the RDF. This was implemented so you don't ask a tank friend to shuttle you into an RDF group and then leave because he had no intention to actually tank.)

**Comment by Aival94** [comment] 2015-03-21 17:10
Ok. This one is not working right.It was implemented during 4.1.0 

"When there is only 1 player left in a Dungeon Finder group, they will now be able to queue for replacements as long as they queue within 2 minutes or stay in the dungeon."

http://wow.gamepedia.com/Patch_4.1.0

**Comment by Varchord** [comment] 2015-03-22 19:53
No Tj. haven't described this in my thread because this issue didn't exist at the time.

And I can confirm existence of this bug and will add this to my issue

**Comment by Aival94** [comment] 2015-05-29 13:58
i think now this one should be closed as was implemented in #696 one.

**Comment by Varchord** [comment] 2015-05-29 14:27
It's already there. I forgot to add the date though

**Closed** 2015-06-24 21:32 UTC
Labels: Core Mechanic
