### ISSUE TITLE
[En][Spell[Shaman] Unleash Elements and Earthliving Weapon

### ISSUE THREAD

**Issue by earodynamic** [Atlantiss/BugTracker#7395] opened 2016-05-11 00:30 UTC
Using Unleash Elements with Earthliving Weapon imbued should be a self healing if the target is an enemy, but instead it tries to cast the Earthliving Weapon healing on the targetted enemy, thus it shows the "Invalid Target" message.

**Comment by Jenovas** [comment] 2016-05-11 08:12
Earthliving Weapon should not be autocast.
When having as ench 2 weapons with Earthliving you will get an Invalid Target message.
When playing resto/elem with 1 waepon with Earthliving you will get an Invalid Target message.
This is how it worked on retail and youcan even find "bug reports" from shamans that claim that it is stupid that it works this way.

Not a bug. Closing.

PS - if it was changed or fixed in farther patches of cataclysm please show me the changelog.

**Closed by Jenovas** 2016-05-11 08:12 UTC
