### ISSUE TITLE
[EN][Spell][Druid] Swift Flight Form

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#711] opened 2014-12-18 07:50 UTC
http://www.wowhead.com/spell=40120
http://www.wowhead.com/spell=33943

Swift flight form should replace flight form on your action bar

**Comment by Isuel** [comment] 2015-01-31 18:59
confirmed

**Comment by Hordraric** [comment] 2015-03-22 19:59
would be rlly nice to fix it, sometimes i click in the other form. kinda annoying

**Comment by Thefakemccoy** [comment] 2015-05-21 23:58
Adding that after exiting dungeons if you are in flight form it pops you out.  Also if in Wintergrasp with out the battle going on you can not pop back into flight form, but you can mount a reg flying mount.

**Comment by Tulv** [comment] 2016-01-13 23:31
They also swap positions (usually after changing specs, sometimes for no apparent reason).  Very annoying for keybindings.

**Comment by PARANOiA32** [comment] 2016-01-14 14:11
Still there.

**Comment by Jenovas** [comment] 2016-01-14 16:13
Fixed in 4818

**Closed by Jenovas** 2016-01-14 16:13 UTC
Labels: Class - Druid, Spell - Generic

**Comment by PARANOiA32** [comment] 2016-01-14 16:49
![wowscrnshot_011316_174245](https://cloud.githubusercontent.com/assets/16690991/12330788/1bdf9f7c-bae7-11e5-9783-0ce7df90e978.jpg)
Fixed?

**Comment by Thefakemccoy** [comment] 2016-01-16 17:44
New issue. Not sure if its due to prior fix or new issue going to stay.

So i have seen a few fellow druids in world chat that lost flight form, but have swift flight form.

This is due to swift flight form should not be able to be learned from trainer until you learn 280% flying.

What happened.
People only bought 150% flying learned swift flight form prior to fix now only has swift flight form and cant use flight form since it is over written.

How to fix from a players point of view
Buy the next flying skill for the 280% flying.
