### ISSUE TITLE
[EN][Quest][Felwood] Wanted: The Demon Hunter

### ISSUE THREAD

**Issue by coba999** [Atlantiss/BugTracker#8924] opened 2017-02-13 08:03 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: quest [Wanted: The Demon Hunter](http://www.wowhead.com/quest=28217/wanted-the-demon-hunter) is bugged.

**Current behaviour**: speaking with [Feronas Sindweller](http://www.wowhead.com/npc=47923/feronas-sindweller) doesn't launch event. When you click on text line in dialog window nothing happens.

**Expected behaviour**: speaking with Feronas Sindweller should  start event.

**Steps to reproduce the problem**:

1. Take quest [Wanted: The Demon Hunter](http://www.wowhead.com/quest=28217/wanted-the-demon-hunter)
2. Speak to [Feronas Sindweller](http://www.wowhead.com/npc=47923/feronas-sindweller)
3. You can't continue quest

**Revision**: 5318

**Comment by Yoryuen** [comment] 2017-02-26 23:20
26 / Feb / 2017
Still not working. Feronas doesn't launch the event. 
The Felwood Quest achievement is impossible because of this quest that isn't working.

**Comment by Noviush** [comment] 2017-02-27 19:09
Confirmed, there is no interaction when you speak to Feronas.

**Comment by coba999** [comment] 2017-03-06 13:50
New info: quest object can be completed, but you can't complete the quest while speaking with [Feronas Sindweller](http://www.wowhead.com/npc=47923/feronas-sindweller) .
![wowscrnshot_030617_155035](https://cloud.githubusercontent.com/assets/15231821/23612581/a2b8a9ea-0284-11e7-8944-560eef1eb495.png)

**Comment by ElliothDracke** [comment] 2017-03-13 06:46
Still not working .. Seems to be leading to a lot more quests as i couldn't find any after that. The achievement is really unoptainable without this one.

**Comment by Ghoulrape** [comment] 2017-03-22 17:18
Still not working and blocking other quests needed to progress map and earn achievement.

**Comment by ExperBug** [comment] 2017-03-29 05:49
Confirmed there is no interaction when you speak to Feronas.

**Comment by aholler2** [comment] 2017-06-03 20:52
I got to where coba999 did. Still now working.

**Comment by galediex** [comment] 2017-06-15 17:10
I just complete this quest with no luck of completing the dialogue after defeating the demon hunter i re-attempted it 12 times with no luck. I was really getting into this part of the quest, but i guess i'll have to experience this some other time =(

**Comment by TranceAccount** [comment] 2017-07-09 12:26
Fixed in rev. 5453.

**Closed** 2017-08-17 09:21 UTC
