### ISSUE TITLE
[EN][IRONFORGE][DAILY-QUEST] I need to Cask a Favor 

### ISSUE THREAD

**Issue by morgs71** [Atlantiss/BugTracker#7144] opened 2016-04-10 14:39 UTC
I know the previous thread was closed because a fix was supposedly done, but this is still not working and is holding up the completion of 3 achievements.  The barrel is not present or clickable in Kharanos.

**Comment by Larcan** [comment] 2016-04-12 19:44
Can confirm

**Comment by monar92** [comment] 2016-04-16 19:53
I can confirm too. I waited 30 min for keg and still didn't respawn.

**Comment by Cellhawk** [comment] 2016-06-10 10:48
Bump.

**Comment by kvokul** [comment] 2016-06-14 08:05
On of the best part of this game is completing achivs, when one found every pieces of BiS pvp and pve sets (you need both of them for achives). 
It is very annoying, when people from Sunwell get for free lots of achive, that we are even unable to do (really - it is LONG list, starting with Stratholme, and Strand of the ancient), and from Cata content are broken.

This one made my day - I tried 3 weeks to do cooking achives, and then SURPRISE!!! Didnt even spawn a barrel.

**Comment by user1011** [comment] 2016-07-12 18:45
Missing: WoWhead links.

**Comment by MichaelArchangelo** [comment] 2016-07-12 20:33
http://www.wowhead.com/quest=29356 - the quest
http://www.wowhead.com/object=208872 - the barrel that doesn't spawn

**Comment by arndry** [comment] 2016-07-18 11:44
same here

**Comment by Noviush** [comment] 2016-07-24 12:36
still not working

**Comment by ofelia59** [comment] 2016-07-25 04:42
Hi, I have done all quests for the achievement in Ironforge except  [I Need to Cask a Favor] than I cannot finish  [Let's Do Lunch: Ironforge]. Solve it please

**Comment by Daknyas** [comment] 2016-07-30 21:58
Confirmed.

**Comment by Deonorth** [comment] 2016-08-07 10:55
still not working

**Comment by arndry** [comment] 2016-08-09 18:11
no one is assigned to solve this bugg so don't expect much... :/ and still not working

**Comment by Docholiday-Atlantiss** [comment] 2016-08-23 20:58
I can confirm the cask is not spawning in as it should.

**Comment by WilsonStark** [comment] 2016-09-24 16:19
Yep item doesn't spawn at all, i waited 15 mins and i even removed quest and took it again to see if it works, but still no luck.

**Comment by Navedonar** [comment] 2016-09-24 16:59
Add Cask of Drugan's IPA http://community.atlantiss.eu/index.php?/topic/11687-objectcask-of-drugans-ipa/

**Comment by Vyrtuz** [comment] 2016-09-28 13:08
Bump, [object=208872] still not present in Kharanos :)

**Comment by guthwine** [comment] 2016-10-11 00:39
bump

**Comment by CatchmeATS** [comment] 2016-12-14 09:36
Still not working.

**Comment by Malanie** [comment] 2017-01-30 17:50
today i was told in /word that this quest got fixed and is working. fussy me headed straight to IF and got the quest, went to Kharanos and.... guess no barrel 🤣 
like @kvokul said its so annoying with those sunwell guys. i finished [http://www.wowhead.com/achievement=2336/insane-in-the-membrane](url) just the other day since all my other wishlist titles are not possible... chef, loremaster, undying... 🥇

**Comment by TranceAccount** [comment] 2017-02-18 09:33
## Posted a fix on the forums.
http://community.atlantiss.eu/index.php?/topic/13246-gameobject-cask-of-drugans-ipa/

**Comment by 1Andas** [comment] 2017-02-27 13:14
Bump. Still not working.

**Comment by TranceAccount** [comment] 2017-02-27 18:56
Waiting for @Bildo to accept my fix.

**Comment by karolnpc** [comment] 2017-03-25 10:03
Bump

**Comment by TranceAccount** [comment] 2017-03-25 18:25
Soon™ by Kiper.

**Comment by TranceAccount** [comment] 2017-05-05 10:54
Can be closed. This has been fixed by Kiper.

**Closed** 2017-05-10 11:09 UTC
Labels: Cataclysm, Gameobject, Professions, Quest

**Comment by aendry** [comment] 2017-05-11 19:41
Wow thanks a lot I was thinking about this quest yesterday LOL
