### ISSUE TITLE
[EN][Spell][Rogue] Shadowstep

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/BugTracker#5452] opened 2015-12-27 22:37 UTC
Shadowstep puts you almost right on top of the targets hitbox making it easier to be detected.

Shadowstep doesn't abide to the z axis, constantly putting you into textures which can make you fall through the world...

**Comment by Genomnomnomnom** [comment] 2015-12-28 16:50
BUMP

**Comment by Genomnomnomnom** [comment] 2015-12-28 23:41
6 times under textures during one EotS is WAY TOO MUCH :<

**Comment by Evelinrose** [comment] 2015-12-30 18:00
Wait so the previous one is duplicate of this one,but this one is closed huh?idk what this is happening more and more now maybe they did some changes to mmaps but now it;s even possible to fall under textures even in completly flat out terrain like the one from second boss in baradin hold.

**Comment by xmesaj2** [comment] 2016-01-01 18:10
I can confirm this happening also in instances. I got under textures in Stonecore and Firelands with Shadowstep few times. On battlegrounds it's like 50% you will land in textures though and pvp with rogue is not viable like that.

**Comment by milzo** [comment] 2016-01-04 18:17
This happened so far in every single battleground, Blade's Edge Arena and Ruins of Lordaeron. This bug makes one spec/class almost unplayable in both PvE and PvP but it's so easily overlooked like it's nothing.

**Comment by xmesaj2** [comment] 2016-01-07 10:50
#5089 may be related

**Comment by xtul** [comment] 2016-01-07 20:55
bump
this makes a whole spec very unenjoyable. when you fall underground the only way you can "ressurect" is to alt+f4, and since the influx of new players queues are becoming very long. as it happens more and more often, subtlety rogues are seriously handicapped.

**Comment by xmesaj2** [comment] 2016-01-07 22:17
/script RepopMe() works for reviving after falling underground

**Comment by xtul** [comment] 2016-01-08 14:26
oh god, wish i knew about it earlier,  thanks m80

**Comment by crosik** [comment] 2016-01-08 16:04
BUMP

**Comment by Evelinrose** [comment] 2016-01-20 23:14
bump? :package: pls every single rogue in pvp,and pve will love you for this fix.

**Comment by Gladdos1337** [comment] 2016-01-21 16:35
Bump, for the love of god its impossible to play like this.

**Comment by BialyADI** [comment] 2016-01-26 23:23
Dont worry Warr Charge heave the same problem ;p.

**Comment by xtul** [comment] 2016-02-02 13:17
bumpan

**Comment by babbulu49** [comment] 2016-02-07 11:14
something like this should be first priority. especially over all quests.

**Comment by Evelinrose** [comment] 2016-02-08 14:09
After they extract mmaps one more time this issue will be fixed and mostly all other issues related to mmaps but it's something that takes time to get it working right.

**Comment by perkydon** [comment] 2016-02-28 19:36
BUMP, still doing so and it's extremely harmful to us rogues as it's a main part of our rotation.

**Comment by axorian0** [comment] 2016-03-12 16:25
"https://www.youtube.com/watch?v=c8QfJL84NQE&feature=youtu.be"

This happen all the time, evrytime i try to kill a mob, or even on PvP, it makes me so upset

**Comment by Crusaderz** [comment] 2016-03-13 10:30
shadowstep is my #1 death reason on a battlegrounds :-1:

**Comment by Jenovas** [comment] 2016-03-21 19:03
Should be fixed in rev 4943.
If it still happens please create a new issue and tell me exactly where it happened.

**Closed by Jenovas** 2016-03-21 19:03 UTC
Labels: Class - Rogue
