### ISSUE TITLE
[EN][Hunter] Lock and Load

### ISSUE THREAD

**Issue by Bjarzyna** [Atlantiss/BugTracker#6407] opened 2016-02-14 20:44 UTC
Lock and load: http://cata.openwow.com/spell=56453
Ice trap: http://cata.openwow.com/spell=13809
Lock and Load procs continously from Ice trap spell instead of just from trap trigger.
It seems like hunter gets Lock and Load procs everytime someone enters ice trap area. If many targets are trapped at once it can provide more procs than hunter can use.

**Comment by BialyADI** [comment] 2016-02-14 22:08
LoL i coś takiego pewno jest od dłuższego czasu i nikt się nie skapnoł, GG WP Atlantiss :>.

**Comment by lqlq32** [comment] 2016-02-14 22:49
"f many targets are trapped at once it can provide more procs than hunter can use."

You see like proc for every target but you still have only 2 charges.

**Comment by BialyADI** [comment] 2016-02-14 23:07
I tested it too.
And it is HUGE bug, Lock and Load proc every time some one go in your trap = Hunter can use Explosive Shot for free 100% up time.

**Comment by lqlq32** [comment] 2016-02-14 23:29
I guess we have different defenition for huge, in pvp - not sure how much ppl with average IQ going in ur trap. Also the problem is prob because it count when the debuff is apply to the target, not when the trap is triggered.

**Comment by BialyADI** [comment] 2016-02-14 23:48
It is no about our different defenition for huge :D.
But about Game balance Bug what makes Explosive Shot free almoust all time for Survi Hunters.

**Comment by lqlq32** [comment] 2016-02-15 06:06
Yea that rly will help on trash when tank walk with a mob in and out of the trap so one guy can use non-stop explosive shot.

**Comment by Bjarzyna** [comment] 2016-02-15 07:36
I ice trapped horde fighting last boss on alterac valley and was able to use free explosive shots for about 40 seconds non-stop. That's what I mean when I write "if many targets are trapped at once it can provide more procs than hunter can use.".
Also please don't insult people with IQ talk. Bug is bug, it needs to be fixed because it has major impact on pvp if hunter chooses to abuse it.

**Comment by lqlq32** [comment] 2016-02-15 07:48
Well it shouldnt be possible to get a proc at all because it has 10s icd in 4.3.4.

**Comment by BialyADI** [comment] 2016-02-15 16:00
So Buged is that:
Black Arrow and Icy/Frezing trap dont share same ICD of Lock and Load.
And Lock and Load proc every time some one go in your Ice Trap.

**Comment by BialyADI** [comment] 2016-02-15 16:54
https://github.com/Atlantiss/BugTracker/issues/6405
The same bug like on Lock and Load ICD.

**Comment by lqlq32** [comment] 2016-02-15 19:06
Black Arrow and Icy/Frezing trap dont share same ICD of Lock and Load.
You can test this easy - throw a blackarrow w8 for a proc remove it with the mouse and throw icy trap.

**Comment by BialyADI** [comment] 2016-02-16 22:23
Bump.
Allmoust all "good" Survi Hunters use that bug, they just runing Ice Trap and force mele class to go in and out of it to have 24/7 Lock and Load proc and it dont have ICD.
It is even more anoing then Combustion-Resi Bug.

**Comment by BialyADI** [comment] 2016-02-19 12:51
How its look like naw:
![wowscrnshot_021916_134958](https://cloud.githubusercontent.com/assets/5780624/13176119/d9b392e4-d70f-11e5-84eb-a24eff0e9c68.jpg)

**Comment by Jenovas** [comment] 2016-02-19 23:42
Fixed in rev 4904
Will no longer proc multiply times from Ice Trap and will have a shared 10 ICD between all spells that proc it.

**Closed by Jenovas** 2016-02-19 23:42 UTC
Labels: Class - Hunter, High priority

**Comment by lqlq32** [comment] 2016-02-20 06:58
Sure but they DO NOT have shared cd on retail because blackarrow is counted as fire trap (this is why 4p set doesnt work on blackarrow too) and icy/freezing arent fire traps.

**Comment by BialyADI** [comment] 2016-02-20 13:46
IT is shared like in Woltk.
But in Woltk was 22 sec and on Cata it is 10 sec.

**Comment by BialyADI** [comment] 2016-02-20 13:50
if there were no ICD, you would get spammed with procs from an explosive trap on a large group.
