### ISSUE TITLE
[EN][Spell][Druid]Pulverize

### ISSUE THREAD

**Issue by Zuntatos** [Atlantiss/BugTracker#1833] opened 2015-01-27 18:02 UTC
Skill description:

Deals 60% weapon damage plus additional 1624 damage for each of your Lacerate applications on the target, and increases your melee critical strike chance by 3% for each Lacerate application consumed for 18 sec.

The 1624 damage varies.
The increase in crit chance works perfectly.
Problem: The initial damage seems to be >100%, and the additional damage per application does a 1-15 dmg 'swipe' across multiple targets.

Some screenshots;

My avg dmg with melee, no buffs / procs:  ~2100
![a](https://cloud.githubusercontent.com/assets/10729195/5926310/7324418a-a66a-11e4-8ab7-3ba863702598.png)

Pulverize damage with 1 application: Initially 2337, hits 2 dummies for 2 dmg.
![c](https://cloud.githubusercontent.com/assets/10729195/5926477/987c615a-a66b-11e4-97b9-3c8057133185.png)

Pulverize damage with 3 applications of lacerate: The initial damage is 2242 (above avg melee) and then it hits 2 (!) dummies for 9 and 18 (crit)

![b](https://cloud.githubusercontent.com/assets/10729195/5926327/8818676a-a66a-11e4-99dc-fa5710d62ccc.png)

 Using this description, it should do ~1260 dmg + 4872 for 3 Lacerate applications to one enemy only. 
It currently is ~110% weapon damage + 2-3 dmg per application for each enemy in front of you.

**Comment by Varchord** [comment] 2015-01-27 19:03
Idk what the problem is
Wowhead Links

**Comment by Zuntatos** [comment] 2015-01-27 20:31
Updated with pics / some stats

**Comment by Jenovas** [comment] 2015-01-27 22:40
From what I see in the DBC it should do without any stacks 60% weapon DMG + 2706 due to a effect Blizzard calls SPELL_EFFECT_NORMALIZED_WEAPON_DMG.

Bonus DMG from Pulverize stacks fixed in rev  4286

**Closed by Jenovas** 2015-01-27 22:40 UTC
