### ISSUE TITLE
[EN][Quest][Badlands] The Day that Deathwing Came

### ISSUE THREAD

**Issue by martinelrey1979** [Atlantiss/BugTracker#4284] opened 2015-08-18 01:11 UTC
It fulfills the mission is not whatever you do please verify
http://www.wowhead.com/quest=27713/the-day-that-deathwing-came

**Comment by Pallitax** [comment] 2015-08-18 06:42
Duplicate of #1358

**Closed** 2015-08-18 11:21 UTC
