### ISSUE TITLE
[EN][Spell][Class][Npc] Killing Spree on Alizabal

### ISSUE THREAD

**Issue by Flinvoltx** [Atlantiss/BugTracker#9952] opened 2018-03-27 15:45 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: After today's update (27.03) Killing spree used on Alizabal teleports the character not far but further away from boss with each jump

**Current behaviour**: After today's update (27.03) Killing spree used on Alizabal teleports the character not far but further away from boss with each jump

**Expected behaviour**: KS should stop teleporting in melee range and should not teleport away.

**Steps to reproduce the problem**:

1. Go to Aliz
2. KS (I guess she shouldn't agro you for clear result)
3. Get upset

Didn't test much with other bosses or big mobs, but 2 KS on Aliz got the same bugged effect.

**Revision**: 5717

**Comment by pelekon** [comment] 2018-03-27 19:19
I can't reproduce that

**Comment by pelekon** [comment] 2018-03-27 20:00
found it, fixed in rev 5718

**Closed by pelekon** 2018-03-27 20:00 UTC
Labels: Cataclysm, High Priority, Raid - Cata, Rogue
