### ISSUE TITLE
Metamorphosis Immolation aura on demonology warlock

### ISSUE THREAD

**Issue by Hartwall** [Atlantiss/BugTracker#9194] opened 2017-05-22 06:41 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

The wowhead link doesnt work since it has been replaced into another one. And openwow is down.

**Description**: Immolation aura ends too soon on the second cast during metamorphosis.

**Current behaviour**: The demonology spec spell Immolation Aura that one can only use in metamorphosis currently ends when metamorphosis ends. This only happens when using the Glyph of Metamorphosis to cast another immolation aura at the end of meta.

**Expected behaviour**: After casting the second immolation the immolation aura should continue as normal after metamorphosis disappears. The only reason to get the glyph is to get a second cast of immolation aura.

**Steps to reproduce the problem**:

1. Cast metamorphosis
2. Cast Immolation aura and wait for its cooldown
3. Cast immolation again and look how it ends after ~3 seconds.

**Revision**: ACore rev. 5418 hash. 021a72b8fa98 2017-05-20 00:06:25 +0200 (4.3.4 branch) (Unix, RelWithDebInfo

**Comment by kadi2** [comment] 2017-05-22 08:13
But it's not a bug. Why you guys take so much effort to create those false reports?

**Comment by Wymorlas** [comment] 2017-05-22 14:43
His right , i played Demonology in blizzard (wotlk-cata and mist ) you can active two immolation with meta Glyph , and immolation goes active after meta fade .

**Comment by kadi2** [comment] 2017-05-22 19:25
@Wymorlas http://laserhemotherapyclinics.com/

**Comment by meowmewo** [comment] 2017-06-01 20:09
"The only reason to get the glyph is to get a second cast of immolation aura." - are you for real...

**Comment by ashrasmun** [comment] 2017-06-07 09:39
"His right , i played Demonology in blizzard (wotlk-cata and mist ) you can active two immolation with meta Glyph , and immolation goes active after meta fade, until the duration end."

It doesn't matter what you played and what you didn't. You either supply a proof or the issue will be ignored because of potentially false claims.

**Comment by ashrasmun** [comment] 2017-06-07 09:56
Ok, I actually took some time to validate this issue. It should be closed ASAP, because the Immolation Aura should never work, as OP describes in the main post. Currently, Immolation Aura works properly!

Proofs:
https://www.youtube.com/watch?v=f__LGzHItyU 2:44
https://www.youtube.com/watch?v=CdgySv5Apms: 17:30

**Comment by Piklo** [comment] 2017-08-01 09:50
change title

**Comment by lamaATS** [comment] 2017-09-10 15:42
Working as intended, it was fixed by Wolffenstein in rev. 3920.

**Closed** 2017-09-10 15:43 UTC
Labels: Spell, Warlock
