### ISSUE TITLE
[EN][ITEM][SPELL] Mage T10 4P Bonus

### ISSUE THREAD

**Issue by jerumbo** [Atlantiss/BugTracker#8749] opened 2017-01-01 13:21 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
The Set Bonus for T10 4P doesnt get Removed once you swap the Items as shows here:
http://community.atlantiss.eu/index.php?/topic/11247-fire-mage-gear-swap-opener/

http://www.wowhead.com/spell=70748/item-mage-t10-4p-bonus
http://www.wowhead.com/item-set=-839/bloodmages-regalia
http://www.wowhead.com/item-set=-228/sanctified-bloodmages-regalia
http://www.wowhead.com/item-set=-247/sanctified-bloodmages-regalia

**Current behaviour**: What happens
You keep the 18% more DMG Buff up.

**Expected behaviour**: What should happen instead
The Buff should be removed once you no longer have the 4 piece Set  Equipped.
changed in  4.0.6.13623 (aka 4.0.6a)
February 11 (Patch 4.0.6a)
https://worldofwarcraft.com/en-us/news/2259389

> Mages
The Quad Core buff provided by the Sanctified Bloodmage 4-piece set bonus is now properly removed as soon as a spell is cast if the mage does not have 4 pieces of the set equipped.

here are some people talking about it:
https://eu.battle.net/forums/en/wow/topic/4940485090#post-8
https://us.battle.net/forums/en/wow/topic/2065608814

**Steps to reproduce the problem**:

1. Equip the 4 Items of T10
2. Cast Mirror Images
3. Change your Equip
4. 18% more Dmg buff is still there

**Revision**: Current server version
ACore rev. 5275 hash. dcd588eb0030 2016-12-31 15:22:11

**Comment by therealpadthai** [comment] 2017-01-01 13:24
Wonder if this is the same for the other tier bonuses too, such as the enhance shaman shamanistic rage one.

**Comment by bonfax4** [comment] 2017-01-01 17:52
shaman one should be working in 4.3.Mentioned in this guide  [guide](https://us.battle.net/forums/en/wow/topic/3967597855)

**Comment by therealpadthai** [comment] 2017-01-01 23:39
Solid

**Comment by sigmundfreud2016** [comment] 2017-01-04 13:57
Not sure if we should praise old blizzlike bugs. Even if they didn't manage to fix it in 4.3.4, but admitted it was a bug later.

**Comment by therealpadthai** [comment] 2017-01-07 10:27
Hindsight is 20/20. While I agree that bugs later admitted by blizzard in later patches and fixed shouldn't be on atlantiss, it would not be true to the blizzlike feature of this server in the first place. We get to enjoy the best and worst of what was patch 4.3.4.

**Comment by stanq87** [comment] 2017-01-27 09:28
i hate mages that boast about their dmg but  use this bug openly

**Comment by sigmundfreud2016** [comment] 2017-01-27 14:11
@therealpadthai the problem is that now a lot of people know about this bug and will gladly abuse it. Back then only few did. One upcoming vanilla server is going to fix widely known blizzlike bugs exactly for this reason.

**Comment by stanq87** [comment] 2017-03-19 21:14
so when are the GM's going to perm ban  for this ?

**Comment by Aival94** [comment] 2017-05-24 18:52
The devs said by trusting a post from MoP and some of their trusted players probably that this is not a bug so do not expect a lot anymore about this bug (which was during cata till 4.1).

**Comment by zekk3n** [comment] 2017-05-25 23:52
Their trusted players who play fire mages in the server and have no idea about how it actually worked in retail?

Pathetic. Countless proofs have been presented already, guess it's pointless.

**Comment by Jenovas** [comment] 2017-06-02 11:46
Fixed in rev 5429.

**Closed by Jenovas** 2017-06-02 11:46 UTC
Labels: Confirmed, Mage
