### ISSUE TITLE
[EN][PL][Quest][Ashenvale] Demon Duty

### ISSUE THREAD

**Issue by Avalain** [Atlantiss/BugTracker#4403] opened 2015-08-30 16:16 UTC
[EN]
Quest: http://www.wowhead.com/quest=13806/demon-duty
Crystals don't have interactive patterns under them, therefore you can't complete quest.
Addon says it was working Blizzlike so there might be a chance that bugged crystals spawn after someone finish quest after restart (where at 1st quest objects work).

[PL]
Quest: http://www.wowhead.com/quest=13806/demon-duty
Kryształy nie posiadają interaktywnego wzoru pod sobą, nie można zatem zaliczyć zadania.
Addon pisze, że quest działa Blizzlike więc najprawdopodobniej kryształy bugują się gdy ktoś wykona zadanie zaraz po restarcie, nie respawnując wzorów.

**Comment by Angelo-DM-** [comment] 2015-11-07 15:53
Confirm! Crystals are not interactive... You can't click on them.
video of how it should work: https://www.youtube.com/watch?v=xoSdLqAZynw

**Comment by JurajNyiri** [comment] 2016-01-22 14:28
Confirming, crystals are not clickable.

**Comment by intrepid70** [comment] 2016-04-25 01:20
Confirmed.  Quest is still not complete-able.

**Comment by JohannDoe** [comment] 2016-11-20 12:09
Confirmed. Not clickable.

**Comment by Nuggfush** [comment] 2018-01-14 16:31
Quest still not completable. Cannot interact with crystals.

**Comment by Bildo** [comment] 2018-10-20 22:56
Partially fixed, the problem is that there are 2 crystals at the same spot. One is for quest Stopping the Rituals and second is for Demon Duty. During quest Stopping the Rituals crystals should be phased but for now they are not. I guess it will be fixed later because it is a phasing issue

**Closed by Bildo** 2018-10-20 22:56 UTC
Labels: Content: Classic, Quest
