### ISSUE TITLE
[EN][Quest][Molten Front][Shadow Wardens]The Forlorn Spire

### ISSUE THREAD

**Issue by ponpontos** [Atlantiss/BugTracker#5694] opened 2016-01-06 11:39 UTC
Pyrelord is simply not spawning at all. I've been at spawn point (tower) with the NPCs for half a hour and nothing happens.

**Comment by anxanas** [comment] 2016-01-06 11:42
I can confirm this http://www.wowhead.com/quest=29205/the-forlorn-spire doesnt work at all,

**Comment by ponpontos** [comment] 2016-01-06 11:43
The weird thing is that when I passed over the tower to get the previous quest in the chain, Mysterious Seed, he was there and a group was killing him.

Maybe it's just the respawn timer?

**Comment by anxanas** [comment] 2016-01-06 11:50
Then he has a huge respawn time since i was waiting there for atleast 45 mins

**Comment by anxanas** [comment] 2016-01-06 12:12
i just did the quest the respawn time is HUGE

**Comment by ponpontos** [comment] 2016-01-06 12:47
Same, but encountered a new bug with the following dailies. In http://www.wowhead.com/quest=29189/wicked-webs#guides, the cocoons don't seem to be respawning correctly either, I've only encountered a couple of them just floating in the air outside the questing area, which didn't count for the tally.

**Comment by xolon** [comment] 2016-01-06 14:27
I believe you can close this, since the fix is in new revision

**Closed** 2016-01-06 14:32 UTC
Labels: New Content, Quest - Cata

**Comment by anxanas** [comment] 2016-01-07 09:04
Not fixed please reopen
