### ISSUE TITLE
[EN][Quest][Borean Tundra] The Plains of Nasam

### ISSUE THREAD

**Issue by ixvenomxi** [Atlantiss/BugTracker#8714] opened 2016-12-23 22:24 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: When i try to use the horde siege, the cast bar dont change for use it, and dont move the horde siege.

**Current behaviour**: I get into the horde siege but this one dont move and dont change the cast bar.

https://postimg.org/image/hck8dlpsh/

**Expected behaviour**: When i get up in the horde siege this one must move and should change the cast bar for use his abilities

http://www.wowhead.com/quest=11652/the-plains-of-nasam
https://www.youtube.com/watch?v=2_YqAxsZvYg

**Steps to reproduce the problem**:

1. Take the mision
2. Get up to the vehicle
3. move the vehicle to the zone of the mision
4. kill adds and rescue injure warsong soilder
5. get back and finish the mision

**Revision**: quest=11652

**Comment by Piklo** [comment] 2016-12-23 22:53
you can see current server revision by typing ".s in" in chat
#8203

**Comment by szentigrad3** [comment] 2017-07-31 02:48
Just tried to do this only one of the seige's work and i could not rescue any of the injured warsong soldiers, the seige engines where the quests start all have injured warsong soldiers in them

**Comment by MercuricUma** [comment] 2018-03-14 01:25
duplicate of issue #7251 

https://github.com/Atlantiss/BugTracker/issues/7251

**Comment by TranceAccount** [comment] 2018-08-09 14:51
The vehicle works.

**Closed by TranceAccount** 2018-08-09 14:51 UTC
