### ISSUE TITLE
[EN][TALENT][PRIEST] Improved Devouring Plague

### ISSUE THREAD

**Issue by janchux** [Atlantiss/BugTracker#9084] opened 2017-04-06 10:07 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Sometimes Improved Devouring Plague deals 1 damage also crits for 1 damage. Core doesn't recognize a valid value?
![one](https://cloud.githubusercontent.com/assets/17173602/24747992/dcac2000-1ac6-11e7-97ea-c36b4c5fca7a.jpg)
That particular fight was Ragnaros hc. On recount under Wrath of Tarecgosa doesn't register all spell procs.

**Current behaviour**: Improved Devouring Plague deals 1 damage

**Expected behaviour**: Due to talents it should deal 30% of Devouring Plague total periodic damage
**Steps to reproduce the problem**:

1. Select 2 point in shadow talent tree Improved Devouring Plague
2. Suggestionestion: Use Dragonwrath, Tarecgosas Rest set proc to 100%
3. Recreate raid environment atleast buff wise 
4.  Spam Devouring Plague 
**Revision**: 5357

**Comment by janchux** [comment] 2017-04-06 20:47
FL add Lava Wielder
![lava wielder](https://cloud.githubusercontent.com/assets/17173602/24774748/c6217b62-1b22-11e7-8a7b-1915b1607e90.png)
FL add Molten Flamefather
![molten flamefather](https://cloud.githubusercontent.com/assets/17173602/24774749/c6244554-1b22-11e7-8491-6c125dcd09ff.png)
add
![one2](https://cloud.githubusercontent.com/assets/17173602/24774750/c625a890-1b22-11e7-8204-351f74d23f7c.png)

**Comment by janchux** [comment] 2017-04-06 20:49
I think the Legendary Staff's proc of DP causes this to happen.

**Comment by Psychobird7** [comment] 2017-04-07 00:50
Did you count how many times you cast DP during your testing? 
The 1 damage "ticks" you're getting might be caused by a "trigger" tied to the spell, and not override the actual damage of the application.        

A similar thing happens with paladins' Consecration, where its "trigger" attacks the closest enemy for 1 damage.

**Comment by janchux** [comment] 2017-04-07 05:24
I dont understand what you mean.
On boss fight' s I spam the sh!t out of my DP every time I am moving.
I didn't count. Yesterday had a raid I noticed ones on my screen so I screenshoted it.
I think Consecration works in a different way then Imp. Dev, Plague. Every time I use DP I get Imp. DP as first instant damage which itself isn't a dot so I should do damage every time I press it.

**Comment by Psychobird7** [comment] 2017-04-07 05:41
~~Nevermind.~~

**Comment by kadi2** [comment] 2017-04-09 07:26
are you sure it's not a subject just for targets at 1 HP ?

**Comment by janchux** [comment] 2017-04-09 07:50
yes I am sure

**Comment by janchux** [comment] 2017-04-17 20:51
Ragnaros hc fight
![one 17](https://cloud.githubusercontent.com/assets/17173602/25104302/6b62ddfc-23c8-11e7-84a5-bac74f0383f9.jpg)

**Comment by janchux** [comment] 2017-05-08 21:38
This is what shows up on the combat logs. Can provide those too.
1 damage: SPELL_DAMAGE,0x000000000006C584,"Janchux",0x511,0x0,0xF130CCB9000001DC,"Ragnaros",0x10a48,0x0,63675,"Improved Devouring Plague",0x20,**1**,0,32,0,0,0,nil,nil,nil

Normal damage: SPELL_DAMAGE,0x000000000006C584,"Janchux",0x511,0x0,0xF130CCB9000001DC,"Ragnaros",0x10a48,0x0,63675,"Improved Devouring Plague",0x20,**13431**,0,32,0,0,0,nil,nil,nil

**Comment by Candiise** [comment] 2017-06-24 14:03
UPP

**Comment by Dziara** [comment] 2017-08-12 08:21
4 months, nice

**Comment by Dziara** [comment] 2017-10-21 16:45
I missed the half-year anniversary to bump ;_;

**Comment by janchux** [comment] 2018-01-27 00:02
Haven' t made a pic for a while
![imp dev pleag](https://user-images.githubusercontent.com/17173602/35465412-691ee006-0304-11e8-81b6-183cedf60497.jpg)

2/9 was a ONE (upper)

For the most part it is a crit but a non-crit (lower) buggs out as well
![impr](https://user-images.githubusercontent.com/17173602/35465623-fd7bb91c-0305-11e8-948e-b773327aa0cb.jpg)

**Comment by janchux** [comment] 2018-02-08 20:10
Warlord Zon'ozz

![untitled](https://user-images.githubusercontent.com/17173602/35995663-c3fee44a-0d1c-11e8-98e4-4e6ace41e545.png)

**Comment by janchux** [comment] 2018-02-08 20:42
Yor'sahj the Unsleeping
![untitled1121](https://user-images.githubusercontent.com/17173602/35996003-dcd70d02-0d1d-11e8-8895-40740968bedc.png)

**Comment by pelekon** [comment] 2018-10-20 20:06
fixed in rev 5891

**Closed by pelekon** 2018-10-20 20:06 UTC
Labels: Class: Priest, Spell, Spell - Generic
