### ISSUE TITLE
[EN][Spell][Mage] Combustion Scaling Wrong

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#6493] opened 2016-02-20 15:40 UTC
Combustion dmg after fix scales wrong.The dmg reduced its just retarded compared to AT / Retail or any other server that you like.Current state of combustion dmg in pvp is like this, after landing crit with pyroblast and putting combustion the damage of ignite hit harder than combustion.Combustion should work like this.When Living bomb + ignite + pyroblast dots are up after using combustion resilliance shouldnt influence the calculating of the new dot combustion.Currently the dmg of combustion is too low.

"Combines your damaging periodic Fire effects on an enemy target but does not consume them, instantly dealing 955 to 1131 Fire damage and creating a new periodic effect that lasts 10 sec and deals damage per time equal to the sum of the combined effects"
http://www.arenajunkies.com/topic/206995-combustion-double-dips-resilience/page__st__20

The dots that are combined from combustion shouldnt get reduced again instead when its calculated.This means that if Living bomb ticks 3k dmg ignite 7k and pyro 1500 with resilliance the combustion should be calculated the same same 3k+7k+1500 after the calculation created resilliance should then only start affecting the dot currently it seems like combustion is already getting reduced by resilliance in the calculating part.Means it dubble dipping.

http://i.imgur.com/j74iNCd.jpg on how mutch resilliance tested.
http://i.imgur.com/t1I0Enn.jpg Ignite doing alone dubble more dmg than combustion (LB and pyro was up in the testing of that combustion)Meaning its reduced too mutch.

In the end I just wanna say that something is wrong with the calculation of combustion.Maybe its overcalculating in resilliance dubble dipping or ignite or some other dot is not getting affected into the total sum of the combined dot for combustion this should be checked out thx.

**Comment by BialyADI** [comment] 2016-02-20 15:52
You hit 3200 from Combustion so how much haste you have?
It will be 15*3200 = 48k Dmg dont forgot it tick every second.
And it scale frond with Haste for naw https://github.com/Atlantiss/BugTracker/issues/6284.

**Comment by Zhalox123** [comment] 2016-02-20 15:54
15% haste 2 extra ticks.Still the dmg from combined effects is reduced by too mutch.

**Comment by razgal** [comment] 2016-02-20 15:59
yes combustion sux right now, it needs a buff.

**Comment by BialyADI** [comment] 2016-02-20 15:59
( ͡° ͜ʖ ͡°)

**Comment by Fearyourself** [comment] 2016-02-20 15:59
Confirmed it's reduced by too much. It's not supposed to do this little damage.

**Comment by blinkmaster** [comment] 2016-02-20 16:05
http://us.battle.net/wow/en/forum/topic/3530366099
last comment.
to summarize - resi should work on living bomb i pyro.
it shouldnt affect ignite - due to fact ignite is created from the spell already affected from resilence ( like fireball) - also it was reported some time ago when i proved it shouldn't double dip with resi.
combustion shouldn't be affected by resi by the same mechanic - it combines effects which are already affected by resilence. indeed it worked like this on retail for some time but then it was reverted back.

http://www.arenajunkies.com/topic/206995-combustion-double-dips-resilience/page__st__20
one of the last comments.

i guess my posts were not noticed on the previous bug entry about combustion.

so yeah to summarize - combustion is fucked atlantiss style

**Comment by calladin** [comment] 2016-02-20 16:07
BialyADI "Finally Combustion dont Ignore Resi, and it should double dip with Resi." u are so wrong...  COMBUSTION SHOULDN'T GET DOUBLE DIPP FROM RESILENCE, BLIZZARD FIXED IT!!!

**Comment by ponpontos** [comment] 2016-02-20 16:11
It doesn't matter, fire mages still do a lot of damage. Combustion is not like a main mechanic or anything. If you have problems with that switch to arcane. 

Oh you're playing PvP? Better yet, switch to frost.

**Comment by BialyADI** [comment] 2016-02-20 16:12
It is not about Switch to forst ot some thing.

The jyst want to Compustion bypass Resi again ^^.

**Comment by blinkmaster** [comment] 2016-02-20 16:24
Are you blind or what? I gave proofs your bug entry about combustion was invalid and u give argumentation like IT SHOULD NT BECOUSE EVERY SPELL IS AFFECTED BY RESI. Its not

**Comment by calladin** [comment] 2016-02-20 16:28
Ponpontos "Combustion is not like a main mechanic or anything" Bro, combustion its only CD of Fire mages which gives him some nice dps (2MIN CD+ DISPELABLE DOTS). Fire mages with double resi dipp BUG of Combust are just USELESS.

**Comment by ponpontos** [comment] 2016-02-20 16:38
A good mage will adapt his playstyle around this bug and still top the charts. This is looooow priority.

**Comment by Zhalox123** [comment] 2016-02-20 16:44
Ponpontos if u dont see the issue in this session please stop talking trash cos u are clueless about the situation!Any player that played retail knows how the spell was working...And the link that blink showed proves about that it doesnt scale correctly.And you are stupid inuff to dont know that the main burst of fire mages is combustion so please get off the topic thx.

**Comment by debtheone** [comment] 2016-02-20 16:45
ponpontos is drunk and hes trolling no doubt

**Comment by Zhalox123** [comment] 2016-02-20 16:50
BialyADI  the combustion on that screen wont do 50-60k dmg calculate it by yourself 
12 ticks with 15 % haste = 12x 3186=38232 so there you go.....

**Comment by ponpontos** [comment] 2016-02-20 16:50
https://github.com/Atlantiss/BugTracker/issues/5539#issuecomment-178752669

**Comment by Zhalox123** [comment] 2016-02-20 16:54
I dont care w/e the problem is combustion currently in pvp is unbalanced and does too low dmg compared to retail I dont know if its becouse of resilliance scale or becouse ignite or any other dot is influencing not properly this matter should be checked and fixed thx!

**Comment by 4free100** [comment] 2016-02-20 19:01
give quodan his powers back ;(

**Comment by kadi2** [comment] 2016-02-21 00:13
1.Make combustion and ignite scaling with every modifier like every single spell in the game, throw away the flag it should ignore resilience.
2.Change ignite formula to be calculated on unmodified critical hits.
3.Change combustion to be calculated on unmodified ignite.
3.You can apply this change to deep wound and all similar spells.
4.Profit.

The only solution to make it not double dipp with modifiers, scale dynamically with them, and work correctly with mastery and fire power(mage's talent)

**Comment by Wolffenstein** [comment] 2016-02-21 11:03
The only issue is with Ignite portion of the damage - it double dips resi. LB and Pyro dmg bonus is working fine. 

Ignite double dip resi fixed in rev 4905.

**Closed by Wolffenstein** 2016-02-21 11:03 UTC

**Comment by kadi2** [comment] 2016-02-21 11:39
@Wolffenstein Ignite is snapshotting with damage modifiers and then scales dynamically with them again which shouldn't be case.

**Comment by Myrcool** [comment] 2016-02-21 15:55
Combustion is supposed to be affected by resilience. It already was pointed out in threads like:
http://www.arenajunkies.com/topic/206995-combustion-double-dips-resilience/
and us.battle.net/wow/en/forum/topic/2957165884
In which a r1 player clearly states using math that combustion is supposed to be reduced by resilience once. AND NO THE RESILIENCE AFFECTING DOTS ONCE DOESN'T MEAN IT SHOULDN'T AFFECT COMBUSTION ANYMORE - IT'S STILL A NEW DOT. Sorry you can't 1shot someone with a dot.
