### ISSUE TITLE
[EN][Spell] Inner Focus

### ISSUE THREAD

**Issue by debtheone** [Atlantiss/BugTracker#2062] opened 2015-02-05 22:01 UTC
In most cases inner focus is displayed as ready while being on cd.Its so irritating being interrupted due to this bug.
http://www.wowwiki.com/Inner_Focus  wowwiki link due to the fact that dm cata does not work and inner focus does not exist anymore on wowhead

https://github.com/Atlantiss/BugTracker/issues/6  >> BUMP

**Comment by TheRealCiapaty** [comment] 2015-02-05 22:15
Confirmed

**Comment by debtheone** [comment] 2015-03-10 16:03
bump

**Comment by debtheone** [comment] 2015-04-07 00:44
bump

**Comment by debtheone** [comment] 2015-05-22 15:00
bump

**Comment by debtheone** [comment] 2015-07-21 07:11
bump

**Comment by Wolffenstein** [comment] 2015-08-03 22:45
Can't reproduce, any ideas?

**Comment by razgal** [comment] 2015-11-06 20:05
@Wolffenstein  here is how you can reproduce it ;)
https://github.com/Atlantiss/BugTracker/issues/4808

**Comment by debtheone** [comment] 2015-11-29 00:25
bump

**Comment by Jenovas** [comment] 2015-12-14 21:59
Fixed in rev 4714

**Closed by Jenovas** 2015-12-14 21:59 UTC
Labels: Class - Priest, Spell - Generic
