### ISSUE TITLE
[EN][QUEST][Westfall][A Vision of the Past] Quest  id: 26320

### ISSUE THREAD

**Issue by seanwow1337** [Atlantiss/BugTracker#4553] opened 2015-09-21 02:16 UTC
[A Vision of the Past] id: 26320 this quest is bugged.. npc no spawned thanks for repair this quest. screen here link: http://oi57.tinypic.com/124bnsh.jpg
wowhead: http://www.wowhead.com/quest=26320/a-vision-of-the-past

**Comment by Pallitax** [comment] 2015-09-21 07:28
Duplicate of #1622.

**Closed** 2015-09-28 11:07 UTC
