### ISSUE TITLE
([EN][Spell][Death Knight] Death Strike)

### ISSUE THREAD

**Issue by SatsumaDK** [Atlantiss/BugTracker#9840] opened 2018-02-10 01:15 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem
I was dueling and suddenly realised that my death strike wasnt healing more after being opened on by a rogue and being close to 20% hp i read the tooltip and seen i should be healed more by death strike depending on how much damage i took in the past 5 seconds.
**Current behaviour**: What happens
death strike doesnt heal for the 20% of the damage you have taken in the past 5 seconds only the minimum of 7% of your max hp
**Expected behaviour**: What should happen instead
after taking a certain amount of damage in the past 5 secs it should heal for 20% of that
**Steps to reproduce the problem**:

1. take a huge amount of damage
2. instantly death strike
3. see you have only been healed for the minimum 7%
![wowscrnshot_021018_011624](https://user-images.githubusercontent.com/36317230/36056869-0dcc8148-0e00-11e8-9887-3a9fe1865281.jpg)

![wowscrnshot_021018_004557](https://user-images.githubusercontent.com/36317230/36056814-9906b1bc-0dff-11e8-872f-41f6673a696c.jpg)
![wowscrnshot_021018_004522](https://user-images.githubusercontent.com/36317230/36056841-dab91528-0dff-11e8-9cf5-fb9fcfafeb00.jpg)

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by pelekon** [comment] 2018-02-11 01:29
I wirte sth cuz Satsuma aked to do so

**Comment by Piklo** [comment] 2018-07-04 20:30
cannot reproduce

damage taken from last 5 sec
19137+49207+19139+19138+49201 = 155822
155822*0.2 = 31164,4

22:13:20> Dkk's Death Strike heals Dkk for 0.(31164 Overhealed

![image](https://user-images.githubusercontent.com/16057987/42293313-938ba9c6-7fd9-11e8-879b-38eecafd961c.png)

**Comment by Piklo** [comment] 2018-07-04 20:56
seems to dont work with dots

dmg from last 5 sec
42907+61950+53633 = 158490
158490*0,2 = 31698

22:46:25> Dkk's Death Strike heals Dkk for 0.(10863 Overhealed)
![image](https://user-images.githubusercontent.com/16057987/42293862-69b25a60-7fdd-11e8-8b89-5547c9740c23.png)

**Comment by Piklo** [comment] 2018-07-17 14:01
seems like i fixed it on my local
```
15:50:59> Dkk suffers 70090 Shadow damage from Lock's Unstable Affliction.(7787 Resisted)
15:50:59> Dkk suffers 43151 Shadow damage from Lock's Corruption.(10787 Resisted)
15:51:00> Dkk gains 113241 Health from Dkk's Uber Heal Over Time.(30416 Overhealed)
15:51:02> Dkk suffers 77877 Shadow damage from Lock's Unstable Affliction.
15:51:02> Dkk suffers 48545 Shadow damage from Lock's Corruption.(5393 Resisted)
15:51:03> Dkk gains 126422 Health from Dkk's Uber Heal Over Time.(17235 Overhealed)
15:51:03> Dkk casts Death Strike at Lock.
15:51:03> Dkk's Death Strike hits Lock for 10101 Physical.
15:51:03> Dkk casts Death Strike.
15:51:03> Dkk's Death Strike heals Dkk for 0.(47932 Overhealed)
```
70090+43151+77877+48545)*0.2 = 47932.6

**Comment by Piklo** [comment] 2018-07-31 15:41
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/18547-9840-death-strike-spell_proc_event/

**Comment by Piklo** [comment] 2019-02-02 18:46
should be fixed in rev. 5923

**Closed by Piklo** 2019-02-02 18:46 UTC
Labels: Class: Death Knight, Spell
