### ISSUE TITLE
[EN] [PETS] Death Ravager Untameable

### ISSUE THREAD

**Issue by Sthibodeaux** [Atlantiss/BugTracker#4624] opened 2015-10-05 00:03 UTC
as of patch 4.0.6, the 'Death Ravager' on Azuremyst Isle (http://www.wowhead.com/npc=17556/death-ravager#drops) gets a new green and turquoise, unique color scheme, and becomes tameable by hunters. I would very much like to have this guy as my pet like back in retail :)

**Comment by aje** [comment] 2015-10-05 07:27
duplicate of https://github.com/Atlantiss/BugTracker/issues/4590

A fix by a content fixer has been posted for this issue. Wait some time and it will be effective on the server.

**Closed by aje** 2015-10-05 07:27 UTC
