### ISSUE TITLE
[EN] [Druid] [Spell] Auto Attack (Feral Druid)

### ISSUE THREAD

**Issue by Iambugged** [Atlantiss/BugTracker#1725] opened 2015-01-21 17:05 UTC
I don't know what is causing it but sometimes Feral Druid Auto Attack gets bugged. It just all of a sudden gets inactive and clicking Auto Attack or macro with "/startattack" won't start it. I have tried all my Feral abilities (got /startattack macroed into everything) but seems only casting Shred and Feral Charge (Bear) will start the auto attack again. Of course it also fixes with a relog but if it happens in the middle of a battleground I'm screwed.

**Comment by kadi2** [comment] 2015-01-21 18:32
Experianced this only few times, guess it's hard to reproduce.

**Comment by Kuszki** [comment] 2015-01-21 20:51
On my hunter i had experience with autoshot stuck. It was produced when i spam healy hard some spell while casting aimed shot. Now i didnt notice anything like that, and i had never notice autoattack stuck in druid.

Try to spam some spell very hard while charge or something there is a chance to reproduce it this way.

PS while it was buggen on my hunter all i had to do to fix it was drop my target, reselect the target and enable autoattack again.

**Comment by Iambugged** [comment] 2015-01-21 21:10
Tried the re-targeting, sometimes it works, sometimes doesn't, either way it will instantly get bugged again once I switch to another mob/player and will continue to do so until I relog.

**Comment by Kuszki** [comment] 2015-01-21 21:16
Check if you have this option checked:
![wowscrnshot_012115_221544](https://cloud.githubusercontent.com/assets/6035437/5845294/31a9bd2e-a1bb-11e4-8bc0-83799751829f.jpg)

**Comment by Iambugged** [comment] 2015-01-21 21:17
It's off, should I have it on?

**Comment by Kuszki** [comment] 2015-01-21 21:21
No, it stops your autoattack if you switch the target. I just thought you have it checked and it may cause your problem. Did you try to disable your addons and then check if it help? It seems stupid but who knows?

**Comment by Kuszki** [comment] 2015-01-21 21:26
Im trying very hard - spamming buttons, charging, switching targets rtc - and i cant force my druid to make autoattack hang.

**Comment by Jenovas** [comment] 2015-01-27 17:08
Cant reproduce the bug. Closing.
Once you know how to bug it for 100% and know it's a bug please report again.

**Closed by Jenovas** 2015-01-27 17:08 UTC
