### ISSUE TITLE
[EN][Quest] BadlandsThe Day that Deathwing Came: What Really Happened

### ISSUE THREAD

**Issue by martinelrey1979** [Atlantiss/BugTracker#4286] opened 2015-08-18 01:13 UTC
It fulfills the mission is not whatever you do please verify
http://www.wowhead.com/quest=27715/the-day-that-deathwing-came-what-really-happened

**Comment by Pallitax** [comment] 2015-08-18 06:45
Duplicate of #1358

**Closed** 2015-08-18 11:20 UTC
