### ISSUE TITLE
[Shaman][Restoration][Talent] Ancestral Vigor bug at Baleroc

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#8419] opened 2016-10-18 00:09 UTC
That talent bug at Baleroc!
it gave my Tank approximatly 2 to 4m health bonus to my Tank.

We did alot of tries on Heroic Baleroc.
everytime my Tank health goes to 5m 6m 7m even one time we had 11m!
(11m caused of Rally Cry also)
my hardest heal done was 1.08m

1.08m is high amount of heal, but when your tank have 11m
it equals to 10% of his health.
you can't no matter what bring a tank to above 90% with that amount of health.

I watched enomorous PoVs of Tanks and Healers against Baleroc HC.
And I never watched an Tank with more than 2.5m health.
Also the heals on those videos by healers are around 250k to 750k at max (not include ticks)
and those heals are enough to bring a Tank to maxium health before Decimation Blade
and also after Decimation Blade.

Today we did more few tries on Baleroc Heroic.
Till I found out that bug.

Than I told our Tank
to add his rotation a /cancelaura Ancestral Vigor

example:
/cast Death Strike
/cancelaura Ancestral Vigor
also for every ability he does!

And everytime he canceled the AVigor his health just was fine and healable.
so please fix it.

Btw im not sure if the Ancestral Vigor cause it, but you must check it out.

Screenshots:
http://oi66.tinypic.com/2q226ft.jpg - normal without Ancestral Vigor / Rally Cry
http://oi64.tinypic.com/16m3h37.jpg - 11m health.

I know there is alot differences between 18x Glory to 32x Glory.
but come on, 11m health is not healable. you can't no matter what to bring your Tank to 90-100% health.

**Comment by Aival94** [comment] 2016-10-18 12:52
As far as i can understand Blaze of Glory normally is taking the base health of the tank and increase it by 20% each stack. Furthermore the tank when had 11m had also Rallying cry which increase Current life by 20% and Vampiric Blood which increase the Current health by 15% so is possible for sth about these spells to reach the amount of life somehow. If you can check the base life of your dk tank and make the calculations gonna be better i believe.

**Comment by Illusie** [comment] 2016-10-18 21:09
@Aival94 I know how Blaze of Glory works.
the issue is the Tank health when Restoration Shaman healing and Health increase buffs.

I recommend you to do what I did and watch 10-15 videos of Tank Pov and Healer Pov
and look specially at end-fight of those videos.
And tell me what the Health amount the Tank have.

I really watched like 10-15 videos, even from our server and never seen an Tank with more than 2.5m health, my Tank just got 5m 6m 7m and 11m its not healable.

https://www.youtube.com/watch?v=S5GjNGiN-b4
look at that video for example. tank 30x blaze of glory = 1.4m health.

https://www.youtube.com/watch?v=eF2NkjnjTsI
and this one 1.5m health

https://www.youtube.com/watch?v=FVz_4SuUdEM
1.3m

and you can keep going on and on.

**Comment by kadi2** [comment] 2016-10-19 08:00
I'd suggest you to play for a while with Bear form and Anscentral Vigor for a while. Didn't test it personally but someone mentioned base HP. Base HP is just 20-25k HP at 85 level at 0 stamina. As we know Anscentral Vigor snapshots it's maximum cap in the moment when the first Anscentral Vigor buff is applied.

**Comment by Illusie** [comment] 2016-10-19 14:59
@kadi2 I'm not the tank I was there as healer (Resto Shaman healer)
It does not matter if the tank is Druid or DK.

The matter is my Tank have 4-11m health, which is not as it should be.

We end the fight with 182k hps+absorbs (total)
http://oi66.tinypic.com/35asy39.jpg

I saw videos when Holy Paladin solo heal it with 65k hps.
I had 202x Spark stacks.
I saw videos when 100x spark is enough.
I double every parameter in this fight.

Something is not working as it should.
Something about Resto shaman healing vs Baleroc.
and also something about HP increase buffs vs Baleroc.

I hope to see a fix or tests asap.
It's pretty make Resto Shaman unfriendly to this encounter.

**Comment by RobiD2** [comment] 2016-10-20 09:48
"We end the fight with 182k hps+absorbs (total)"
I kill Baleroc HC on DKs(main/alts) tanks 1 healer/2healer.Dmg is rng and most of kills total healing/apsorb <70k overall but some kill req.180k+ .Most of kills ar done with shaman healer and never got any issue.Stacking HP cd/using non glyphed VB can be isssue and overall rlly bad idea for Baleroc.

**Comment by Illusie** [comment] 2016-10-20 13:05
@RobiD2 No, most of the fights dont require more than 70k hps, I mean pure heal.
We already did it with Disc priest solo heal with that same tank. > http://i.imgur.com/pSzSHXO.jpg

Infact I stood on 70k hps (pure heal) cause Resto shaman haven't Absorbtion.
so if I'm at 70k hps, and in Retail video Holy Paladin can solo heal it with 64.5k hps
And we can't heal the tank to full health on the last Decimation Blade.
It caused our tank die few times 10-15 sec before Enrage timer.
It means we lost 10-15 seconds that tank could be alive before he Enraged.
that means he will still target tank and not random people.
those 10-15 seconds are crucial.


About the 11M ok ok.. leave it behind. I know it was cause of Vampire Blood and also cause Rally Cry.
tbh the Rally Cry is been used cause warrior took shard and almost died cause we couldn't bring Tank to full health. we both focused the Tank and almost ignored the sharder.
VP is been used to increase our Heal done cause we couldn't bring him up.
But let's say i'm agreed, the timing was bad. ok?

Explain me how any tank can get more than 2.5m health?

You & other are completly ignored that I mentioned that my tank health goes "4m, 5m, 6m..." 
Believe me even 3m-5m health is weird without any HP increase buff.
why it's weird? because my comment refered to Avial94. I posted like 5 videos from YT
PoV Tanks and those tank health never went higher than 1.5m.

**Comment by Aival94** [comment] 2016-10-20 14:47
I just said to make some calculations or try to check what exactly can bug it because it might even be the Vampiric Blood or the Rally Cry. I am not saying is normal to have this hp but still seems the buff of Baleroc is a little buggy about the health it should give i believe but if i do not know base max health i cannot tell for sure.

**Comment by RobiD2** [comment] 2016-10-20 15:02
Its hard to say what combination of buffs make HP go wild but in our main raid i never got any problem with Anscentral Vigor.Dying from DB in 10man is shame for any DK tank and that is simple player fail.What buff tanks use on retail in 4.2 have nothing with 4.3 DK on ATS.

**Comment by Illusie** [comment] 2016-10-20 15:36
@Avial94
@RobiD2 

I made the calculations and watched videos from 2011.
the cause is probably the Anscentral Vigor.

If you watched 
https://www.youtube.com/watch?v=eF2NkjnjTsI

that DK use Stamina Flask and use 3 times VB during the fight
1:40, 4:03, 5:16
his health remains the same.

so please >.< ...

**Comment by RobiD2** [comment] 2016-10-20 15:40
http://cata.openwow.com/spell=58676    
EoD

**Comment by Illusie** [comment] 2016-10-20 15:56
@RobiD2 
I know about that glyph and I don't play a DK.
I assume our DK is not a pug DK. and he probably know and used this glyph during the fight.
I will check out.

Anyway, you still stuck at that "11m" shitty screenshot I posted.
Let me quote myself:
"You & other are completly ignored that I mentioned that my tank health goes "4m, 5m, 6m..." 
Believe me even 3m-5m health is weird without any HP increase buff." - Illusie 7#

**Comment by Illusie** [comment] 2016-10-21 14:31
*This comment refered by the DK of my group
- go kill yourself.
- you did not even checked the videos, and you have such a low iq. you commenting randomly without checking things out.
- I used VP glyph.

**Comment by Kejmil** [comment] 2016-10-21 15:22
@everyone
#manybump=nofix

**Comment by kadi2** [comment] 2016-10-21 15:29
@mongoloids You didn't post any useful info. Everyone knows it's bugged. The time you spent on spamming retarded comments here you could spend on doing something towards explaining how it should work:
1.Should it scale with Stamina from Gear?
2.Should it scale with stamina from buffs?
3.Should it scale with % HP increases?
4.Should the maximum HP cap snapshot or scale dynamically?


@Illusie I told you to play with bear form just because bear form increases your health by 8%. It's the fastest way to test if you can stack HP endlessly by abusing the bug.

**Comment by lamaATS** [comment] 2016-10-22 00:44
Please stop using @ with all devs. Sorry but it's annoying and I will close and lock issues because I know that you think your issue is more important then other but maybe it's not important for other people.

**Comment by Illusie** [comment] 2016-10-23 01:21
Hey yoo,
Thank you lamaATS. yeah sorry I was a bit retard for spaming "@" ^^
but I report it 7 days ago  (4  here, 3 personal to some dev). this is the first reason.
the second reason is  I wanted to check it out if that "@" works xD.. (I'm amateur with all what GitHub site can do)

kadi2 - I cant test it whenever i want, cause our raid-time, I need everyone online and that.
also I can say that with another group I run FL hc, we using Feral tank but healers are Priest & Holy we haven't that issue. that why I assuming the problem causes by Shaman ability.
I don't even think the cause is Rally Cry we use and used the ability everytime.

kadi - we tested it today with Feral tank, and it's cause of Anscentral Vigor.
seems like Ancentral Vigor has no limitation for it HP increasing, and on Baleroc your Tank health always go up, meanwhile cause of Anscentral Vigor it go up aswell. make you end with 3m+ health on tank.

We had lucky that our holy paladins could solo heal-it. but It's pretty sad that Restoshaman is unfriendly now with that boss. It make us formation changes. 

Btw, for everyone who told me to check it out myself. I have to say sorry, I'm not here to check things by myself, all what I can to do is report when I see things that make no sense to me.

so again, Thanks for label it, I hope to see a fix soon, maybe Anscentral Vigor limitation, Like you did with Ignite.

**Comment by lamaATS** [comment] 2016-10-23 12:36
The problem is like You said:
`Anscentral Vigor limitation go up`

Currently I'm unable to find any proof how it should scale but to fix it I will limit to amount to % of maximum health in moment of first buff application (not refresh). So to get more health with stack of Blaze of Glory You will need to expire `Anscentral Vigor` from the target and apply it again. I know it's not perfect solution and probably not blizzlike.
I will fix it when I will find some free time.

p.s. `For everyone who told me to check it out myself. I have to say sorry, I'm not here to check things by myself, I'm not dev xD.`
You can do here what You want but if You will test something and find some proofs You can reduce time of validation where is the problem and reduce time to fix the problem because when I know what to do in most cases it's just a several minutes to fix and I know sometimes You are totally unable to test something.

**Comment by Aival94** [comment] 2016-10-23 15:02
@lamaATS really not sure how it get bugged but on friday i healed as shaman one druid and one warrior on Baleroc HC and did not have such a problem(Warrior tank with 20 stacks had around 1.5 million).

Is a general issue with Anscentral Vigor and tanks or is just with DKs as is strange for me not being like that.

**Comment by lamaATS** [comment] 2016-10-23 15:24
I spent some time after I wrote last comment and I saw buffs which increase health by % but buff like `Rallying Cry` which in description has % but in real it's static amount of health (calculation on cast), so buffs which increase health by % will be excluded and don't worry about Druids it's will be only specific aura type and all player's buffs will not be affected by this. (it's hard to explain exactly but trust me it will work properly)

**Comment by Aival94** [comment] 2016-10-23 17:05
ok nice :)

**Comment by lamaATS** [comment] 2016-10-23 21:39
With 147k maximum health and 30 glory stacks after fix I was able to get maximum 103k bonus health from vigor and my total health was 1,75M so vigor will still increase health from `Blaze of Glory` but will no longer stack to infinity.

**Comment by lamaATS** [comment] 2016-10-23 21:51
Fixed in rev. 5224

**Closed by lamaATS** 2016-10-23 21:51 UTC
Labels: Class - Shaman
