### ISSUE TITLE
[EN][Gilneas][Quest] Grandma's Cat

### ISSUE THREAD

**Issue by Kastron** [Atlantiss/BugTracker#4406] opened 2015-08-30 21:34 UTC
Everything worked fine until I approached the cat - then I crashed. The bigger problem here is that when I tried to log in I crashed again, over and over, therefore I had to use my unstuck option from the website. I can't progress any further from this point and my character is stuck at Gilneas newbie area. I'm using the bit.torrent version.

**Comment by Zerthion** [comment] 2015-08-30 21:37
I'm also having the same issue. I tried a client on my Laptop and PC. I can no longer play since I ran out of vote points to unstuck. 
IGN: Varentain  (Stuck Worgen) used the Torrent version + Mini

**Comment by Avalain** [comment] 2015-08-30 22:01
I never had this problem - always using Mini Client from Web Site.
Made many worgens, never had  crash there.

Many people seems to complain on torrent version, try using only Game Client (mini), remove previous instalment and just launch freshly unpacked exe from Client.
Could also be that I'm using Windows XP.

**Comment by Zerthion** [comment] 2015-08-30 23:12
I just tried it on a PC & Laptop. Both the torrent version and fresh Mini Client version. No Change. I'm using Windows 7 on the laptop and Windows 10 on the PC. Both PC's have a fresh install of OS.
I have tried Windows XP compatibility but no luck....

This application has encountered a critical error!
ERROR #132 (0x85100084) Fatal exception!
ProcessID:	3892
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:00595487
The instruction at "0x00595487" referenced memory at "0x00000028".
The memory could not be "read".

**Comment by Pallitax** [comment] 2015-08-30 23:34
Duplicate of #3697

**Comment by Zerthion** [comment] 2015-08-30 23:39
It has not been acknowledged for 2 months

**Comment by Avalain** [comment] 2015-08-31 08:36
Some people say it worked for them: 
Go to Options -> Advanced, there find Graphic API and change to DirectX9
Make sure your graphic driver is optimised for your laptop (most recent update crash me to blue screen, so I'm using drivers provided by my laptop producer).

Also make sure there are no addons turned on.

Restart whole WoW application, check if problem still occurs.

In worst scenario better to contact GM in game on different character and ask for autocomplete said quest so you can carry on with your chain.

**Comment by Kastron** [comment] 2015-08-31 16:53
Thanks for response, I'll try both of that.

**Comment by Kastron** [comment] 2015-08-31 17:03
I turned off the one add-on I had (the dps one ) and changed from DirectX11 to DirectX9 and that solves the problem, once again thanks for the help.

**Closed** 2015-08-31 18:59 UTC

**Comment by Zerthion** [comment] 2015-09-01 01:17
I did not have any Add-on's. I did change from DirectX11 to DirectX9. I did not receive the error anymore. Thanks Avalain!

**Comment by Avalain** [comment] 2015-09-01 16:10
Always happy to help, enjoy your time on Atlantiss!

**Comment by tiagodisouza** [comment] 2015-09-16 01:23
I attempted all the fixes shown here and it did not work
