### ISSUE TITLE
[EN][Hunter] Auto Shot vs. Cobra Shot / Steady Shot

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#6280] opened 2016-02-07 01:18 UTC
With the rev. 4878 "Auto Shot will no longer be casted when casting other spells" auto shot isn't casted when casting cobra shot/steady shot.

Your auto shots should be able to be casted while casting steady shot/cobra shot
https://youtu.be/3X2hJS1bSJs?t=5m1s  PROOF

**Comment by xolon** [comment] 2016-02-07 01:48
same for aimed shot

**Comment by BialyADI** [comment] 2016-02-07 03:25
Now I see Warrior Slam have the same problem ;o.

**Comment by aneq** [comment] 2016-02-07 04:08
@BialyADI working as intended,
slam and aimed shot are supposed tu supress auto shot/auto attack
steady and cobra however, not so much

**Comment by lqlq32** [comment] 2016-02-07 07:35
You CAN cast auto-shots during cobra/steady shots. but NOT during aimed shots, right now you bugged the hunters. Which mean less auto shots because cobra/steady interupt your autoshot timer. 


 Patch 6.0.2 (14-October-2014): Aimed Shot no longer interrupts Auto Attacks

But i have something to ask:
Cataclysm-Logo-Small Patch 4.0.6 (8-Feb-2011): the base cast time has been reduced to 2.4 seconds, down from 3
This is a known bug from retail, they did a mistake and reduce the cast time to 2.9 sec instead of 2.4 and was fixed in early MoP, Should we have 2.9s aimed right now or 2.4?
http://us.battle.net/wow/en/forum/topic/2046965590
http://us.battle.net/wow/en/forum/topic/2065787501
http://eu.battle.net/wow/en/forum/topic/1695060664
"I spoke to a Gm yesterday and he said that indeed was a bug and it is supposed to be 2.4."

This cloud make MM again playble. I would love an answer from GM.

**Comment by Bastek** [comment] 2016-02-07 09:04
Fixed in rev. 4879

**Closed by Bastek** 2016-02-07 09:04 UTC

**Comment by BialyADI** [comment] 2016-02-07 09:28
What about Warrior Slam?

**Comment by Kejmil** [comment] 2016-02-07 11:03
slam is working as intended already

**Comment by aneq** [comment] 2016-02-07 14:23
@lqlq32
http://us.battle.net/wow/en/forum/topic/2136234168
the 0.5 difference is supposed to be "hidden". I guess it's not hidden here
