### ISSUE TITLE
[EN][Quest][Zone] Time for Answers (Horde)

### ISSUE THREAD

**Issue by OvanSan** [Atlantiss/BugTracker#9820] opened 2018-02-02 08:17 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Missing NPC **Matthias Lehner**. Probably because it is wrong phase.

**Current behaviour**: Missing NPC, Quest is unavaliable to complete.

**Expected behaviour**: NPC Should stand on the crossroad.

**Steps to reproduce the problem**:

1. Take Quest **Time for Answers**
2. Fly to point.
3. 

**Revision**: 5612

http://www.wowhead.com/quest=13360/time-for-answers

**Comment by TranceAccount** [comment] 2018-02-02 19:11
And the phasing issue is probably caused by a wrong quest chain.

**Comment by OvanSan** [comment] 2018-02-07 11:14
It's possible to get Quest Reward. After server restart you cannot take Tournaments Daily Quests. Then the phase is correct and you are able to see NPC.

But after Quest [Tirion's Gambit](http://www.wowhead.com/quest=13403/tirions-gambit) there is no more Quests. What's wrong ?

**Comment by tomatosz** [comment] 2018-02-07 16:50
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/18176-npc-matthias-lehner/

**Comment by tomatosz** [comment] 2018-02-26 00:04
Fixed in rev. 5645

**Closed by tomatosz** 2018-02-26 00:04 UTC
