### ISSUE TITLE
[EN][Spell][Shaman]  lava surge

### ISSUE THREAD

**Issue by Oldsylar** [Atlantiss/BugTracker#9028] opened 2017-03-16 18:37 UTC
# **Description**:my lava suge procs mostly when lava burst is out of cd, so i can cast lava  and dont need lava surge, it should proc only when lava burst  is on cd to reset it, if it does w lava out of cd it doesnt reset a damn thing.
(i came from mop retail and a similar lava surge procs only when lava is on cd ) it s really stupid elsewise

**Current behaviour**: lava suge procs mostly when lava burst is out of cd

Expected behaviour: it should proc only when lava burst is on cd

# Steps to reproduce the problem:
just cast lava at dummy and see when lava surge procs

[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Illusie** [comment] 2017-03-16 19:21
It already reported and its not should work like its work on MoP.

**Comment by Oldsylar** [comment] 2017-03-16 20:39
just tell me the reason why a spell that has to reset cd it doesnt reset cd, it doesnt work exactly like mop but has the same meaning which is to reset cd not to do nothing

**Comment by Jenovas** [comment] 2017-03-16 23:39
Not a bug. Closing.

**Closed by Jenovas** 2017-03-16 23:39 UTC

**Comment by Illusie** [comment] 2017-03-17 10:44
@Oldsylar Yeah believe me I know your feeling.
I thought the same because on my Druid if im casting Starsurge and get Proc I still can shot it.
and on Lava Surge I cant the cd get locked to next 7 sec.

Blame atlantiss. It's not a bug in Cataclysm. video proof it.. try find a better proof that it should work like you said and I'll be the first to support it.
