### ISSUE TITLE
[EN][Core][Stats] Hit rating and Spirit rating do not give equiv spell hit rating values

### ISSUE THREAD

**Issue by whatisthisthing** [Atlantiss/BugTracker#8633] opened 2016-12-01 05:33 UTC
**Description**: Describe the problem
When reforging Spirit into Hit you mysteriously lose a few values of hit rating

**Current behaviour**: What happens
When reforging Spirit to Hit you lose small amount of hit values

**Expected behaviour**: What should happen instead
When reforging Spirit to Hit you should get same values before and after

**Steps to reproduce the problem**:

1.  Check spell hit rating before reforging (exact value and percentage)
2.  Reforge spirit to hit on a class that gains hit rating from spirit (elemental shaman, shadow priest, balance druid)
3.  Check spell hit rating again to see that the values have changed 1-2 spell hit rating

**Revision**: Current server version
5263

**Comment by whatisthisthing** [comment] 2016-12-01 05:37
Essentially hit rating is worth ~98-99% as much as spirit. Switching 100 spirit to hit grants 1 less spell hit rating.

**Comment by Jenovas** [comment] 2016-12-02 14:16
Did you have any buffs that increase spirit? For example king / wild / any talents that increase spirit by a %.
That would cause 100 spirit to not be equal to 100 hit.

**Comment by fluessig** [comment] 2016-12-04 10:10
ever since cataclysm kings doesnt buff spirit
its only agi str int and stamina
i double checked, it works correctly on atlantiss

**Comment by whatisthisthing** [comment] 2016-12-04 19:25
No player buffs give hit/spirit and no hit buffs were consumed. Only change between results was reforging spirit to hit.

**Comment by whatisthisthing** [comment] 2016-12-09 01:39
@Jenovas @pelekon 

here's a video showing exactly what's happening.

https://www.youtube.com/watch?v=0NsMH6qmEHI

**Comment by whatisthisthing** [comment] 2016-12-12 00:28
Confirmed this issue is occuring on not only Balance druids, but also Shadow priests.

Balance druid talent: Balance of Power (couldn't find link)

Shadow priest talent: http://wowwiki.wikia.com/wiki/Twisted_Faith

**Comment by Jenovas** [comment] 2016-12-28 18:49
So I had a look at this bug and it seems that the spirit calculation is wrong.
If you look at your video you can see the same thing, during reforge it showed that you will gain 120 spirit but if you look at your spirit value it went up by 121. So this is the cause of your hit chance being different.

**Comment by zorix** [comment] 2018-04-05 16:44
Fixed in rev. 5725

---
lama aka zori

**Closed by zorix** 2018-04-05 16:44 UTC
Labels: Content: Cata, Core Mechanic, Low Priority, Status: Confirmed
