### ISSUE TITLE
[EN][STATS] Stat bonuses must be multiplicative

### ISSUE THREAD

**Issue by metaldoctor** [Atlantiss/BugTracker#6255] opened 2016-02-05 17:20 UTC
Hello.
I checked my dk and druid for bonuses from talents, passives, abilitys and buff.
In #6233 we had discuss about how its works.
> On our server all stat bonuses are additive. If you have any proof that it shouldnt plz make a report with the proof.
> 
> Closing.

**Part one.**
I find proof how it must works.http://www.youtube.com/watch?v=dLvqKULmwBw - its video, in description on it u can find link for vidio author armory (video from retail 4.3.)
At ~0.55 you can see, he had 4334 str. At ~2:40 he started switching in blood from frost. After it in blood he have 4049 str.
Math part: Frost dk have talent to up str by 4%, and his plate special up str for 5%. In blood he had talent for 2% of str.
How calculate str:
Add way: 4334 / (1.09) * 1.02 = 4055.669725 => it will be rounded for 4056 or 4055?
Mult way: 4334 / (1.05) / (1.04) * 1.02 = 4048,24175824.

Closes value for his 4049 is 4048,24175824. Then its work for mult way.

**Part two.**
At proof in 1st video he said what gear he have. You can see it on the video. Then we can calculate Str from it (Calculate str because you can have it from base stats, gear, food, potion and buffs only. No one gathering proff add it).
Gear in Video:
Hands: 322 (T12 hc)
Belt: 282 (FL rep)
Legs: 368 (T12 nm)
Boots: 266 (magmaw hc)
Ring1: 175 (FL rep)
Ring2: 214 (Tot4W hc Permafrost_Signet of the Rockslab)
Relic: 128 (VP one nm)
Weapon: 408 (shannox normal)
bracers: 286 (DS hc)
chest: 420 (T12 hc)
Back: 173 (FL rep)
Shoulders: 255 (Ragna hc)
Neck: 229 (BoT sinestra)
Head: 250 (T12 nm).
Total str from gear: 3776.
Orc have base str 193. Then with gear and base it will be 3969.
Add way: 3969 * 1.09 = 4326. Less then 4334? yeah.
Mult way: 3969 * 1.05 * 1.04 = 4334.148. Equal with 4334? yeah.

**Part three.**
I found guide for Holy paladin in 4.3.4 (http://manaflask.com/en/guides/404)
It says

> Intellect
Intellect is by far the most useful stat for a Holy Paladin. It increases our spell power, mana and crit chance. Intellect increases the mana we gain from spirit as well as the mana we gain from spells that are based on our total mana such as Replenishment, Divine Plea and Arcane Torrent.
With 5% Plate Spec, 5% Kings, and 10% Spellpower buff, 100 Int will provide (assuming all regen abilities used on cooldown):
* 1653.75 Maximum Mana.
With out any buffs talents and bonuses 1 intellect give you 15 mana. How you can have 1653.75 mana from intellect? Its good question.
Math for 100 intellect:
Add way: 15 * 1.1 * 100 = 1650.
Mult way: 15 * 1.05 * 1.05 = 1653.75.

**Comment by lqlq32** [comment] 2016-02-05 17:27
I am pretty sure they are.

**Comment by metaldoctor** [comment] 2016-02-06 07:24
Its not close enough.
At druid i have 156 int with out gear and spec.
With gear and no spec i have 5444(5228 from gear).
In restor spec i have talent for 6% intellect. I have 6042 intellect, but it must be 6059. Then if i will buff my self it will be 6315, but must be 6362. Difference is 47 intellect.
Math:
With out buffs:
5444 * 1.11 = 6042. Nice math.
5444 * 1.05 * 1.06 = 6059.172
Screenshots:
![wowscrnshot_020616_101107](https://cloud.githubusercontent.com/assets/2743430/12865325/f56db826-ccb9-11e5-9781-38f26707747f.jpg)
![wowscrnshot_020616_101100](https://cloud.githubusercontent.com/assets/2743430/12865326/f5714f5e-ccb9-11e5-8fca-a13ae5e91c40.jpg)
![wowscrnshot_020616_101050](https://cloud.githubusercontent.com/assets/2743430/12865327/f57728de-ccb9-11e5-90d0-1a07dbaff563.jpg)
![wowscrnshot_020616_101044](https://cloud.githubusercontent.com/assets/2743430/12865328/f57c05f2-ccb9-11e5-8edd-95078bd9ba19.jpg)
For hunters same.
No Spec.
Base agility 209 (210 if make relog).
![wowscrnshot_020616_101910](https://cloud.githubusercontent.com/assets/2743430/12865390/4955ecfa-ccbb-11e5-8c96-7f200dae7279.jpg)
Equip gear 5224 (Base agility + gear agility only)
![wowscrnshot_020616_101916](https://cloud.githubusercontent.com/assets/2743430/12865393/62f33726-ccbb-11e5-8b41-a25e293834ce.jpg)
Respec for survive. Make math: 5224 * 1.1781 = 6154. 
Screenshot says 6113 (6113 / 5224 = 1.1701 - because in game all stats rounded)
![wowscrnshot_020616_101916](https://cloud.githubusercontent.com/assets/2743430/12865401/8218047e-ccbb-11e5-8cb6-e3dc8b7bf0fc.jpg)

**Comment by lqlq32** [comment] 2016-02-06 07:52
Well if ur agiliy is 5224 then ur % will be lower because that was my agility without 5% bonus from the gear. I just SUM all of the agiliy from the gear by hand. So i am pretty sure u are doing it wrong.

**Comment by metaldoctor** [comment] 2016-02-06 08:02
No Spec, no talents. Remove one mail item. I remove boots, see how much agility you have.
![wowscrnshot_020616_105902](https://cloud.githubusercontent.com/assets/2743430/12865570/dd6e919e-ccc0-11e5-851e-06d59796f277.jpg)
Boots give: 281 + 10 + 40 + 35 = 366. Then 5224 - 366 = 4858.
![wowscrnshot_020616_105853](https://cloud.githubusercontent.com/assets/2743430/12865571/dd74de82-ccc0-11e5-8fd9-a1d65a115c7f.jpg)
Then 5% bonus dont working when you dont have spec. Where i take extra agility?

**Comment by lqlq32** [comment] 2016-02-06 08:10
Can u sum all of ur gear agility? WIthout watching the tooltip?

**Comment by metaldoctor** [comment] 2016-02-06 08:22
I make calculation, all gear give me 4945 agility and 70 agility bonus (2S10 head + shoulders) => 5015, with base agility it will be 5224 (5225 after relog, i dont know why its wrong after respecs).

**Comment by lqlq32** [comment] 2016-02-06 08:29
How much tottal agility u have nonbuffed on survival spec?

**Comment by metaldoctor** [comment] 2016-02-06 08:33
I said it before, 6113.
![wowscrnshot_020616_113224](https://cloud.githubusercontent.com/assets/2743430/12865720/57f23c8c-ccc5-11e5-8da0-a3038543f5c7.jpg)

**Comment by lqlq32** [comment] 2016-02-06 08:56
Well i dont know what is behind the scripts but i still think its fine, will check again later with 5% buff.

**Comment by metaldoctor** [comment] 2016-02-06 10:08
@lqlq32 Can you post screenshots?
With out Mark of the wild 6113 agility, with 6374.
Math: 6113 * 1.05 = 6418. If 6418 = 6374 then its working good.
![wowscrnshot_020616_130504](https://cloud.githubusercontent.com/assets/2743430/12866109/86ffd40a-ccd2-11e5-873f-f78b534b1c60.jpg)

**Comment by lqlq32** [comment] 2016-02-06 11:09
So without spec i have 5718 
5406 from gear and base + 5% from mail spec 
but 5406 * 1.05 = 5 676.3 = 5677 agility. 
So i guess there is something wrong overall. But with more % gain different is lowered and specially for survival its a agility loss.

**Comment by aneq** [comment] 2016-02-07 04:01
the problem is  you count base agility which is not counted.

**Comment by lqlq32** [comment] 2016-02-07 07:18
Well 5196 * 1.05 + 210 = 5 665.8 still not 5718.

**Comment by ponpontos** [comment] 2016-02-08 20:57
I see no reason for base stats not to be multiplied by bonuses, and even if that was the problem, the maths wouldn't check out. The thing here is that stat multiplication isn't stacking. 

And as I said in my ticket, the whole affair seems really counter-intuitive. I'm almost sure that in retail PoF did simply 1.2x the total value of strength in the character panel. Why would it ever work in any other way?

Not to mention that every single spec in the game seems to be doing way lower dps than on retail or other cata private servers. Like, 2-3k dps less.

**Comment by ponpontos** [comment] 2016-02-08 20:59
But then again, with bugs such as ignite banking not properly working being labelled as "minor priority" it doesn't surprise me in the least. God knows how many actual minor class bugs there are.

**Comment by lamaATS** [comment] 2016-10-27 10:08
Fixed in rev. 4910 (missing close)
Part of commit message about this:
`Now some additive bonuses will be multiplicative as should be`

**Closed by lamaATS** 2016-10-27 10:08 UTC
Labels: Core Mechanic
