### ISSUE TITLE
Remove Course

### ISSUE THREAD

**Issue by joker1292** [Atlantiss/BugTracker#9001] opened 2017-03-09 14:05 UTC
This spell [http://cata.openwow.com/spell=475] works good.but it is have 1  problem is that when you have nothing to dispel it works the same, instead of having no course, should not work to say (nothing to dispel) instead always dispel.
Same for the Spellsteal [http://cata.openwow.com/spell=30449] the mage, the spell works works even when there is no magic to steal. when there's nothing to steal should tell you (nothing to dispel) instead always works.

I noticed that this problem exists even with the dispel magic of the priest and I think with all the spells that remove disease / poison / magic/course # # **etc.**

check please

**Comment by TranceAccount** [comment] 2017-03-09 15:15
# Please follow our _How to use?_: 
https://github.com/Atlantiss/BugTracker#how-to-use

Thanks in advance.

**Comment by blinkmaster** [comment] 2017-03-09 17:45
check cataclysm patchnotes. 

close this shit, its not a bug.

**Comment by joker1292** [comment] 2017-03-09 20:01
@blinkmaster I do not know if what you say is true, but since you are the strongest player and inteligent this server,(ironic) link me this  pacth notes cataclysm where it is reported that shit so we all look ,thank you sir I know everything

**Closed** 2017-03-10 10:49 UTC
