### ISSUE TITLE
[EN][Raid] Lord Rhyolith HC

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#8215] opened 2016-09-10 12:55 UTC
Currently on Lord, when you dps the legs in first phase, your damage to the leg halfs itself on both legs;

If you do 40k hit on left leg, your damage splits and it hits both legs for 20k.
How it should work: If you do 40k hit on left leg, you should do 40k on right leg to.
This bug results in Harder steering and "Healing" of the boss.
And also means that in phase 1 you have 65% damage reduction ^^
http://www.wowhead.com/npc=52558/lord-rhyolith

**Comment by Aival94** [comment] 2016-09-10 15:43
"The damage done to a foot is divided equally between both feet. More precisely, every few seconds, the health of both feet is adjusted so that it becomes equal. For example, if one foot is at 48% health and the other is at 50% health, then both feet will be at 49% after the adjustment." - Source: [Lord Rhyolith](http://www.icy-veins.com/wow/lord-rhyolith-strategy-guide-normal-heroic)

It work just fine as what i can see.
If you mean that even if you dps one leg the steering damage itself split to both legs every some sec then is a bug which make steering need more burst dps on one leg to make him move to this location but last  time i did it it look like the steering damage to make him rotate is not so much so probably is not splitting but instead the boss foots just equalize their health pool.

**Comment by xolon** [comment] 2016-09-10 16:30
Ok, didn't really notice split on any of the pre nerf videos, the problem here then is. When it splits it pushes the bar a bit back to other side, it shouldn't do that, thus it makes harder to steer, and according to videos he should turn a lot faster.

**Comment by Aival94** [comment] 2016-09-10 17:04
The steering is true that is a little buggy but steering bar tend to go back to original every 1-2 sec and is blizzlike,

"It looks as if Rhyolith has some inertia. When the damage done to both his feet is no longer unequal, the Direction Gauge will have a tendency to go back to the middle." - Source: [Lord Rhyolith](http://www.icy-veins.com/wow/lord-rhyolith-strategy-guide-normal-heroic)

**Comment by Jenovas** [comment] 2016-09-16 17:30
The reported bug is not a bug. Closing issue.
If you have any other bugs please create a new issue.
Thx and cheers.

**Closed by Jenovas** 2016-09-16 17:30 UTC
