### ISSUE TITLE
[EN][Gilneas]  Worgen starting area crash,Can't play character

### ISSUE THREAD

**Issue by vordai** [Atlantiss/BugTracker#3117] opened 2015-04-27 01:20 UTC
Rolled a Worgen Druid. Completed every quest up to 'Two By Sea'.
http://www.wowhead.com/quest=14382/two-by-sea

Had no problem completing the quest. The problem happened as I was walking back across the field with the catapults,  towards the house basement to turn the quest in. Got 'ERROR 132' when I was halfway  and have been unable to log into that character since. Loading screen progress bar fills up and WoW crashes. 

I did everything listed here:
http://atlantiss.eu/community/viewtopic.php?f=10&t=1117&sid=0aba179ac746dcf570e7a32d756bb179

and I still can't log onto that toon.

**Comment by Tj20** [comment] 2015-06-14 20:49
I was not able to reproduce this issue some weeks ago, but it may have been a phasing issue (maybe you came to close to Lorna Crowley, #2493?). 

Anyways, I think it may have been fixed in [rev. 4458](http://atlantiss.eu/changelog#rev4458) by Wolffenstein.

**Closed** 2015-06-15 08:31 UTC
Labels: WoW Error
