### ISSUE TITLE
[EN][Quest][Ashenvale] Return Fire

### ISSUE THREAD

**Issue by josue1795** [Atlantiss/BugTracker#9731] opened 2017-12-28 23:21 UTC
http://www.wowhead.com/quest=13853/return-fire#comments
**Description:**
Right clicking on the Astraanar throwers don't work.
Completing this quest removes the fires and Horde attackers.

**Comment by tomatosz** [comment] 2017-12-29 11:34
Duplicate of #8084 and #7311

Also please use the [template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md).

**Comment by TranceAccount** [comment] 2018-02-28 14:50
## Posted a fix on the forum for the mounting part:

https://community.atlantiss.eu/index.php?/topic/18255-npc-astranaar-thrower-cecidit-parody/

**Comment by TranceAccount** [comment] 2018-03-01 15:08
Fix got accepted. Comment if still presists. Rev 5653.

**Closed by TranceAccount** 2018-03-01 15:08 UTC
