### ISSUE TITLE
[en][mage][talent] cauterize and additional hits ( f.ex. windfury procs)

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#6541] opened 2016-02-23 10:43 UTC
http://www.wowhead.com/spell=86949/cauterize

how it works:
when i have for example 2000 health 
shaman connects to me, hit me for 2001 damage
- cauterize procs - everythings fine

i have 2000 health
shamman connects, hit me for 2001 damage + WF procs the same attack
- cauterize doesn't activate, mage's dead.

probably works the same with warrior arms mastery ( additional attack) and other abilities/talents which adds additional hits to attack
i have no idea how could this be fixed ( idea is that the damage should be postponed somehow )

**Comment by kadi2** [comment] 2016-02-23 11:42
The old report, might be helpful. https://github.com/Atlantiss/BugTracker/issues/750

**Comment by aneq** [comment] 2016-02-23 12:36
This is because the bonus damage is dealt in the exactly same time as the hit that procced is so the spells that saves you has no chance the proc. You can easily reproduce it by going into BWD 25 HC and trying to tank a double attack on chimaeron while having over 110k hp (let's assume that a single hit will deal exactly 100k damage) Double attack will proc the same time as a normal attack, and the robot won't be able to save you, while it should.
I died way too many times tanking this :D

**Comment by Kejmil** [comment] 2016-02-23 16:36
you have 20k hp -> retri crits you with templar for 60k (this dmg is absorbed by cauter), mastery hits you for 21k hp - you are dead, no cauter
you have 2k hp - shaman melee atacks hit you for 1,5k, 3x windfury hits you for 3k each (EVERY windfury is absorbed), EVERY one of them gives cauter heal proc, mage has 100% hp and overheal xD

**Comment by Fearyourself** [comment] 2016-02-24 14:58
If I recall correctly this is a retail like bug, but I'm not sure. I know for a fact that when you hit a fire mage (as a warlock) with multiple spells landing at the same time cauterize doesn't proc

**Comment by lamaATS** [comment] 2016-10-05 21:02
Fixed in rev. 5205

**Closed by lamaATS** 2016-10-05 21:02 UTC
Labels: Class - Mage
