### ISSUE TITLE
[EN][Quest] Can You Smell What the Lok'tar is Cooking?

### ISSUE THREAD

**Issue by Dearkus** [Atlantiss/BugTracker#4388] opened 2015-08-28 18:36 UTC
http://www.wowhead.com/quest=28344/can-you-smell-what-the-loktar-is-cooking
Kingslayer Orkus NPC is missing. This blocks the main questline in Hillsbrad Foothills.

**Comment by Pallitax** [comment] 2015-08-28 22:29
Duplicate of #3807

**Closed** 2015-08-28 22:43 UTC
