### ISSUE TITLE
[EN] [Quest] [Violent Hold] Discretion is Key

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3222] opened 2015-05-10 03:46 UTC
Upon entering Vh you have no option to turn in the quest to get the VH quest. 
Quest
http://www.wowhead.com/quest=29829/discretion-is-key
End
http://www.wowhead.com/npc=30658/lieutenant-sinclari 
I posted this cause the only other one i saw was closed and its not fixed.

**Comment by Tj20** [comment] 2015-05-10 09:44
#2616 was closed because it's a duplicate of #125 I think, and that one is still open.

**Closed** 2015-05-10 09:48 UTC
