### ISSUE TITLE
[EN] [Hunter] [Marksmanship] Steady Shot

### ISSUE THREAD

**Issue by Fapguy** [Atlantiss/BugTracker#5848] opened 2016-01-12 14:19 UTC
Steady Shot doesn't work like it should.
On Atlantiss, you need to wait for steady shot to hit, on retail you just had to CAST it, to get the buff.

This makes it so you can't do anything for half a second every time you need to SS in your MM rotation. This makes marksman super weak.

https://youtu.be/nTQDIyO-v6M?t=9m

**Comment by netukerme** [comment] 2016-01-12 14:23
And Aimed Shot deal less dmg than on retail.

**Comment by Fapguy** [comment] 2016-01-12 14:33
I only have my hunter at level 80, granted all the way, and I didn't see AS being broken aswell, thank you for info.

I don't want to play SV as it's boring, so devs please fix MM.

**Comment by meowmewo** [comment] 2016-01-12 14:38
Aimed shot is not bugged. But the original report is valid. MM was good in 4.2 but we are on 4.3.4 with 4.3.4 mechanics, happy or not MM is the weakest spec to play on 4.3.4.

**Comment by netukerme** [comment] 2016-01-12 14:41
So fix it to 4.2 content?  Why atlantiss impose us to play with survi?

**Comment by Fapguy** [comment] 2016-01-12 14:47
yeah... this is not good, so me picking a hunter was a waste of time?

**Comment by Wolffenstein** [comment] 2016-01-12 15:11
"on retail you just had to CAST it, to get the buff."
What buff? Improved Steady Shot?

**Comment by Kejmil** [comment] 2016-01-12 15:21
if this issue is about focus - you can see in video you linked that focus is gained AFTER steady shot deal dmg, not AFTER cast
if this issue is about gaining imp. steady shot buff:
http://cata.openwow.com/spell=53221 r1
http://cata.openwow.com/spell=53222 r2
http://cata.openwow.com/spell=53224 r3
then this is correct

**Comment by Lanrutcon** [comment] 2016-01-12 15:42
Similar to: https://github.com/Atlantiss/BugTracker/issues/4828

**Comment by Fapguy** [comment] 2016-01-12 15:48
Yes, Lanrutcon, exactly like that.

It's "ON HIT" but should be "ON CAST".

**Comment by Wolffenstein** [comment] 2016-01-12 15:51
I still don't know which buff should proc on cast rather than on hit. Improved Steady Shot?

**Comment by meowmewo** [comment] 2016-01-12 16:05
He means the IMp steady shot i think

**Comment by Wolffenstein** [comment] 2016-01-12 17:04
Waiting on confirmation from the author...

**Comment by Kejmil** [comment] 2016-01-12 18:40
while i can't speak for author i can assure that improved steady shot talent:
http://cata.openwow.com/spell=53221 r1
http://cata.openwow.com/spell=53222 r2
http://cata.openwow.com/spell=53224 r3
is for now bugged on atlantiss - it should proc after succesfull double CAST in a row with steady shot, but it proc after the steady shot hits, which is causing a problem, f.e. chimera shot flight time is faster than steady shot (i think), so after steady+steady+chimera immediately we will not get a buff while we of course should, similiar with aimed shot in steady+steady+aimed immediately - cast time of aimed will be unaffected by imp. steady shot buff (buff appear when cast is already in progress)

**Comment by meowmewo** [comment] 2016-01-12 18:56
Yes confirmed. Due to the proc happening when the shot hits, rather then when its cast, after that if u have to cast AImed shot, ur aimed shot is not benefiting from the buff..becouse it takes longer time to get the effect. So what he ment is that he has to wait..in order the haste effect to kick in and then start casting aimed, but cuz of that waiting(0.5 sec)..the buff doesnt really help becouse ur wasting time.

**Comment by Fapguy** [comment] 2016-01-12 19:24
Yes, Improved Steady Shot, of course, sorry, maybe I should have mentioned it lol :)

**Comment by Wolffenstein** [comment] 2016-01-12 22:58
Fixed in rev 4814.

**Closed by Wolffenstein** 2016-01-12 22:58 UTC
