### ISSUE TITLE
[EN][Quest][Badlands] Eric, the Utility Dwarf

### ISSUE THREAD

**Issue by martinelrey1979** [Atlantiss/BugTracker#4281] opened 2015-08-18 01:09 UTC
It fulfills the mission is not whatever you do please verify
http://www.wowhead.com/quest=27828/eric-the-utility-dwarf

**Comment by Pallitax** [comment] 2015-08-18 06:44
Duplicate of #3302

**Closed** 2015-08-18 11:21 UTC
