### ISSUE TITLE
[En][Mage] Hot Streak vs. Imp. Hot Streak

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4595] opened 2015-09-30 17:35 UTC
## How it should be:
There should be a dr / break point between Hot Streak and Improved Hot Streak.

In bg after a fire mage hit me for 5 times consecutive in ten-fifteen seconds with Pyroblast I made myself a mage and tested

## proof:
http://forums.elitistjerks.com/topic/128507-433-fire-mage-compendium/
http://forums.elitistjerks.com/index.php?showtopic=103833#post1766032

* http://tinypic.com/r/2q8d3sl/8 (graphic 1)
* http://tinypic.com/r/23v1ahz/8 (graphic 2,chances how it should be)
#
When you have the talent Improved Hot Streak,from 25% crit, the proc chance from Hot Streak must drop to 0(when you reach 46% crit like in the graphic nr.2 above).The problem on our server it's that it never drops...and at 50%+ crit you are continiously getting Hot Streak procs.This DR i'm talking about should stop Pyro spamming while mage scales better with gear/other procs and has more and more procs from Improved Hot Streak.

T3 HS gives you no benefit above 47% crit. 
With the linear formula, T3 and T4 cross over at about 34% crit chance. That is, below 34% crit, T3 is more valuable, above that point T4 is more valuable. 
Below 19% crit, T4 HS gives you less than 1% chance per cast for a HS proc, if you have T3 HS. 
Below 9% crit, T4 HS gives you less than 0.1% chance per cast for a HS proc, if you have T3 HS.

**Comment by blinkmaster** [comment] 2015-10-23 10:01
its RNG generator bug of this server. it loves to go to the END values ( so - no crits or only crits)
in 20k or smth of hits it will be like it should but before that.... well... u see it for urself.

**Comment by Jenovas** [comment] 2015-11-16 13:08
On the server Hot Streak works like this.
Hot Streak has a chance to proc a instant pyroblast the and the chance is reduced by crit chance.
The formula is made that when you hit 33% of crit Hot Streak will stop working.
So it seems that this number should be increased to 45%, so that will probably be a little buff for fire mages.

**Comment by Kejmil** [comment] 2015-11-16 13:49
maybe shatter multiplayer should be taken into account? meaning virtually no instant pyros from single crit from frozen targets?

**Comment by blinkmaster** [comment] 2015-11-16 18:41
i remember i once read blizz us forum that it does not affect the graph ( shatter talent ). 
but need to find it out once again.

**Comment by razgal** [comment] 2015-11-16 21:19
< you hit 33% of crit Hot Streak will stop working.
Not 100% sure,but I think both Hot Streak and Imp. Hot Streak should stop working,as the graphic says T3 stops working  when they cross-over at 34% crit chance

## A little comparison with a mmo-champion topic:
**MMO-Champion**: http://www.mmo-champion.com/threads/780272-Hot-Streak-Procs
42% crit, with gear.
 100 fireballs
 12 pyroblasts

**Our server**:  http://tinypic.com/r/14cabd2/9
21% crit, with gear and food/drink
 100 fireballs
 16 pyroblasts , with 4 more and with 21% less crit. Of course rng is rng but still should be less due to 21% crit reduce.

< So it seems that this number should be increased to 45%, so that will probably be a little buff for fire mages.
Don't rush too fast the conclusion without analyzing everything,in the same topic from above says the following:
"Seems it's even lower than 46% crit. Hot Streak did not work for me at 42% crit only Improved Hot streak worked"

**Comment by Jenovas** [comment] 2015-11-22 21:05
Works as intended. With 21.5% of crit I had:
16 HS after 100 casts
10 HS after 100 casts
12 HS after 100 casts
13 HS after 100 casts 
10 HS after 100 casts

With 31% of crit I had:
14 HS with 100 casts
16 HS with 100 casts
14 HS with 100 casts
18 HS with 100 casts
15 HS with 100 casts

This as almost the same as the graphs shown above how it should work.
Closing.

**Closed by Jenovas** 2015-11-22 21:05 UTC
Labels: Class - Mage
