### ISSUE TITLE
[ENG] Stonecore

### ISSUE THREAD

**Issue by treflowa** [Atlantiss/BugTracker#4118] opened 2015-08-06 08:34 UTC
Last boss in Stonecore is bugged. She flew away from us. 
She is unkillable.

**Comment by Juau** [comment] 2015-08-06 09:05
I can confirm Hight Priestess Azil is unkillable at the moment; as soon as it is engaged, the NPC flies away.

**Comment by MasterK15** [comment] 2015-08-06 09:14
LINKS ...

**Comment by cuba1984** [comment] 2015-08-06 10:57
She is killable. Just go to a place the third boss.

**Comment by Wulgarny** [comment] 2015-08-06 21:16
Shes killable. She lands down on Ozuruk place (3rd boss), then on fly phase just wait there for adds.

**Comment by Aival94** [comment] 2015-08-07 02:35
[High Priestess Azil](http://www.wowhead.com/npc=42333/high-priestess-azil) but it might be good idea to put it to the general stonecore report which already exist i think,

https://github.com/Atlantiss/BugTracker/issues/1155

Confirmed both the bug and the way to kill her.

**Comment by Bildo** [comment] 2015-08-07 22:09
fixed by @Quban

**Closed by Bildo** 2015-08-07 22:09 UTC

**Comment by Aldergar** [comment] 2015-08-11 10:11
I dunno why you said it's fixed...because it's not.)

**Comment by Quban** [comment] 2015-08-11 10:44
coz server havent been compiled and restarted yet
