### ISSUE TITLE
[EN] Inside Arena.

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#6118] opened 2016-01-27 19:03 UTC
Hey, I wondering something,
I been check that month ago. and forgot about that, just now I spoke with GM via ticket, and he remind me that,
I will try to explain i'm not sure all of you will understand. because my english is not perfect.

What I been checked is my damage as Warlock [Affliction spec] on Friend.
Full dots (CoC, UA, Corr, Agony + Haunt (1time)] the Healthbar went from 100% to 85%
Than I full dot him again, this time I used my character to keep him in combat (with white attacks of 20,20,20) the Healthbar went from 100% to 45-40%

**I tried to make the damage without procs of anything, and i believe nothing procced.

I wonder how HP regeneration works in Arenas, I am asking that because I had alot of situations
when I'm full dotting someone, fear him, swap to arena2/arena1 (the other target)
Than I'm back to the first target who got Fear or Really far from me or I was not focused on him,
And his HP bar barely moves down. even while he had full dots on him.

It feels like my pressure as Afflictions is really sucks duo HP regen non-combat.
Or something else I can't figure out. I'm talking mostly about Arenas / Pvp zones. etc.

So Maybe it a bug? and I would like that someone will answer me.

**Comment by BialyADI** [comment] 2016-01-27 23:13
When no in combat Regen is faster.

**Comment by Illusie** [comment] 2016-01-29 12:14
@BialyADI yeah I know that,
But I felt something weird in arena as Warlock [Affliction]

Think about situation like this:
I'm attacking target1, his healthbar at 65%.
Than I fear target1, and swap to target2 (Soul swap or Manually dot him, The way does not matter), Than for the next 7-12 seconds I'm on target2.
Than I back to target1 which had 65% hp, his HP STILL stand on 65%. Like what going on?? >..<"
His hp did not dropped even 1 precent? what just happen in the last 7-12 seconds? Nothing?

Affliction is about pressure on BOTH targets [2vs2] and the problem is something make my pressure failing.
The worse is I donno what cause it, and I think it's the HP regen.

**Comment by Fearyourself** [comment] 2016-01-29 14:37
Affliction warlock here, I can confirm. When not in combat players regenerate extremely fast making dots close to useless.

**Comment by Illusie** [comment] 2016-01-31 19:45
@Fearyourself  yes but i cant point on the problem, if it the HP regeneration or something else.
I think i pretty good explained myself.

somehow i can't feel my "pressure" work as it should be on 2s.
and as affliction warlock, we are pressuring both targets at same time.
we are not suppost to make single-target damage.

annoyable ;d

@Jenovas 
@Wolffenstein 
@Aviannaqt 

hello ^?

**Comment by BialyADI** [comment] 2016-01-31 19:50
What is the problem?

**Comment by kadi2** [comment] 2016-01-31 19:57
I don't think you'll find someone that will search for that. There's just event that enables regeneration.
http://wowwiki.wikia.com/wiki/Events/P
ctrl+f "PLAYER_ENTER_COMBAT"

**Comment by Illusie** [comment] 2016-01-31 20:26
@kadi2 missunderstand.
@BialyADI I already explained and gave example of possible situation in arena.

**Comment by Wolffenstein** [comment] 2016-01-31 20:29
Find the equation for health regen out of combat.

**Comment by BialyADI** [comment] 2016-01-31 20:35
It can be easy see on many PvP videos from Cata and all looks ok.

**Comment by Illusie** [comment] 2016-01-31 20:55
@Wolffenstein Hi. as I already said. I don't know if the cause of that "feeling" I have is because of HP regeneration out of combat in pvp zones (Battlegrounds & Arena).

I just tested things in elwynn forest with a friend and @Fearyourself just confirmed that something goes wierd.

All what i am saying is I feel "weird" when my pressure fail. And as I explained, I had alot real situations in Arena when I'm on target1, fear him (**with full dots**) than swap to target2.
While that time I'm on target2. The target1 is feared+take damage from dots.

time elapse between I'm attack him again [the target1] (re-dot or something else) is around 7-12 seconds approx.

In that time (7-12 seconds) there is "gap" between what I Think should happen, and between what really happen.

What really happen:
His Health (65%) > Dots+Fear->7-12 seconds later -> His Health (65-60%). (No off heals / HoTs)
65%>65%? lol... "7-12 sec gap" of nothing. where the damage of my dots :'(

What I think should happen:
His Health (65%) > Dots+Fear> 7-12 seconds later-> His Health around (40-50% or even lower) Depends how strong my dots hit him.


That atleast how I know Affliction warlock works in arena.
We pressure both, CC healer, hitting the DPSer, Healer still taking damage,
So he have to heal himself &  the DPSer,
Than we Fear the DPSer and attacking the Healer,
But the DPSer is taking damage too..

hmmmm (>>...<<")

**Comment by BialyADI** [comment] 2016-01-31 21:03
Mayby Absorb?
And Lock can regenerate from Armor.

**Comment by Illusie** [comment] 2016-01-31 21:05
@BialyADI I'm not talking about my class.
I'm talking about facing other classes in Arena.

**Comment by Bjarzyna** [comment] 2016-02-01 05:51
Health regen might actually be bugged by a bit.
Hard to find formula for it, but it seems that level 85 out of combat regen should be 1% of max hp every 2 sec. Also "Health Regeneration is increased by 33% while sitting".
After quick testing it seems that I receive regeneration ticks of 1.333% of my max health even tho i was not sitting, so it seems like system is always applying sitting bonus.
I also think this high regeneration value is bad design, but it is blizzlike. Unless we want to drop blizzlike values and mod it to regenerate for example percentage of base health instead there's only bug fixing we can do.

**Comment by BialyADI** [comment] 2016-02-01 08:30
Where you find that values?
Blizzlike is blizzlike dont change it to custom values ;x.

**Comment by Bjarzyna** [comment] 2016-02-01 16:26
http://bug.omfg.gg/issues/3680
"on Cataclysm, Health Regen was standarized to 1% HP regen out of combat.every 2 seconds"
http://wow.gamepedia.com/Health_regeneration
"Health Regeneration is increased by 33% while sitting."
http://wowwiki.wikia.com/wiki/Patch_4.0.1_%28undocumented_changes%29
"Outside of combat, all classes seem to regenerate 0.75% of their maximum health per second"
Emphasis on "seem"
Tested again, something is off with these values on atlantiss. While standing up I regenerated from 3200 to 5120 with one tick, which compared to my 128056 health is 1.49934% (This value is backed up by undocumented patch notes). However when I sat down my health went from 4131 to 7012, which is 2.24979% of my total health and 50.052% more than when I was standing up.
Which value is correct (1% or 1.5% per tick) I don't know for sure, but i think that 1% of health is more likely. 1.5% is such a high value that you hardly ever need to eat or bandage while out of combat unless you took serious damage. Also note that troll characters get bonus to their regeneration. Running away troll hunter regeneration will outheal any dots unless he's dying already and stealth troll rogue will have close to constant stack of lifebloom.

**Comment by Jenovas** [comment] 2016-02-01 16:35
Also there is a question - should a target with DoTs doing DMG to him + being under CC leave combat?

**Comment by BialyADI** [comment] 2016-02-01 17:01
and what about Mana regen?

**Comment by Bjarzyna** [comment] 2016-02-01 18:06
Another evidence for 1% regeneration:
http://us.battle.net/wow/en/forum/topic/3182448914
The percentage regeneration is supposed to go down with level, so the fact that he had low level doesn't matter here. That's actually the best evidence for regeneration value I was able to find overall (I guess nobody discusses something so trivial as hp regen).
Also note that OP of that topic was a troll, so if value were to be 1.5% he would regenerate much more than ~1.1%.

**Comment by Bjarzyna** [comment] 2016-02-01 18:37
Another (and I believe last needed) piece of evidence:
https://www.youtube.com/watch?v=rVFbwC1ro_Y
0:53 (immediately after he won the duel) he regenerated from 56006 to 57205 health. This is 1199 regeneration tick and as you can clearly see he has 119k max health (probably close to 120k).
Can we expect a fix quite soon? It's just adjusting one value.

**Comment by Illusie** [comment] 2016-02-01 19:56
@Bjarzyna thanks for the information really helpful to make this bug report go for real.
I still don't know if the HP regeneration is the cause of the Affliction (Dot based spec) in PvP.

@Jenovas hi Jenovas, i did not understand what you asked, Hope someone else will answer,
But I will try;
In general I know that you leave combat after 7 or 8 seconds without being attacked / attacking.
when you dotted+under cc [like fear] you still in combat. fear last 7 seconds, so right after or 1 sec after the fear, you leave combat, again if not being attacked or attacking. if you being attacked or you start attack. you're in combat.

As I explained my big problem is keep my pressure on 2 targets.
when I dot+fear target1 with 65% hp, and focus target2 than back to target1 and his hp still 65%

**I repeat!!** "65%" is just number to illustrate the example, it can be any another number of HP %.

here the example:

what **REALLY** happen:
                                 <*              *fear*               *>
target1: 65% health>1--2--3--4--5--6sec/or more> still 65% health (0% hp lost)
target2: 70% health>im attacking him..> 50% health (-20% hp lost)

total hp lost -20% #pressurefail
                         
what **SHOULD** happen:
                                <*               *fear*                *>
target1: 65% health>1--2--3--4--5--6sec/or more> 50% health (-15% hp lost)
target2: 70% health>1--2--3--4--5--6sec/or more> 50% health (-20% hp lost)

total hp lost -35% #presssurework

**Comment by Illusie** [comment] 2016-02-01 19:59
More something

Fear unlike other Crowd Control is kinda "special" because It does not break or have low chance to break from DoTs

Unlike Polymorph, Sap, Hex, Trap, etc, etc.

That what make us (Affliction Warlocks) strong in arenas, and this is our "key" to win.
explained above^

**Comment by BialyADI** [comment] 2016-02-01 20:11
It is no about "special" Hex and Fear dont brake instant from Dmg.

**Comment by Jenovas** [comment] 2016-02-01 20:18
Fear unlike other Crowd Control is kinda "special" because It does not break or have low chance to break from DoTs - this is not true. Effects such as fear / hex / RoF I think too have a limit of DMG that can be dealt before the effect breaks. For example the limit is 20% HP, if you take more than 20% of your HP while under the effect of fear it will break, no matter if it was a DoT or a Direct Hit.

**Comment by BialyADI** [comment] 2016-02-01 20:27
I think that Lock have more important bugs like https://github.com/Atlantiss/BugTracker/issues/4698, no HP regen.

**Comment by Illusie** [comment] 2016-02-01 20:56
@Jenovas exactly, I just did not know how to explain it that the Fear does not break immediately.
the buttom line is targets that got Fear still take damage.
that what make us (affliction warlocks) good in arena, the "ability" to keep people take damage under the fear without let them heal themself (because of the fear they can't cast). this what we call "Pressure".

Perfect Pressure is like: (theory)

phase1:
dotting both target1+target2

phase2:
fear target1->attack on target2

phase3:
fearing target2->attack on target1

phase4:
repeat on phase1.
(fear target1->attack on target2)


In this scenario both targets (1&2) lose HP. pressure work as it intend,
If healer-dps comp (example: Disc-hunter) it make the Disc go oom quicker& harder to keep both alive.

BUT
this is not happening just because ^ all this report above.
what cause it? I still don't know.

**Comment by Bjarzyna** [comment] 2016-02-02 06:23
I opened new issue regarding health regeneration and cleaned up my regeneration posts from this one as it seems it's not the topic of the discussion.

**Comment by Jenovas** [comment] 2016-02-02 10:28
HP Regen Fixed in rev 4859
If this issue does not get fixed please do some more research and create a new issue.

**Closed by Jenovas** 2016-02-02 10:28 UTC
