### ISSUE TITLE
[EN][Talent][Paladin] Eternal Glory

### ISSUE THREAD

**Issue by Meecow** [Atlantiss/BugTracker#3233] opened 2015-05-11 04:39 UTC
http://cata.openwow.com/spell=87164

Sometimes for an unkown reason when casting Word of Glory at 3 Holy Power you are only refunded 2 Holy Power. Tested in and out of combat.

Eternal Glory should always refund the full cost when it triggers at 3 Holy Power but sometimes only refunds 2 Holy Power.

**Comment by sunshineinabox** [comment] 2015-05-11 04:56
I have noticed this also on my pally. Not sure if this is intended behavior or not, but its a pretty big problem when you are trying to stay alive.

**Comment by Frainzil** [comment] 2015-05-11 07:44
Lol, after playing it so long i now realise that its a bug :/ I always thought there was another talent that was sometimes consuming only 1 holy power when you casted Word of Glory, it seems i have been dreaming all the time. Well i never had the occasion that this talent was the reason of a wipe but still would be nice to have it fixed. :)

**Comment by Kejmil** [comment] 2015-05-11 13:00
the actual problem is that it is caused by other bug - eternal glory should have a 15s cooldown for its not consuming effect, and this "wogs for one holy power" are propably caused by it - they should consume all holy power that you have at that moment

from spellwork:

ID - 88676 Eternal Glory
Description: Restores the Holy Power spent on Word of Glory.

...
RecoveryTime: <b>15000 ms</b>, CategoryRecoveryTime: 0 ms
StartRecoveryCategory = 0, StartRecoveryTime = 0,00 ms

**Comment by Wolffenstein** [comment] 2015-10-07 18:45
Fixed in rev 4623.

**Closed by Wolffenstein** 2015-10-07 18:45 UTC
Labels: Class - Paladin, Spell - Generic
