### ISSUE TITLE
[EN][NPC] High Thane Jorfus phasing

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/BugTracker#9263] opened 2017-06-15 09:05 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: [High Thane Jorfus](http://www.wowhead.com/npc=32501/high-thane-jorfus) is in a different phase than the players when he spawns just west of ICC.

**Current behaviour**: When he spawns he does trigger NPCScan, and he rarely walks out of the phased area (towards the area with Boneguard Footman), but then before he can be attacked he already walks out of phase again.
Edit: not sure whether he triggers NPCScan while out of phase, can't get it to trigger now but I don't know whether that is because of the phase or if someone managed to kill him in the meantime.
Edit2: yup, only triggers when he comes in phase for a moment.

**Expected behaviour**: High Thane Jorfus should be in any phase so players can always attack him.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: rev. 5434

**Comment by Sayris9876** [comment] 2017-06-15 19:07
The phasing there is caused by quests I have seen him few times without him phasing out but i did all the quests in Icecrown and some of the lasts quests are changing the phasing around there + i think some of AT quests change phase too not sure.

**Comment by Samineh** [comment] 2017-08-19 00:00
yeah noticed the same bug today. Luckily I have killed him before doing AT or Icecrown quests.

**Comment by tomatosz** [comment] 2017-12-28 21:58
Posted a fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15539-npc-high-thane-jarfus/

**Comment by Piklo** [comment] 2018-01-19 19:28
should be fixed in [rev. 5608](https://atlantiss.eu/changelog#rev5608)

**Closed by Piklo** 2018-01-19 19:28 UTC
Labels: CF, NPC, Phasing, Quest, Wrath of the Lich King
