### ISSUE TITLE
[EN] [Talent] Mage - Shatter's 20%  dmg calculation

### ISSUE THREAD

**Issue by flashxx** [Atlantiss/BugTracker#6494] opened 2016-02-20 15:55 UTC
Hello,

In general, the damage, whether it hits or misses etc., of a spell is calculated the moment it is finished casting.
Currently the 20% damage increase of shatter is calculated when frostbolt lands, instead of when it is finished casting which is incorrect.

On the first screenshot you can see that I freeze my target. Cast frostbolt and break the freeze before it reaches the target, doing 871. It is only affected by the bonus crit but not dmg bonus of the talent.
On the second screenshot I show you frosbolt dmg on target which is frozen when the spell reaches it.
If we calculate : 817 * 1.20 = 1045 we can see how much damage frostbolt should have done on the first screenshot.

1) http://i.imgur.com/LAuzW25.jpg
2) http://i.imgur.com/iLz2buP.jpg

Thanks.

**Comment by gurin** [comment] 2016-02-20 18:08
http://wowwiki.wikia.com/wiki/Shatter
Works as intended.

**Comment by flashxx** [comment] 2016-02-20 18:34
Maybe you should've read my comment and the link you pasted first before replying...
Quote: "The check to see if the target is frozen, and thus the critical strike check, is done at the time the cast completes"

**Comment by blinkmaster** [comment] 2016-02-20 19:15
Confirming, pretty huge. I never saw that coz i assumed if it crits then it benefits

**Comment by gurin** [comment] 2016-02-21 03:18
@flashxx Maybe just practice to land Frostbolt+Lance at the same time? If you break nova with instant FireBlast why you expect FrostBolt 0,5sec later will benefit from Shatter?

**Comment by flashxx** [comment] 2016-04-17 20:56
Any news on this? It's very important talent for pvp, and I don't imagine it's hard to fix it.

**Comment by kadi2** [comment] 2016-04-17 21:46
You didn't even post any proof for it. Why you are expecting a fix?

**Comment by Lanrutcon** [comment] 2016-04-18 01:26
> You didn't even post any proof for it. Why you are expecting a fix?
https://www.youtube.com/watch?v=dRgZhRtG8es
At 6:40 - He casts "pet nova" while Frostbolt is flying and he got no +20% bonus damage even though  target was frozen when Frostbolt reached the target.

During multiple times, he casts Frostbolt at frozen targets and the damage is around ~14k damage. Against no-frozen targets the damage is ~11k.

**Comment by blinkmaster** [comment] 2016-04-18 09:27
Nah its not like this Lanrut.
IT should work like this: i cast frostbolt, target is frozen when cast end and it gets x3 crit and 1.2 multiplier.
How it works. We cast frostbolt, target is frozen when cast end. Frostbolt is flying, frozen effect end. Fb benefits from 3x crit but not from 1.2 multiplier. Its all about the fact it should work simulitanously

**Comment by blinkmaster** [comment] 2016-04-18 09:35
And in the movie provided mage doesnt know i think that shatter doesnt benefit spells in the air and he needs to cast pet freeze before cast end (sorry for multipost Ima on phone

**Comment by Lanrutcon** [comment] 2016-04-18 11:29
The problem is that if you try to do it like the mage did on the video (pet nova after casting Frostbolt), you **will get the 20% bonus damage**. http://i.imgur.com/e0LoHa1.png

It's just like the OP said, the bonus is being added on hit, not when you finish the cast.

**Comment by kadi2** [comment] 2016-04-18 15:30
Everyone know that's reasonable due to the fact it works like that with mastery, but everything about Frostbolt stacks multiplicative with eachother. Was considering possibility as another mechanic that would just work diffrently.

**Comment by blinkmaster** [comment] 2016-04-18 17:48
ill try to chekc out some good high rated mages arena videos later. its gonna be possible to see it specially with DF dispel when fb is in the air etc. hopefully ill find something for this

**Comment by blinkmaster** [comment] 2016-10-25 11:24
@lamaATS 
repo upload plox :d

**Comment by lamaATS** [comment] 2016-10-26 22:47
Fixed in rev. 5227

**Closed by lamaATS** 2016-10-26 22:47 UTC
Labels: Class - Mage

**Comment by blinkmaster** [comment] 2016-10-26 23:17
<3

**Comment by lamaATS** [comment] 2016-10-26 23:24
But please stop using @ when it's not needed.
