### ISSUE TITLE
[EN][Talent][Mage] Master of Elements

### ISSUE THREAD

**Issue by drlinux92** [Atlantiss/BugTracker#1955] opened 2015-02-01 00:06 UTC
I noticed a new positive bug on mages!
Talent: http://www.wowwiki.com/Master_of_Elements

Basically it refunds mana cost after every Fireball and Scorch hits(non crits). The talent's description says clearly: "Your spell CRITICALS will refund 15/30% of their base mana cost"!

Update: added screenshot results nearly for all spells: http://imgur.com/a/NpLgF#0
A1: Master of Elements <b>giving mana</b> back on these spells after <b>normal(non-crit)</b> hits:
-arcane blast
-arcane explosion
-blast wave
-cone of cold
-dragon's breath
-fireball
-fireblast
-flamestrike
-frost bolt
-frostfire bolt
-ice lance
-pyroblast
-scorch
-frost nova
-arcane barrage

A2: Master of Elements giving <b>NO</b> mana back on these spells after <b>critical</b> hits:
-blizzard
-combustion
-flame orb
-molten armor
-arcane missiles

**Comment by Arcadia713** [comment] 2015-02-01 01:28
I can confirm - every spell refunds 15/30% their base mana cost, even with Normal hit. I tested practically every spell in fire, frost, arcane and only Blizzard doesn't give mana back (even with critical hits).

**Comment by garnbirt** [comment] 2015-02-01 10:52
This bug aint working for me lvl 85 mage, i think youre unlucky to have enemies which only crip on you or you are lucky to have so many crits.

**Comment by garnbirt** [comment] 2015-02-01 10:52
ofc crits do refund the mana but not non crits

**Comment by drlinux92** [comment] 2015-02-01 11:07
Hmm sounds interesting. You might be the one who's lucky or the issue is fixed. Don't know yet, i didn't test it today. But i can prove that i dont get any crits and still the mana is refunded + the incoming hits from mobs are not in the case coz im doing these tests on training dummies. As you can see the above guy has the same issue so i'm/we aren't the only ones

**Comment by Arcadia713** [comment] 2015-02-01 11:08
Just make some tests garnbirt and put screenshot like mine, because i asked few mages and they have that problem aswell.

**Comment by drlinux92** [comment] 2015-02-01 11:11
Btw thank you for your helpful screenshots Arcadia. When I'll have some free time, I'll upload some aswell. :)

**Comment by drlinux92** [comment] 2015-02-01 14:41
The promised screenshot results on nearly all spells: http://imgur.com/a/NpLgF#0

**Comment by Wolffenstein** [comment] 2015-02-05 12:46
Fixed in rev 4306. It was bugged on rank 1 and 2, but working properly on rank 3.

**Closed by Wolffenstein** 2015-02-05 12:46 UTC

**Comment by drlinux92** [comment] 2015-02-05 13:16
Very nice, it's fixed now - thank you :)
