### ISSUE TITLE
[EN][Mage] Arcane T12 4 Set Bonus

### ISSUE THREAD

**Issue by kostas4949** [Atlantiss/BugTracker#6371] opened 2016-02-13 00:15 UTC
Arcane power should reduce current mana cost by 10%, not base mana cost of spells.
In the start it was based on base mana cost, but they changed it around 1 month into patch 4.2.
Forum topic: http://us.battle.net/wow/en/forum/topic/3082033369 post 4 and 5

EJ Topic: http://forums.elitistjerks.com/forums/topic/117088-cataclysm-arcane-mage-compendium/?do=findComment&comment=1915951 starting from this post and it goes on for 2 more pages.

There is also SS proof in EJ topic dated 21 july 2011:
![wowscrnshot_071811_191626](https://cloud.githubusercontent.com/assets/11000444/13023996/832642ea-d1f7-11e5-8841-dc8c6baae8f4.jpg)

This is how it currently works on atlantiss (base mana reduction):
![wowscrnshot_021316_022748](https://cloud.githubusercontent.com/assets/11000444/13024140/87db85dc-d1f9-11e5-8aad-69e35053e145.jpg)

**Comment by xolon** [comment] 2016-02-13 02:16
That gearscore addon >.>

**Comment by kostas4949** [comment] 2016-02-13 08:54
@xolon Sounds very relevant and important for this bug report.

**Comment by blinkmaster** [comment] 2016-02-13 10:09
yup i also mentioned few bugs ago that it was stealthy hotfixed later on in 4.2

**Comment by kostas4949** [comment] 2016-02-13 10:13
Yeah, because of your comment I had a look into it. But it was reported together with other bugs and when the other bugs were fixed the report got closed, that's why I created a report just for this.

**Comment by Netherstrider** [comment] 2016-03-10 16:24
I can confirm this problem on my Mage too. Tier 12 4-set bonus decreases mana cost of spells by only 10% of their base value. This is relevant for Arcane Blast and not that much (it at all) for other spells, but it's an important issue since Arcane Blast is the backbone of Arcane Mage damage output.

It seems that the set bonus decreases Arcane Blast mana cost by 87, regardless of number of stacks, which is exactly 10% of it's base mana cost of 871.

This image shows mana cost without Arcane Power for different stacks:
![no power](https://cloud.githubusercontent.com/assets/17726039/13676122/c9fbb81a-e6e4-11e5-918c-8345684009ec.png)

and this one with Arcane Power:
![power](https://cloud.githubusercontent.com/assets/17726039/13676135/da650abc-e6e4-11e5-8af8-7bd5653fce81.png)

As you can see, the difference is always 87 or 88, when it should be dependant of the current mana cost.

**Comment by grigorlives** [comment] 2016-06-10 12:05
BUMP! High priority for arcane mages, needs a fix asap or we have to farm heroic t11 which is better than normal t12 without working 4p bonus.

**Comment by lamaATS** [comment] 2016-10-07 22:23
Fixed in rev. 5207
We are unable to fix client side visual (sorry)

**Closed by lamaATS** 2016-10-07 22:23 UTC
Labels: Class - Mage, Item

**Comment by kostas4949** [comment] 2016-10-08 10:15
Lama you are my hero <3
