### ISSUE TITLE
EN[Druid][Talent] Heart of the Wild

### ISSUE THREAD

**Issue by mati865** [Atlantiss/BugTracker#6903] opened 2016-03-19 22:43 UTC
Without bear form 5876 stamina unbuffed.

Rank 0 HotW:
Bear 7405 stamina (==5876 x 1.2 x 1.05, 20% stamina from bear form and 5% from leather spec; all fine)

Rank 1 HotW:
Bear 7429 stamina (==5876 x 1.2 x 1.05 x 1.0032; 0.32% increase instead of 2%)

Rank 2 HotW:
Bear 7454 (==5876 x 1.2 x 1.05 x 1.0066; 0.66% increase instead of 4%)

Rank 3 HotW:
Bear 7479 (==5876 x 1.2 x 1.05 x 1.00993; 0.993% increase instead of 6%)

Testing procedure:
1. Reset talents
2. Logout && Log in
3. Put 1 by 1 talent
4. Repeat 1-3

P.S.
Forgot to test int
Id:
http://cata.openwow.com/spell=17003
http://cata.openwow.com/spell=17004
http://cata.openwow.com/spell=17005

EDIT: Removed Cat's AP calculation since it works after logout.

**Comment by Chromiell** [comment] 2016-04-06 13:10
I'm still level 80 on my Druid, but i run some tests with Heart of the Wild. The results are that the AP portion for Cat form is actually working as intended, in fact from 5450 i go up to 5995 which is exactly 10% more, the only issue is that it requires a relog before getting the right stats, if you try doing it without reloggin it doesn't calculate the correct stats.

Now about the Bear's stamina. Without buffs and in normal form i have 1970 stamina, when i enter bear form i get 2507 stamina which is around 27% extra, now if we subtract 20% stamina that i get passivly from Bear Form it leaves me with a 7% extra which should actually be correct. The problem is that that extra 6-7% doesn't actually comes from the Heart of the Wild talent, in fact if i don't get Heart of the Wild (i leave it 0/3) i still have a bonus 25% extra stamina in Bear Form (2482) so there is something in Feral spec that actually increases your stamina by 5%, Heart of the Wild only increases stamina by an additional 1-2%. If we add the bonus from Heart of the Wild and this random 5% that comes out of nowhere when you pick Feral Specializzation, you actually have almost the exact amount of stamina that you are expected to have (only a tiny bit more, something like 0.5%)

This is the build i used for the testing in case you want to replicate my steps: http://i.imgur.com/yCqzfyZ.png

Cheers.

**Comment by mati865** [comment] 2016-04-06 13:28
Stamina bonuses are multiplicative that means you calculate it like I did at rank 0 of the HotW:
5876 x 1.2 x 1.05; 20% stamina from bear form and 5% from leather spec
So for rank 3 it should be:
5876 x 1.2 x 1.05 x 1.06 while now it's 5876 x 1.2 x 1.05 x 1.00993.

**Comment by Chromiell** [comment] 2016-04-06 13:48
Oh yeah i forgot about Leather Spec so whatever i said is invalid, you are right then, Heart of the Wild **doesn't** provide the correct amount of Stamina while in Bear Form although it does give you 10% AP in Cat Form (so at least this part should be working as intended), i didn't test the Int part tho so that may be bugged too.

**Comment by mati865** [comment] 2016-04-06 14:36
Just tested Cat and you are right. Usually you have to log out and log in to gain AP. Although sometimes it adds AP without logging out.

**Comment by mati865** [comment] 2016-05-18 08:32
Is more feedback needed?

**Comment by Jenovas** [comment] 2016-06-26 16:49
Fixed in rev 5066

**Closed by Jenovas** 2016-06-26 16:49 UTC
Labels: Class - Druid
