### ISSUE TITLE
[EN][Quest][Badlands] Baelog, the Glass Cannon

### ISSUE THREAD

**Issue by martinelrey1979** [Atlantiss/BugTracker#4282] opened 2015-08-18 01:10 UTC
It fulfills the mission is not whatever you do please verify
http://www.wowhead.com/quest=27834/baelog-the-glass-cannon

**Comment by Pallitax** [comment] 2015-08-18 06:43
Duplicate of #3303

**Closed** 2015-08-18 11:21 UTC
