### ISSUE TITLE
[EN][shaman][spell] Chain heal on target with riptide

### ISSUE THREAD

**Issue by gawronpl** [Atlantiss/BugTracker#6324] opened 2016-02-10 11:17 UTC
Consuming riptide hot by Chain Heal should improve healing done by entire CH by 25%, currently it improves healing just on first target. It makes t12 second set bonus useless.

**Comment by Aviannaqt** [comment] 2016-02-12 18:49
links

**Comment by lamaATS** [comment] 2016-10-05 22:20
It's working as intended.
Riptide:
`Your next Chain Heal cast on that primary target within 15 sec will consume the healing over time effect and increase the amount of the Chain Heal by 25%.`

T12 4p:
`Your Chain Heal spell no longer consumes your Riptide effect on the primary target.`

For me first means heal will be increased by 25% only if Primary target is affected by Riptide and will be consumed but if You have T12 4p Riptide will not be consumed.

If I am wrong give proof.

**Comment by gawronpl** [comment] 2016-10-11 23:46
[http://eu.battle.net/forums/en/wow/topic/4784318770]

> Riptide boosts the whole link of chain heal, as long as you chain the person with riptide on first (riptide is consumed in this effect).

Riptide on 1st target should be removed (w/o t12), and all CH jumps should be boosted.

**Comment by lamaATS** [comment] 2016-11-01 17:52
`and all CH jumps should be boosted`
I don't know where I had my mind when I wrote my last comment.

Sorry for delay (long 21 days) but I got too many spam on my email sorry.

**Comment by lamaATS** [comment] 2016-11-12 01:35
Fixed in rev. 5245

**Closed by lamaATS** 2016-11-12 01:35 UTC
Labels: Class - Shaman
